# RAG Evaluation Test Set Generation

This example shows how to use the [Ragas](https://docs.ragas.io/en/stable/) (```v 0.1.22```) framework to generate a **test set** that can be used to evaluate the quality of a RAG pipeline. We then use the Python [LangChain](https://python.langchain.com/docs/introduction/) library to run some requests through this pipeline and we evaluate the quality of the results.

### <u>Requirements</u>
1. As you will accessing the LLMs and embedding models through Vector AI Engineering's Kaleidoscope Service (Vector Inference + Autoscaling), you will need to request a KScope API Key:

      Run the following command (replace ```<user_id>``` and ```<password>```) from **within the cluster** to obtain the API Key. The ```access_token``` in the output is your KScope API Key.
  ```bash
  curl -X POST -d "grant_type=password" -d "username=<user_id>" -d "password=<password>" https://kscope.vectorinstitute.ai/token
  ```
2. After obtaining the `.env` configurations, make sure to create the ```.kscope.env``` file in your home directory (```/h/<user_id>```) and set the following env variables:
- For local models through Kaleidoscope (KScope):
    ```bash
    export OPENAI_BASE_URL="https://kscope.vectorinstitute.ai/v1"
    export OPENAI_API_KEY=<kscope_api_key>
    ```
- For OpenAI models:
   ```bash
   export OPENAI_BASE_URL="https://api.openai.com/v1"
   export OPENAI_API_KEY=<openai_api_key>
   ```

## Set up the RAG workflow environment

#### Import libraries

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
#!pip install pdfplumber

In [5]:
#import pdfplumber

In [6]:
import numpy as np
import os
import sys

from datasets import Dataset
from pathlib import Path

from langchain.chains import RetrievalQA
from langchain.document_loaders.pdf import PyPDFDirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_huggingface.embeddings import HuggingFaceEmbeddings
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

from ragas import evaluate
from ragas.metrics import Faithfulness, ContextPrecision, AnswerCorrectness
from ragas.testset import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context

#### Load config files

In [7]:
# Add root folder of the rag_bootcamp repo to PYTHONPATH
current_dir = Path().resolve()
parent_dir = current_dir.parent
sys.path.insert(0, str(parent_dir))

In [8]:
from utils.load_secrets import load_env_file
load_env_file()

#### Set up some helper functions

In [9]:
def pretty_print_docs(docs):
    print(
        f"\n{'-' * 100}\n".join(
            [f"Document {i+1}:\n\n" + d.page_content for i, d in enumerate(docs)]
        )
    )

#### Make sure other necessary items are in place

In [10]:
# Look for the source_documents folder and make sure there is at least 1 pdf file here
contains_pdf = False
documents_path = "./source_documents"
if not os.path.exists(documents_path):
    print(f"ERROR: The {documents_path} subfolder must exist under this notebook")
for filename in os.listdir(documents_path):
    contains_pdf = True if ".pdf" in filename else contains_pdf
if not contains_pdf:
    print(f"ERROR: The {documents_path} subfolder must contain at least one .pdf file")

## Generate a sythentic test set

#### Start by loading in the documents we'll be using to augment our RAG generations

In [11]:
# skip the next step

In [12]:
#loader = PyPDFDirectoryLoader(documents_path)
#documents = loader.load()
#for document in documents:
#    document.metadata['file_name'] = document.metadata['source']
    
#%%time
# Load the IBIS pdfs
#directory_path = "./source_documents"
directory_path = "/projects/RAG2/scotia-2/Datasets-Scotia-2/IBIS"
loader = PyPDFDirectoryLoader(directory_path)
docs = loader.load()
print(f"Number of source documents: {len(docs)}")
for document in docs:
    document.metadata['file_name'] = document.metadata['source']
# Split the documents into smaller chunks
#text_splitter = RecursiveCharacterTextSplitter(chunk_size=3600, chunk_overlap=32)
#chunks = text_splitter.split_documents(docs)
#print(f"Number of text chunks: {len(chunks)}")

Number of source documents: 280

In [13]:

from langchain.document_loaders import TextLoader

In [14]:
directory_path  ='/projects/RAG2/scotia-2/Datasets-Scotia-2/PDF_text'

documents=[]
for filename in os.listdir(directory_path):
    if filename.endswith('.txt'):
        file_path = os.path.join(directory_path, filename)
        print (file_path)
        loader = TextLoader(file_path)

        # Load the document

        document = loader.load()
        documents = documents+ document
        #chunks2 =text_splitter.split_documents(document)
        #print(f"Number of text chunks: {len(chunks2)}")
        #chunks= chunks +chunks2

/projects/RAG2/scotia-2/Datasets-Scotia-2/PDF_text/11114CA Wheat Farming in Canada Industry Report.txt
/projects/RAG2/scotia-2/Datasets-Scotia-2/PDF_text/48422CA Local Specialized Freight Trucking in Canada Industry Report.txt
/projects/RAG2/scotia-2/Datasets-Scotia-2/PDF_text/44111CA New Car Dealers in Canada Industry Report.txt
/projects/RAG2/scotia-2/Datasets-Scotia-2/PDF_text/48412CA Long-Distance Freight Trucking in Canada Industry Report.txt
/projects/RAG2/scotia-2/Datasets-Scotia-2/PDF_text/33639CA Auto Parts Manufacturing in Canada Industry Report.txt
/projects/RAG2/scotia-2/Datasets-Scotia-2/PDF_text/48423CA Long-Distance Specialized Freight Trucking in Canada Industry .txt
/projects/RAG2/scotia-2/Datasets-Scotia-2/PDF_text/11115CA Corn Farming in Canada Industry Repor.txt

In [15]:
type(document)

list

#### Now use OpenAI to generate a test set from the data in these documents (This takes about 2-3 minutes)

**IMP Note:** The LLM and embedding model used for test set generation should be more capable than the model being evaluated. Hence, we will use OpenAI GPT-4o and OpenAI embeddings for this purpose.

Store your OpenAI API key in ```~/.ragas_openai.env``` using the following format (this is in addition to ```~/.kscope.env```):

```bash
export RAGAS_OPENAI_BASE_URL="https://api.openai.com/v1"
export RAGAS_OPENAI_API_KEY=<openai_api_key>
```

In [16]:
from utils.load_secrets import load_env_file_ragas
load_env_file_ragas()

In [17]:
os.environ["RAGAS_OPENAI_BASE_URL"]

'https://api.openai.com/v1'

In [18]:
generator_llm = ChatOpenAI(
    model="gpt-4o",
    base_url=os.environ["RAGAS_OPENAI_BASE_URL"],
    api_key=os.environ["RAGAS_OPENAI_API_KEY"],
)
generator_embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small",
    base_url=os.environ["RAGAS_OPENAI_BASE_URL"],
    api_key=os.environ["RAGAS_OPENAI_API_KEY"],
)

In [19]:
# skip the next line

In [35]:
%%time
#generator_llm = (
#    model="DeepSeek-R1-Distill-Llama-8B",
#    base_url=os.environ["OPENAI_BASE_URL"],
#    api_key=os.environ["OPENAI_API_KEY"],
#)
# Define the RAG embeddings model (different than the OpenAI embedding model defined above for test set generation)
model_kwargs = {'device': 'cuda', 'trust_remote_code': True}
encode_kwargs = {'normalize_embeddings': True} # set True to compute cosine similarity
print(f"Setting up the RAG LLM...")
llm = ChatOpenAI(
    #model="DeepSeek-R1-Distill-Llama-8B",
    model="Meta-Llama-3.1-8B-Instruct",
    temperature=0,
    max_tokens=256,
    base_url=os.environ["OPENAI_BASE_URL"],
    api_key=os.environ["OPENAI_API_KEY"],
)

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-base-en-v1.5",
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
)

Setting up the RAG LLM...
CPU times: user 369 ms, sys: 228 ms, total: 597 ms
Wall time: 1.18 s

In [25]:
generator_llm.generate('what is  the day today?, Answer in no more then 10 words')

LLMResult(generations=[[ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-3f776630-e2c2-49f4-801f-8660e711d9a0-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-0cb7a60f-ad81-48d0-adeb-27d53e0b6e79-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_192567ecc1', 'finish_reason': 'stop', 'logprobs': None}, id='run-0932c3e9-01d0-4cd2-b5b1-02f519e6a5aa-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='It looks like your message might have been cut off or sent by mistake. Could you please provide more details or clarify your question?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='It looks like your message might have been cut off or sent by mistake. Could you please provide more details or clarify your question?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 27, 'prompt_tokens': 8, 'total_tokens': 35, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-c11e02cf-d488-4bac-b5e0-58c6b58c0b2f-0', usage_metadata={'input_tokens': 8, 'output_tokens': 27, 'total_tokens': 35}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-1030a0d9-4e6f-4cbd-9b1d-c8111d36d431-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_192567ecc1', 'finish_reason': 'stop', 'logprobs': None}, id='run-45b37a73-e9f1-4eb3-b8e8-06a3c87aa60e-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-5d6c984c-50c2-484d-a04f-347016c604a4-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-c08496e5-3836-4e4b-8b7e-9b0e3a0bacc1-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-12990d00-4c49-4368-b087-299bbaf0c6db-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='It looks like your message got cut off. Could you please provide more details or clarify what you need help with?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='It looks like your message got cut off. Could you please provide more details or clarify what you need help with?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 24, 'prompt_tokens': 8, 'total_tokens': 32, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-6a964bcc-295e-47c7-be41-5c7f4c0b131c-0', usage_metadata={'input_tokens': 8, 'output_tokens': 24, 'total_tokens': 32}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-a6d1f46e-931e-4204-949b-ce924b9bbdc2-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-fe560583-86fa-4866-91f2-ff1b51073a1d-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-66fc3bc9-1543-4675-9a13-95fca79cadca-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-e561366a-1e77-47cf-931d-975dcd212e75-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-1c83bd31-fb7f-41b9-a38c-c3814712fece-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-f0816377-85d2-41cb-a2c5-bc78b3a73889-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-7d6e17d1-1899-4879-a649-049a3fada20d-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-da162d65-cce1-4429-8eb1-68aa6927d232-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-f40c3ad9-346a-41ab-a740-ef2121b4a7d5-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-b0b5ecdd-2316-4957-8453-3513f025e316-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-b8d8ea45-155a-42a0-a2e4-5d30b85fcb01-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 8, 'prompt_tokens': 8, 'total_tokens': 16, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_192567ecc1', 'finish_reason': 'stop', 'logprobs': None}, id='run-741ad048-f3f9-45b1-87fe-1edbda1260c0-0', usage_metadata={'input_tokens': 8, 'output_tokens': 8, 'total_tokens': 16}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-54dcacbd-3a6c-4d72-a51d-7f6cd2b2f015-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_4691090a87', 'finish_reason': 'stop', 'logprobs': None}, id='run-c59e62f9-0dce-429d-855d-479e92bd3cb2-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'prompt_tokens': 8, 'total_tokens': 18, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-4o-2024-08-06', 'system_fingerprint': 'fp_50cad350e4', 'finish_reason': 'stop', 'logprobs': None}, id='run-ae9b882f-34d7-4461-b85c-ec689b4599d6-0', usage_metadata={'input_tokens': 8, 'output_tokens': 10, 'total_tokens': 18}))], [ChatGeneration(text='Hello! How can I assist you today?', generation_info={'finish_reason': 'stop', 'logprobs': None}, message=AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 10, 'pro

In [ ]:
%%time
# Create generator with OpenAI model
generator = TestsetGenerator.from_langchain(
    generator_llm=generator_llm,
    critic_llm=generator_llm,
    embeddings=generator_embeddings,
)

# Generate the test set
testset = generator.generate_with_langchain_docs(
    documents=documents, 
    test_size=1,
    distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25},
)

In [18]:
%%time
# Create generator with OpenAI model
generator = TestsetGenerator.from_langchain(
    generator_llm=generator_llm,
    critic_llm=generator_llm,
    embeddings=generator_embeddings,
)

# Generate the test set
testset = generator.generate_with_langchain_docs(
    documents=documents, 
    test_size=1,
    distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25},
)

embedding nodes:   0%|          | 0/260 [00:00<?, ?it/s]

RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

#### Preview the test dataset so far

In [19]:
testset1 = testset.to_pandas()

In [20]:
# testset1.to_parquet ('../../Testing_Data/testset_llama.parquet')
# testset1.to_csv ('../../Testing_Data/testset_llama.csv', index =False)

In [27]:
import joblib

In [25]:


# Save (serialize) the object to a file
joblib.dump(testset, "../../Testing_Data/testset_openai_clean.pkl")

['../../Testing_Data/testset_openai_clean.pkl']

In [22]:
testset1.to_parquet ('../../Testing_Data/testset_openai_clean.parquet')
testset1.to_csv ('../../Testing_Data/testset_openai_clean.csv', index =False)

In [28]:
#load 
# Load (deserialize) the object from file
testset = joblib.load("../../Testing_Data/testset_openai_clean.pkl")

In [27]:
print (testset==testset2)

True

## Now, start the RAG pipeline!

#### Choose the RAG LLM and embedding model
Note: This is different than the OpenAI LLM and embedding model defined above for test set generation.

In [29]:
RAG_LLM_MODEL_NAME = "Meta-Llama-3.1-8B-Instruct"
RAG_EMBEDDING_MODEL_NAME = "BAAI/bge-base-en-v1.5"

#### Generate answers for all the questions in our test set

Go through the embedding, storage and retrieval steps.

In [30]:
# Split the documents into smaller chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=3000, chunk_overlap=32)  ### Change Chunks here 
chunks = text_splitter.split_documents(documents)
print(f"Number of text chunks: {len(chunks)}")

Number of text chunks: 193

In [31]:
# Define the RAG embeddings model (different than the OpenAI embedding model defined above for test set generation)
model_kwargs = {'device': 'cuda', 'trust_remote_code': True}
encode_kwargs = {'normalize_embeddings': True} # set True to compute cosine similarity

print(f"Setting up the RAG embeddings model...")
embeddings = HuggingFaceEmbeddings(
    model_name=RAG_EMBEDDING_MODEL_NAME,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
)
print (f"setting up {RAG_EMBEDDING_MODEL_NAME}")

Setting up the RAG embeddings model...
setting up BAAI/bge-base-en-v1.5

In [32]:
# Create the vector store and the retriever
vectorstore = FAISS.from_documents(chunks, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

In [33]:
RAG_LLM_MODEL_NAME

'Meta-Llama-3.1-8B-Instruct'

In [38]:
%%time
# Define the RAG LLM (different than the OpenAI LLM defined above for test set generation)
print(f"Setting up the RAG LLM...")
llm = ChatOpenAI(
    model=RAG_LLM_MODEL_NAME,
    temperature=0,
    max_tokens=256,
    base_url=os.environ["OPENAI_BASE_URL"],
    api_key=os.environ["OPENAI_API_KEY"],
)
print (f"setting up {RAG_LLM_MODEL_NAME}")

Setting up the RAG LLM...
setting up Meta-Llama-3.1-8B-Instruct
CPU times: user 21 ms, sys: 4.14 ms, total: 25.1 ms
Wall time: 23.8 ms

Iterate over the questions in our synthetic testset, and run them each through the RAG pipeline to see what answers get returned. (This also takes 2-3 minutes)

In [46]:
%%time
#USe OpenAi

dataset = testset.to_dataset()
answers = np.empty(len(dataset), dtype=object)

for index, row in enumerate(dataset):
    query = row["question"]
    
    # Run the query through the RAG pipeline
    rag_pipeline = RetrievalQA.from_llm(
        llm=generator_llm,
        retriever=retriever
    )
    answer = rag_pipeline.invoke(input=query)
    answer = answer["result"]
    print(f"Result {index}\nQuestion: {query}\nAnswer: {answer}\n")
    
    # Store the result
    answers[index] = answer

Result 0
Question: Here is a question that can be fully answered from the given context:

"What drives the demand for dry bulk transportation in the local specialized freight trucking industry in Canada?"

This question can be answered by referencing the context, which states that "Dry bulk transportation swells alongside construction activity" and that "Strong construction activity has supported this segment but is expected to trend downward through the end of 2024 as tightened monetary policy pressures businesses' financing ability.
Answer: The demand for dry bulk transportation in the local specialized freight trucking industry in Canada is driven by construction activity. Mining companies and farmers use specialized freight companies' trucks to transport commodities like coal, iron ore, corn, wheat, and other dry bulk goods. Additionally, construction companies use these services to transport materials such as gravel and cement to construction sites. Strong construction activity has supported this segment, although it is expected to trend downward through the end of 2024 due to tightened monetary policy affecting businesses' financing ability.

Result 1
Question: Here is a question that can be fully answered from the given context:

"What are the expected outcomes of the government's pro-immigration policies on the driver shortage and turnover in the long-distance specialized freight trucking industry in Canada?
Answer: The expected outcomes of the government's pro-immigration policies on the driver shortage and turnover in the long-distance specialized freight trucking industry in Canada include alleviating pressure from high driver turnover and vacancies. The introduction of the Express Entry initiative aims to expedite immigration, enabling migrant workers to arrive in Canada within six months of applying. This initiative is designed to quickly bring in new truckers to replace retiring employees and those not keen on the trucker lifestyle, potentially reducing the driver shortage and improving workforce stability in the industry.

Result 2
Question: Here is a question that can be fully answered from the given context:

"What is the expected impact of the rebound in economic growth on the demand for freight transportation services in Canada?
Answer: The expected impact of the rebound in economic growth on the demand for freight transportation services in Canada includes an increase in demand driven by increased consumer spending and construction investments. As the economy improves and consumer spending rises, manufacturing and retail activity are expected to climb, which in turn will increase the need for product transportation. The rebound in economic growth is also expected to drive distribution services across specialized freight transport, supporting expansion after a muted performance between 2019 and 2024. Additionally, the value of trade into and out of Canada is projected to increase, further driving demand for freight transportation services.

Result 3
Question: Here is a question that can be fully answered from the given context using the topic "E-commerce growth":

question: "What is driving the growth of e-commerce in the long-distance freight trucking industry in Canada?
Answer: The growth of e-commerce in the long-distance freight trucking industry in Canada is driven by the expanding presence of e-commerce and more merchants requiring order fulfillment. This has led to gains in the less-than-truckload (LTL) segment, as smaller establishments benefit from cheaper shipments.

Result 4
Question: Here is a question that can be fully answered from the given context:

"What is the average debt ratio of corn farming enterprises in Canada, based on the data from 2018 to 2022?
Answer: The average debt ratio of corn farming enterprises in Canada, based on the data from 2018 to 2022, is 0.6.

Result 5
Question: Here is a question that can be fully answered from the given context:

"What province in Canada has the majority of new car dealerships and auto parts manufacturers?"

This question can be answered by looking at the tables and text in the context, which state that Ontario has the majority of new car dealerships and auto parts manufacturers, and that it is the province with the largest spread of businesses compared to its population.
Answer: Ontario has the majority of new car dealerships and auto parts manufacturers in Canada.

Result 6
Question: Here is a question that can be fully answered from the given context:

"What are the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation?
Answer: Successful businesses in the specialized trucking services industry compete with substitutes such as rail and air transportation by focusing on the following key factors:

1. **Develop Strong Technical Product Knowledge**: Having deep technical expertise ensures companies can effectively manage and troubleshoot their specialized equipment. This capability enhances reliability and service excellence, making their offerings more attractive compared to substitute transportation options.

2. **Establish Brand Names**: Building a recognizable and trusted brand fosters client confidence and loyalty. By establishing a strong brand presence, businesses can reduce the likelihood of customers switching to substitutes, reinforcing their position in the competitive trucking landscape.

These strategies help trucking companies maintain a competitive edge against substitutes by enhancing their value proposition and customer loyalty.

Result 7
Question: Here is a question that can be fully answered from the given context:

"What are the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation?
Answer: Successful businesses in the specialized trucking services industry use the following key factors to compete with substitutes such as rail and air transportation:

1. **Develop Strong Technical Product Knowledge**: Having deep technical expertise ensures companies can effectively manage and troubleshoot their specialized equipment. This capability enhances reliability and service excellence, making their offerings more attractive compared to substitute transportation options.

2. **Establish Brand Names**: Building a recognizable and trusted brand fosters client confidence and loyalty. By establishing a strong brand presence, businesses can reduce the likelihood of customers switching to substitutes, reinforcing their position in the competitive trucking landscape.

These factors help businesses maintain a competitive edge against other transportation modes by focusing on service quality, reliability, and strong customer relationships.

Result 8
Question: Here is a question that can be fully answered from the given context:

"What type of research does IBISWorld specialize in?
Answer: IBISWorld specializes in industry research with coverage on thousands of global industries.

Result 9
Question: Here is a question that can be fully answered from the given context:

"What are the expected long-term effects of rising truck prices and fuel costs on the Long-Distance Specialized Freight Trucking industry in Canada?
Answer: The expected long-term effects of rising truck prices and fuel costs on the Long-Distance Specialized Freight Trucking industry in Canada include:

1. Increased Upfront Costs: Companies will face larger upfront expenses due to climbing prices of reefers, dry vans, and oil tankers, as well as fuel and replacement parts which constitute a significant portion of expenses.

2. Higher Barriers to Entry: The rise in vehicle and fuel costs will present higher barriers to entry for new establishments, as initial investments become more substantial.

3. Passing Costs Downstream: Surcharges will allow truckers and businesses to pass rising fuel costs downstream to their clients, leveraging the specialized nature of operations to negotiate favorable rates.

4. Enhanced Efficiency: Integrating technology such as sensors, load monitors, and more fuel-efficient engines into trucks will drive up costs in the short term but will improve efficiency on the road.

5. Financial Relief from Stabilizing Fuel Prices: As energy markets stabilize and fuel prices decline, some financial relief is expected, which will support profit recovery and revenue expansion.

Overall, while rising truck prices and fuel costs pose challenges, companies are likely to adapt by passing costs downstream, optimizing efficiency, and benefiting from eventual stabilization in fuel prices.

Result 10
Question: Here is a question that can be fully answered from the given context:

"What are the key international markets that drive demand for Canadian corn exports?"

This question can be answered by referencing the context, which states that "Demand from key international markets drives corn exports" and specifically mentions Ireland, the US, and the United Kingdom as key markets.
Answer: The key international markets that drive demand for Canadian corn exports are Ireland, the US, and the United Kingdom.

Result 11
Question: Here is a question that can be fully answered from the given context:

"What are the expected trends in the Canadian long-distance specialized freight trucking industry, including the impact of technological advances and government policies?"

This question is fully answerable from the context, which discusses the industry's expected growth, the impact of technological advances, the effects of government policies such as the Express Entry initiative, and the industry's maturity and saturation levels.
Answer: The Canadian long-distance specialized freight trucking industry is expected to experience several key trends in the coming years:

1. **Growth and Economic Impact**: The industry is projected to recover and grow as the Canadian economy improves, with the real GDP growth expected to accelerate from 1.1% in 2024 to 1.6% in 2025. This recovery will drive demand for specialized transportation services, supported by a rebound in economic activity and manufacturing output.

2. **Technological Advances**: Technological innovations will continue to reshape the industry, with trucking companies investing in remote monitoring systems and technology to enhance resilience. The gradual rollout of autonomous trucks is expected to transform long-distance logistics, reducing limitations posed by Hours of Service (HOS) and Electronic Logging Devices (ELDs). Advanced trucks with Level 4 and 5 autonomy are being developed, which will significantly alter logistics operations in the industry.

3. **Government Policies**: The Express Entry initiative aims to alleviate the driver shortage by expediting immigration, allowing migrant workers to arrive in Canada within six months of applying. This is expected to help address high driver turnover and vacancies. Additionally, environmental oversight is likely to increase as the government prioritizes emissions control, encouraging the adoption of electric and hybrid trucks.

4. **Market Maturity and Saturation**: The industry is in its mature stage, with a significant contribution to GDP. It remains highly competitive with low barriers to entry, allowing new entrants to join the market. However, consolidation activity among larger carriers is expected to continue, driven by rising competition and customers' preference to outsource logistics operations.

5. **Sustainability and Environmental Concerns**: There is an increasing emphasis on sustainability, with fleet owners seeking to acquire environmentally friendly vehicles to eliminate fuel price uncertainty and meet the demand for sustainable supply chains.

Overall, the Canadian long-distance specialized freight trucking industry is poised for growth, driven by economic recovery, technological advancements, supportive government policies, and a focus on sustainability.

Result 12
Question: Here is a question that can be fully answered from the given context:

"What is the expected Compound Annual Growth Rate (CAGR) of revenue for local specialized freight trucking companies in Canada through the end of 2029?
Answer: The expected Compound Annual Growth Rate (CAGR) of revenue for local specialized freight trucking companies in Canada through the end of 2029 is 1.5%.

Result 13
Question: Here is a question that can be fully answered from the given context:

"According to the Electric Vehicle Availability Standard, what percentage of new cars, SUVs, crossovers, and light-duty pickup trucks sold in Canada must be 100% zero-emission by 2035?"

This question can be answered directly from the context, which states: "Canada unveiled the Electric Vehicle Availability Standard, requiring all new cars, SUVs, crossovers and light-duty pickup trucks sold in Canada to be 100% zero-emission by 2035.
Answer: According to the Electric Vehicle Availability Standard, 100% of new cars, SUVs, crossovers, and light-duty pickup trucks sold in Canada must be zero-emission by 2035.

Result 14
Question: Here is a question that can be fully answered from the given context:

"By what percentage did the number of enterprises in the Long-Distance Freight Trucking industry in Canada increase from 2006 to 2007?"

This question can be answered by looking at the "Enterprises" column in the table, where it shows a 17% increase from 2006 to 2007.
Answer: The number of enterprises in the Long-Distance Freight Trucking industry in Canada increased by 11.9% from 2006 to 2007.

Result 15
Question: Here is a question that can be fully answered from the given context:

"Keyphrase: 'Strong market profile'
question: "How does establishing a strong market presence affect buyer power in the long-distance freight trucking industry in Canada?
Answer: Establishing a strong market presence enhances brand recognition and customer loyalty, which reduces buyer power. This is because when a service becomes a preferred choice, it lessens the impact of competitive offers in the market. Therefore, in the long-distance freight trucking industry in Canada, a strong market profile diminishes buyer power by making the service more desirable and less susceptible to competition.

Result 16
Question: Here is a question that can be fully answered from the given context:

"Over the period from 2005 to 2030, what was the average annual percentage change in the number of establishments in the Long-Distance Freight Trucking industry in Canada?"

This question can be answered by analyzing the data in the "Industry Data Annual Change" section of the context, specifically the column labeled "%" under the "Establishments" heading.
Answer: To calculate the average annual percentage change in the number of establishments in the Long-Distance Freight Trucking industry in Canada from 2005 to 2030, we need to look at the annual changes provided in the context. Here are the provided annual percentage changes for establishments:

- 2006: 18.1%
- 2007: 5.7%
- 2008: 8.3%
- 2009: 1.0%
- 2010: 1.1%
- 2011: 2.1%
- 2012: 3.3%
- 2013: 20.3%
- 2014: 7.4%
- 2015: 7.7%
- 2016: 6.1%
- 2017: 5.1%
- 2018: 5.5%
- 2019: 5.3%
- 2020: 4.8%
- 2021: 4.8%
- 2022: 7.1%
- 2023: 3.9%
- 2024: 3.6%
- 2025: 3.8%
- 2026: 3.5%
- 2027: 3.5%
- 2028: 3.5%
- 2029: 3.4%
- 2030: 3.5%

Now, calculate the average of these changes. There are 25 values in total.

Average percentage change = (Sum of all percentage changes) / Number of years

Average percentage change = (18.1 + 5.7 + 8.3 + 1.0 + 1.1 + 2.1 + 3.3 + 20.3 + 7.4 + 7.7 + 6.1 + 5.1 + 5.5 + 5.3 + 4.8 + 4.8 + 7.1 + 3.9 + 3.6 + 3.8 + 3.5 + 3.5 + 3.5 + 3.4 + 3.5) / 25

Average percentage change = 5.22%

The average annual percentage change in the number of establishments in the Long-Distance Freight Trucking industry in Canada from 2005 to 2030 is approximately 5.22%.

Result 17
Question: Here is a question that can be fully answered from the given context:

"How do fuel costs and pricing power affect the profitability of long-distance specialized freight trucking companies in Canada?
Answer: Fuel costs have a significant impact on the profitability of long-distance specialized freight trucking companies in Canada. The fluctuations in fuel prices are more pronounced in long-distance operations compared to local and regional services due to the length of haul, which increases fuel consumption and operating costs. Trucking companies often mitigate rising fuel costs by imposing surcharges on their contract rates, passing a portion of the increased costs downstream to their clients, which helps boost their revenue.

Larger trucking companies are generally more successful in levying these fuel surcharges or mitigating prices through forward contracts, whereas smaller competitors may struggle to impose the same additional costs, potentially forcing them out of the industry. This dynamic has led to increased market dominance by larger companies. Despite this, lingering competition prevents truckers from fully passing on fuel costs and preserving profit, affecting overall profitability.

Result 18
Question: Here is a question that can be fully answered from the given context:

"What is the forecasted revenue growth rate for the Long-Distance Specialized Freight Trucking industry in Canada from 2019-2024?"

This question can be answered by looking at the table that shows the forecasted annual revenue and change percentage for the industry from 2012 to 2028. The answer can be found in the row that says "Revenue" and the column that says "â19-â24 î¥0.5 %", which indicates a revenue growth rate of 0.5% from 2019 to 2024.
Answer: The forecasted revenue growth rate for the Long-Distance Specialized Freight Trucking industry in Canada from 2019-2024 is 0.5%.

Result 19
Question: Here is a question that can be fully answered from the given context:

"What is the expected impact of the rebound in economic growth on the demand for freight transportation services in Canada?
Answer: The rebound in economic growth is expected to boost demand for freight transportation services in Canada. This increase in demand will be driven by rising consumer spending and construction investments. As economic conditions improve and consumer spending increases, there will be a heightened need for product transportation, which will prompt manufacturers to enhance production and freight companies to expand operations. Additionally, the expected pickup in growth and manufacturing output will drive distribution services across specialized freight transport, supporting expansion after a muted performance between 2019 and 2024.

Result 20
Question: Here is a question that can be fully answered from the given context:

"What is the effect of low barriers to entry on the long-distance freight trucking industry in Canada?
Answer: The effect of low barriers to entry on the long-distance freight trucking industry in Canada is that it keeps the market competitive. Minimal capital requirements allow individuals to easily start a business, fostering an expansion in nonemployer establishments. This has resulted in a large number of small businesses entering the market, leading to a low market share concentration. Over 60% of all establishments in the industry are nonemployers, and since 2018, more than 5,000 nonemployer establishments have been added. The presence of freight brokerages and agencies facilitating contracts with clients also supports entry by nonemployers, maintaining low market concentration. However, it also means that the market is saturated, with fierce competition among a large number of small players.

Result 21
Question: Here is a question that can be fully answered from the given context using the keyphrase "Barriers to Entry":

"What challenges do potential industry entrants face when entering the local specialized freight trucking industry in Canada?"

This question is fully answerable from the context, as it is directly addressed in the section "What challenges do potential industry entrants face?" under the subheading "Barriers to Entry".
Answer: Potential industry entrants face several challenges when entering the local specialized freight trucking industry in Canada:

1. **Legal Regulations**: The industry is heavily regulated, especially for transporting hazardous materials like petroleum, oil, and chemicals. There are also laws governing road safety, hours of service, and weight regulations that must be adhered to.

2. **Start-up Costs**: The type of specialization dictates the start-up costs. Companies targeting specific niches must purchase trucks compatible with the required distribution service, which can significantly increase the upfront capital investment.

3. **Differentiation**: Companies must differentiate themselves by specializing in niche distribution services. The type of distribution dictates the type of truck required, and businesses can optimize operations with route software or offer volume discounts.

4. **Labour Expenses**: Truck drivers work long hours and may spend days away from home, leading to high salaries as compensation. New companies need steady revenue to retain enough employees to comply with hours of service laws.

Result 22
Question: Here is a question that can be fully answered from the given context:

"Key Success Factors for Local Specialized Freight Trucking companies include developing a strong reputation, generating repeat customers, and providing superior after-sales service. What is the primary way in which successful Local Specialized Freight Trucking businesses handle concentration in the market?"

This question requires the reader to understand the key success factors mentioned in the context and how they relate to the topic of Local Specialized Freight Trucking.
Answer: The primary way in which successful Local Specialized Freight Trucking businesses handle concentration in the market is by developing a strong reputation. Maintaining a team of highly skilled drivers and staff ensures reliable, high-quality service, which helps local specialized freight truckers stand out and secure business.

Result 23
Question: Here is a question that can be fully answered from the given context:

"Despite the importance of livestock transportation, what has increased the complexity and documentation requirements for this service in Canada?"

This question can be answered by referencing the following sentence in the context:

"The lack of viable alternatives causes livestock companies to depend on trucking for animal transportation. Nonetheless, stringent animal welfare regulations in Canada have increased the complexity and documentation requirements for livestock transport.
Answer: Stringent animal welfare regulations in Canada have increased the complexity and documentation requirements for livestock transportation.

Result 24
Question: Here is a question that can be fully answered from the given context:

"Are regulatory barriers at both the provincial and federal levels governing the testing of autonomous vehicles in Canada?"

This question is formed using the topic "Regulatory barriers in Canada" and can be answered directly from the context, which states: "Regulatory barriers at both the provincial and federal levels govern the testing of autonomous vehicles in Canada...
Answer: Yes, regulatory barriers at both the provincial and federal levels govern the testing of autonomous vehicles in Canada.

Result 25
Question: Here is a rewritten version of the question:

"What operational strategy enables Canadian Local Specialized Freight Trucking firms to thrive during market fluctuations?"

I've kept the core meaning of the original question, but made it more concise and indirect by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "operational strategy" instead of "operational strategy helps")
* Focusing on the key outcome (thriving during market fluctuations) rather than the specific practices that lead to it.
Answer: The operational strategy that enables Canadian Local Specialized Freight Trucking firms to thrive during market fluctuations includes maintaining efficient work practices and using new technology to contain costs and boost productivity. Streamlining operations and integrating the latest technology enhance resilience and adaptability, ensuring consistent service delivery and client retention.

Result 26
Question: Here is the rewritten question:

"What GM crops are on the market, excluding wheat?"

This question conveys the same meaning as the original, but in a more indirect and concise manner. It requires the reader to make the same logical connections and inferences as the original question, but in a more subtle way.
Answer: Genetically modified (GM) crops on the market include corn and soybeans. These GM seeds offer enhanced resistance to pests and diseases, increased yield potential, and better tolerance to adverse weather conditions.

Result 27
Question: Here is a rewritten version of the question:

"When did Canada's Auto Parts Mfg. industry see a big revenue boost?"

I've used abbreviations (e.g. "Mfg." for "Manufacturing") and shortened the question to make it more concise while still conveying the same meaning.
Answer: The Canadian Auto Parts Manufacturing industry saw a revenue boost during the period from 2019 to 2024, with revenue climbing at an expected CAGR of 1.2% to $7.9 billion, including a 1.9% jump in 2024.

Result 28
Question: Here is the rewritten question:

"What kind of freight do Canadian local trucking companies haul for ag products?"

I shortened the question by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "ag" for "agricultural")
* Simplifying the sentence structure
* Focusing on the main idea of the question
Answer: Canadian local trucking companies haul agricultural products such as primary goods to central storage and distribution depots or transport products to coastal export facilities. This includes perishable goods like fruits and vegetables, which often require insulated vehicles, and bulk dry goods like corn and grains, which are loaded into pneumatic trailers.

Result 29
Question: How much of Canada's wheat demand comes from imports?
Answer: Less than 2.0% of Canada's domestic wheat demand is typically accounted for by imports.

Result 30
Question: Here is a rewritten version of the question:

"What advantage do buyers gain when comparing freight trucking companies in Canada?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "freight trucking" instead of "long-distance freight trucking")
* Focusing on the key benefit for buyers, rather than the process of comparison.
Answer: Buyers gain the advantage of numerous choices, allowing them to leverage competitive pricing and delivery efficiency among freight trucking companies in Canada. This enables them to select services that best meet their cost and time requirements.

Result 31
Question: Here is a rewritten version of the question:

"What crop helps farmers manage market risks?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "crop" instead of "type of crop")
* Focusing on the key aspect of the question (managing market risks) rather than the specific benefit (diversifying output and combating revenue volatility)
Answer: The crop that helps farmers manage market risks is wheat, as it is considered essential by legislators and provides opportunities for diversification with other crops, which aids in managing market volatility.

Result 32
Question: Here is the rewritten question:

"What could undermine the benefits of the company's expansion?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "the company's" becomes "the company")
* Changing the wording to make it more concise and natural-sounding.
Answer: I don't have specific information about a company's expansion and what might undermine its benefits without additional context. If you provide more details about the company or industry, I might be able to offer more insight.

Result 33
Question: Here is a rewritten version of the question:

"What's the net change in Auto Parts Manufacturing businesses in Canada from 2024 to 2029?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Using a shorter phrase ("net change" instead of "expected annual change")
* Removing unnecessary words and phrases
* Using an abbreviation ("Auto Parts Manufacturing" instead of "the Auto Parts Manufacturing industry")
* Focusing on the main idea of the question ("change in businesses") rather than the specific details.
Answer: The net change in Auto Parts Manufacturing businesses in Canada from 2024 to 2029 is expected to be a decrease of 0.9%.

Result 34
Question: Here is the rewritten question:

"What share of 2024 industry revenue is domestic?
Answer: I don't know. The provided context does not specify the share of 2024 industry revenue that is domestic.

Result 35
Question: Here's a rewritten version of the question:

"What owns the rights to a Canadian car dealers report?"

I've used abbreviations like "owns" instead of "retains" and "rights" to make the question shorter and more concise. I've also removed unnecessary words to make it more direct and to the point.
Answer: The rights to the Canadian car dealers report are owned by IBISWorld.

Result 36
Question: Here's a rewritten version of the question:

"What drives Canadian auto parts revenue growth, and how do they stay competitive with tech changes?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Using a more general term "drives" instead of "economic conditions"
* Shortening "auto parts manufacturers" to "auto parts"
* Using an abbreviation "tech" for "technological"
* Removing unnecessary words and phrases to make the question more concise.
Answer: Canadian auto parts revenue growth is primarily driven by stable economic conditions, increased new vehicle sales, and the aging vehicle fleet, which supports aftermarket demand for repairs. To stay competitive with technological changes, manufacturers invest in research and development, adopt efficient manufacturing technologies, and innovate products like HVAC systems and airbags to meet evolving safety and sustainability standards. They also focus on higher-margin specialty products and streamline production through automation and integration of new technologies.

Result 37
Question: Here's a rewritten version of the question:

"What triggers industry growth in Canada when a key competitor lowers prices?"

I've used abbreviations like "key" instead of "major" and "triggers" instead of "drives" to make the question shorter and more indirect.
Answer: In Canada, when a key competitor lowers prices, industry growth can be triggered by several factors:

1. **Consumer Demand**: Lower prices can increase consumer demand as more people can afford the products, leading to higher sales volumes for the industry.

2. **Competitive Response**: Other companies in the industry may also lower their prices or offer promotions to retain market share, potentially increasing overall industry sales.

3. **Market Expansion**: The reduction in prices can make products accessible to a wider audience, expanding the market size and contributing to industry growth.

4. **Innovation and Efficiency**: To maintain profitability at lower prices, companies might invest in innovation or improve operational efficiencies, which can enhance industry growth.

5. **Increased Brand Loyalty**: Offering lower prices can also increase customer loyalty and attract new customers, contributing to long-term industry growth.

Overall, a key competitor lowering prices can stimulate industry growth by increasing demand, expanding the market, and encouraging competitive strategies.

Result 38
Question: Here's a rewritten version of the question:

"What kinds of freight do Canadian long-haul carriers move?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "long-haul" instead of "operating both locally and over long distances")
* Focusing on the key aspect of the question (the types of freight transported)
Answer: Canadian long-haul carriers typically move a wide range of freight, including consumer goods, raw materials, industrial products, and specialized freight for various industries such as manufacturing, retail, and construction. The specific types of freight can vary depending on the carrier's specialization and customer needs.

Result 39
Question: Here is the rewritten question:

"What year between 2024-2029 will wheat farming revenue in Canada peak before declining?
Answer: Based on the provided context, there is no specific year mentioned between 2024 and 2029 during which wheat farming revenue in Canada is expected to peak before declining. The context only provides a general outlook, stating that revenue is expected to climb at a CAGR of 0.8% to $16.8 billion through the end of 2029.

Result 40
Question: Here's a rewritten version of the question:

"What Canadian industries are easiest for specialized trucking companies to operate in?"

I've kept the core meaning of the original question, but made it more concise and indirect by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "operating in" instead of "profit recovery efforts face the least resistance due to favorable market conditions and structural advantages")
* Changing the wording to make it more conversational and less formal.
Answer: The easiest Canadian industries for specialized trucking companies to operate in are those with high demand for niche distribution services, like oil and gas extraction, mining, and construction. These industries often require specialized equipment and knowledge, which can reduce competition and provide opportunities for companies that can meet their specific needs.

Result 41
Question: Here's a rewritten version of the question:

"What quartile has the strongest link between asset leverage and ROA?"

This version conveys the same meaning as the original question but in a more indirect and concise way, using abbreviations like "ROA" (Return on Assets) and "asset leverage" to refer to the ratio of total assets to equity.
Answer: Based on the context provided, the quartile with the strongest link between asset leverage and Return on Assets (ROA) is the top quartile. This is because the top quartile typically exhibits higher efficiency in utilizing assets to generate returns, as reflected in higher ROA values, which often correlates with effective asset leverage management.

Result 42
Question: Here's a rewritten version of the question:

"What market conditions favor stable market share concentration for family-owned farms in Canada's corn industry?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "market conditions" instead of "market conditions do")
* Focusing on the key aspect of the question (stable market share concentration)
Answer: Stable market share concentration for family-owned farms in Canada's corn industry is favored by several market conditions:

1. **Decentralized Structure**: The industry is predominantly composed of small, family-owned farms, which inherently limits the ability of any single entity to dominate, thus maintaining a stable market share concentration.

2. **Geographical Diversity**: Canada's varied geography creates different regions suitable for corn farming, dispersing production and preventing centralization by a few large players.

3. **Climate Variations**: Different provinces have specific agricultural niches due to climate variations, encouraging a balanced distribution of corn production across the country.

These factors collectively support a stable market share concentration by preventing significant consolidation and maintaining a competitive environment where small and family-owned farms can thrive.

Result 43
Question: Here is the rewritten question:

"What holds back live animal transport growth?
Answer: The growth of live animal transport is held back by growing regulatory oversight over the conditions of livestock transport. Regulations prohibit transporting livestock for more than 36 hours without food, water, or rest, and compromised cattle can only be transported for a maximum of 12 hours. These regulations and the oversight create barriers for truckers entering the market, leading to stagnation in growth within the segment.

CPU times: user 2.18 s, sys: 125 ms, total: 2.31 s
Wall time: 3min 41s

In [36]:
%%time
#Use LLama
dataset = testset.to_dataset()
answers = np.empty(len(dataset), dtype=object)

for index, row in enumerate(dataset):
    query = row["question"]
    
    # Run the query through the RAG pipeline
    rag_pipeline = RetrievalQA.from_llm(
        llm=llm,
        retriever=retriever
    )
    answer = rag_pipeline.invoke(input=query)
    answer = answer["result"]
    print(f"Result {index}\nQuestion: {query}\nAnswer: {answer}\n")
    
    # Store the result
    answers[index] = answer

Result 0
Question: Here is a question that can be fully answered from the given context:

"What drives the demand for dry bulk transportation in the local specialized freight trucking industry in Canada?"

This question can be answered by referencing the context, which states that "Dry bulk transportation swells alongside construction activity" and that "Strong construction activity has supported this segment but is expected to trend downward through the end of 2024 as tightened monetary policy pressures businesses' financing ability.
Answer: According to the context, the demand for dry bulk transportation in the local specialized freight trucking industry in Canada is driven by construction activity. Specifically, it is stated that "Dry bulk transport is the largest market for specialized trucks" and that "A strong expansion in mining and high demand from the construction sector fueled market growth."

Result 1
Question: Here is a question that can be fully answered from the given context:

"What are the expected outcomes of the government's pro-immigration policies on the driver shortage and turnover in the long-distance specialized freight trucking industry in Canada?
Answer: The expected outcomes of the government's pro-immigration policies on the driver shortage and turnover in the long-distance specialized freight trucking industry in Canada are to alleviate pressure from high driver turnover. The policies, such as the Express Entry initiative, aim to quickly bring in new truckers to replace retiring employees and those not keen on the trucker lifestyle, thereby addressing the ongoing issues with worker retention and incentivizing more skilled drivers to stay in the industry.

Result 2
Question: Here is a question that can be fully answered from the given context:

"What is the expected impact of the rebound in economic growth on the demand for freight transportation services in Canada?
Answer: The expected impact of the rebound in economic growth on the demand for freight transportation services in Canada is that it will boost demand for freight transportation services, driven by increased consumer spending and construction investments.

Result 3
Question: Here is a question that can be fully answered from the given context using the topic "E-commerce growth":

question: "What is driving the growth of e-commerce in the long-distance freight trucking industry in Canada?
Answer: The growth of e-commerce is driving the expansion of the Less-than-truckload (LTL) segment in the long-distance freight trucking industry in Canada. This is because smaller establishments are benefiting from cheaper shipments, and trucking companies are expanding their value-added services to secure their place in global supply chains and grow revenue.

Result 4
Question: Here is a question that can be fully answered from the given context:

"What is the average debt ratio of corn farming enterprises in Canada, based on the data from 2018 to 2022?
Answer: To calculate the average debt ratio, we need to add up the debt ratios for each year from 2018 to 2022 and divide by the number of years.

Debt ratio for 2018: 0.6
Debt ratio for 2019: 0.6
Debt ratio for 2020: 0.6
Debt ratio for 2021: 0.6
Debt ratio for 2022: 0.5

Average debt ratio = (0.6 + 0.6 + 0.6 + 0.6 + 0.5) / 5
Average debt ratio = 3.3 / 5
Average debt ratio = 0.66

So, the average debt ratio of corn farming enterprises in Canada, based on the data from 2018 to 2022, is 0.66 or 66%.

Result 5
Question: Here is a question that can be fully answered from the given context:

"What province in Canada has the majority of new car dealerships and auto parts manufacturers?"

This question can be answered by looking at the tables and text in the context, which state that Ontario has the majority of new car dealerships and auto parts manufacturers, and that it is the province with the largest spread of businesses compared to its population.
Answer: The province in Canada with the majority of new car dealerships and auto parts manufacturers is Ontario.

Result 6
Question: Here is a question that can be fully answered from the given context:

"What are the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation?
Answer: According to the context, the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation are:

1. Develop strong technical product knowledge: Having deep technical expertise ensures companies can effectively manage and troubleshoot their specialized equipment, enhancing reliability and service excellence.
2. Establish brand names: Building a recognizable and trusted brand fosters client confidence and loyalty, reducing the likelihood of customers switching to substitutes.

These factors help businesses in the specialized trucking services industry to differentiate themselves and offer more attractive services compared to substitutes like rail transportation and air transportation.

Result 7
Question: Here is a question that can be fully answered from the given context:

"What are the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation?
Answer: According to the context, the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation are:

1. Develop strong technical product knowledge: Having deep technical expertise ensures companies can effectively manage and troubleshoot their specialized equipment, enhancing reliability and service excellence.
2. Establish brand names: Building a recognizable and trusted brand fosters client confidence and loyalty, reducing the likelihood of customers switching to substitutes.

These factors help businesses in the specialized trucking services industry to differentiate themselves and offer more attractive services compared to substitutes like rail transportation and air transportation.

Result 8
Question: Here is a question that can be fully answered from the given context:

"What type of research does IBISWorld specialize in?
Answer: IBISWorld specializes in industry research with coverage on thousands of global industries.

Result 9
Question: Here is a question that can be fully answered from the given context:

"What are the expected long-term effects of rising truck prices and fuel costs on the Long-Distance Specialized Freight Trucking industry in Canada?
Answer: According to the context, the expected long-term effects of rising truck prices and fuel costs on the Long-Distance Specialized Freight Trucking industry in Canada are:

* A decline in insurance and maintenance costs relative to revenue expansion, supporting a profit recovery.
* A slowing consumer-price index and a rebounding economic activity energized by monetary easing will support freight volumes and transport of petroleum and reefer contracts, spurring revenue expansion and allowing profit to recover as conditions stabilize.
* A rise in purchases is expected to persist in line with climbing prices of new vehicles, but the expected decline in fuel prices as the energy markets stabilize will provide relief.
* Improved route optimization and focus on the most profitable routes are expected to persist, limiting the need for drivers and allowing businesses to generate more revenue without dramatically expanding fleet sizes.

Result 10
Question: Here is a question that can be fully answered from the given context:

"What are the key international markets that drive demand for Canadian corn exports?"

This question can be answered by referencing the context, which states that "Demand from key international markets drives corn exports" and specifically mentions Ireland, the US, and the United Kingdom as key markets.
Answer: According to the context, the key international markets that drive demand for Canadian corn exports are:

* Ireland
* The US
* The United Kingdom

These markets account for a significant portion of Canadian corn exports, underscoring their importance for sustaining export growth.

Result 11
Question: Here is a question that can be fully answered from the given context:

"What are the expected trends in the Canadian long-distance specialized freight trucking industry, including the impact of technological advances and government policies?"

This question is fully answerable from the context, which discusses the industry's expected growth, the impact of technological advances, the effects of government policies such as the Express Entry initiative, and the industry's maturity and saturation levels.
Answer: Based on the provided context, here are the expected trends in the Canadian long-distance specialized freight trucking industry:

1. **Growth**: The industry is expected to grow, driven by the acceleration in the GDP growth from 1.1% in 2024 to 1.6% in 2025, and the expected CAGR of 1.9% in consumer spending through 2029. This growth will be fueled by the recovery in economic activity, manufacturing output, and consumer spending.
2. **Technological advances**: Technological advances will continue to reshape the industry, with trucking companies investing in remote monitoring systems and technology to strengthen the industry's resilience. The gradual rollout of autonomous trucks will transform long-distance logistics, allowing for more efficient transportation and reducing the limitations presented by the Hours of Service (HOS) and Electronic Logging Devices (ELDs).
3. **Government policies**: The Canadian government's policies, such as the Express Entry initiative, will alleviate pressure from high driver turnover by attracting migrant workers to the industry. The government's economic policies will also favor freight transportation services, supporting demand for freight trucking and the safety of drivers.
4. **Consolidation**: The industry is expected to experience further consolidation, driven by rising competition and customers

Result 12
Question: Here is a question that can be fully answered from the given context:

"What is the expected Compound Annual Growth Rate (CAGR) of revenue for local specialized freight trucking companies in Canada through the end of 2029?
Answer: According to the context, the expected Compound Annual Growth Rate (CAGR) of revenue for local specialized freight trucking companies in Canada through the end of 2029 is 1.5%.

Result 13
Question: Here is a question that can be fully answered from the given context:

"According to the Electric Vehicle Availability Standard, what percentage of new cars, SUVs, crossovers, and light-duty pickup trucks sold in Canada must be 100% zero-emission by 2035?"

This question can be answered directly from the context, which states: "Canada unveiled the Electric Vehicle Availability Standard, requiring all new cars, SUVs, crossovers and light-duty pickup trucks sold in Canada to be 100% zero-emission by 2035.
Answer: According to the Electric Vehicle Availability Standard, 100% of new cars, SUVs, crossovers, and light-duty pickup trucks sold in Canada must be 100% zero-emission by 2035.

Result 14
Question: Here is a question that can be fully answered from the given context:

"By what percentage did the number of enterprises in the Long-Distance Freight Trucking industry in Canada increase from 2006 to 2007?"

This question can be answered by looking at the "Enterprises" column in the table, where it shows a 17% increase from 2006 to 2007.
Answer: According to the context, the number of enterprises in the Long-Distance Freight Trucking industry in Canada increased by 11.9% from 2006 to 2007, not 17%. This can be seen in the "Enterprises" column of the table, where the number of enterprises in 2006 is 21,949 and in 2007 is 24,570.

Result 15
Question: Here is a question that can be fully answered from the given context:

"Keyphrase: 'Strong market profile'
question: "How does establishing a strong market presence affect buyer power in the long-distance freight trucking industry in Canada?
Answer: According to the context, establishing a strong market presence enhances brand recognition and customer loyalty, which reduces buyer power by making the service a preferred choice, lessening the impact of competitive offers in the market.

Result 16
Question: Here is a question that can be fully answered from the given context:

"Over the period from 2005 to 2030, what was the average annual percentage change in the number of establishments in the Long-Distance Freight Trucking industry in Canada?"

This question can be answered by analyzing the data in the "Industry Data Annual Change" section of the context, specifically the column labeled "%" under the "Establishments" heading.
Answer: To calculate the average annual percentage change in the number of establishments, we need to calculate the average of the annual percentage changes from 2005 to 2030.

The annual percentage changes in the number of establishments are:

2006: 18.1%
2007: 5.7%
2008: 8.3%
2009: 1.0%
2010: 1.1%
2011: 2.1%
2012: 3.3%
2013: 20.3%
2014: 7.4%
2015: 7.7%
2016: 6.1%
2017: 5.1%
2018: 5.5%
2019: 5.3%
2020: 4.8%
2021: 4.8%
2022: 7.1%
2023: 3.9%
2024: 3.6%
2025: 3.8%
2026: 3.5%
2027: 3.2%
2028: 3.2%
2029: 1.4%
2030: 1.2%

To calculate the average, we add up all the annual percentage

Result 17
Question: Here is a question that can be fully answered from the given context:

"How do fuel costs and pricing power affect the profitability of long-distance specialized freight trucking companies in Canada?
Answer: Fuel costs have a significant impact on the profitability of long-distance specialized freight trucking companies in Canada. Rising fuel costs can increase operating expenses, which can reduce profit margins. However, trucking companies can mitigate the impact of fuel costs by imposing fuel surcharges on their contracts, which can help to boost revenue. The ability of trucking companies to pass on fuel costs to their clients through surcharges is influenced by their pricing power, which is affected by factors such as the level of competition in the market and the company's market share.

In the context of the Canadian long-distance specialized freight trucking industry, fuel costs have been a major concern, particularly in recent years due to the surge in fuel prices. However, larger local specialized freight trucking companies have been able to successfully impose fuel surcharges or mitigate prices with forward contracts, which has helped to maintain their profit margins. In contrast, smaller competitors have struggled to impose the same additional costs, which has exacerbated the dominance of larger companies and lifted concentration in the industry.

Overall, the profitability of long-distance specialized freight trucking companies in Canada is influenced by their ability to manage fuel costs and pricing power, which is critical to maintaining profit margins in a highly competitive market.

Result 18
Question: Here is a question that can be fully answered from the given context:

"What is the forecasted revenue growth rate for the Long-Distance Specialized Freight Trucking industry in Canada from 2019-2024?"

This question can be answered by looking at the table that shows the forecasted annual revenue and change percentage for the industry from 2012 to 2028. The answer can be found in the row that says "Revenue" and the column that says "â19-â24 î¥0.5 %", which indicates a revenue growth rate of 0.5% from 2019 to 2024.
Answer: The forecasted revenue growth rate for the Long-Distance Specialized Freight Trucking industry in Canada from 2019-2024 is 0.5%.

Result 19
Question: Here is a question that can be fully answered from the given context:

"What is the expected impact of the rebound in economic growth on the demand for freight transportation services in Canada?
Answer: The expected impact of the rebound in economic growth on the demand for freight transportation services in Canada is that it will boost demand for freight transportation services, driven by increased consumer spending and construction investments.

Result 20
Question: Here is a question that can be fully answered from the given context:

"What is the effect of low barriers to entry on the long-distance freight trucking industry in Canada?
Answer: Low barriers to entry in the long-distance freight trucking industry in Canada have kept the market competitive. This is because individuals can easily start a business with minimal capital requirements, such as a commercial driver's license, a few basic tools, and a truck. As a result, the industry has seen an expansion in nonemployer establishments, with over 60.0% of all establishments being nonemployers. Additionally, the presence of freight brokerages and agencies facilitating contracts with clients has supported the entry of nonemployers, keeping the concentration low.

Result 21
Question: Here is a question that can be fully answered from the given context using the keyphrase "Barriers to Entry":

"What challenges do potential industry entrants face when entering the local specialized freight trucking industry in Canada?"

This question is fully answerable from the context, as it is directly addressed in the section "What challenges do potential industry entrants face?" under the subheading "Barriers to Entry".
Answer: According to the context, potential industry entrants face the following challenges when entering the local specialized freight trucking industry in Canada:

* Legal: The regulatory landscape is more demanding than for transporting regular freight, with regulations governing road safety, hours of service, weight, and the distribution of hazardous materials.
* Start-up Costs: Specialization type dictates the start-up costs incurred, with businesses targeting a specific niche requiring a truck compatible with the distribution service required. Diversifying operations can greatly expand the up-front capital investment.
* Differentiation: Companies differentiate by specializing in niche distribution services, which requires the right type of truck, such as flatbed, dry-bulk trailer, reefer, pneumatic trailer, and others.
* Labour Expenses: Truck drivers work long hours and sometimes spend days at a time away from home, so salaries are high to compensate, and new tank and refrigeration trucking companies need steady revenue to retain enough employees to comply with hours of service laws.

Result 22
Question: Here is a question that can be fully answered from the given context:

"Key Success Factors for Local Specialized Freight Trucking companies include developing a strong reputation, generating repeat customers, and providing superior after-sales service. What is the primary way in which successful Local Specialized Freight Trucking businesses handle concentration in the market?"

This question requires the reader to understand the key success factors mentioned in the context and how they relate to the topic of Local Specialized Freight Trucking.
Answer: According to the context, the primary way in which successful Local Specialized Freight Trucking businesses handle concentration in the market is by "Maintain[ing] efficient work practices". This is mentioned in the section "How do successful businesses handle concentration?" under the context of Local Specialized Freight Trucking in Canada.

Result 23
Question: Here is a question that can be fully answered from the given context:

"Despite the importance of livestock transportation, what has increased the complexity and documentation requirements for this service in Canada?"

This question can be answered by referencing the following sentence in the context:

"The lack of viable alternatives causes livestock companies to depend on trucking for animal transportation. Nonetheless, stringent animal welfare regulations in Canada have increased the complexity and documentation requirements for livestock transport.
Answer: Stringent animal welfare regulations in Canada have increased the complexity and documentation requirements for livestock transport.

Result 24
Question: Here is a question that can be fully answered from the given context:

"Are regulatory barriers at both the provincial and federal levels governing the testing of autonomous vehicles in Canada?"

This question is formed using the topic "Regulatory barriers in Canada" and can be answered directly from the context, which states: "Regulatory barriers at both the provincial and federal levels govern the testing of autonomous vehicles in Canada...
Answer: Yes, regulatory barriers at both the provincial and federal levels govern the testing of autonomous vehicles in Canada.

Result 25
Question: Here is a rewritten version of the question:

"What operational strategy enables Canadian Local Specialized Freight Trucking firms to thrive during market fluctuations?"

I've kept the core meaning of the original question, but made it more concise and indirect by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "operational strategy" instead of "operational strategy helps")
* Focusing on the key outcome (thriving during market fluctuations) rather than the specific practices that lead to it.
Answer: Based on the provided context, the operational strategy that enables Canadian Local Specialized Freight Trucking firms to thrive during market fluctuations is:

Maintain efficient work practices and use new technology to contain costs and boost productivity.

This strategy is mentioned in the context as a key success factor for the industry, allowing firms to reduce costs, improve resilience, and adapt to changing market conditions.

Result 26
Question: Here is the rewritten question:

"What GM crops are on the market, excluding wheat?"

This question conveys the same meaning as the original, but in a more indirect and concise manner. It requires the reader to make the same logical connections and inferences as the original question, but in a more subtle way.
Answer: Based on the provided context, the answer to the rewritten question is:

"Genetically modified (GM) corn seeds."

This is because the context mentions that genetically modified corn seeds offer enhanced resistance to pests and diseases, safeguarding crops, and provide increased yield potential, essential for meeting rising demand across animal feed, human consumption, and industrial uses.

Result 27
Question: Here is a rewritten version of the question:

"When did Canada's Auto Parts Mfg. industry see a big revenue boost?"

I've used abbreviations (e.g. "Mfg." for "Manufacturing") and shortened the question to make it more concise while still conveying the same meaning.
Answer: According to the provided context, Canada's Auto Parts Mfg. industry saw a big revenue boost in 2024, with a 1.9% jump in revenue and a profit margin of 8.7%.

Result 28
Question: Here is the rewritten question:

"What kind of freight do Canadian local trucking companies haul for ag products?"

I shortened the question by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "ag" for "agricultural")
* Simplifying the sentence structure
* Focusing on the main idea of the question
Answer: According to the context, Canadian local trucking companies haul various types of freight for ag products, including:

* Perishable goods such as fruits and vegetables, which require insulated vehicles
* Bulk dry goods such as corn and grains, which are loaded into pneumatic trailers
* Oversized objects such as rigs, pipes, and drilling equipment, which are transported using flatbed trailers

These types of freight are often transported to remote locations without rail access, making specialized truck services necessary.

Result 29
Question: How much of Canada's wheat demand comes from imports?
Answer: According to the provided context, imports account for a minimal share of domestic demand, typically less than 2.0% of domestic demand in a given year.

Result 30
Question: Here is a rewritten version of the question:

"What advantage do buyers gain when comparing freight trucking companies in Canada?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "freight trucking" instead of "long-distance freight trucking")
* Focusing on the key benefit for buyers, rather than the process of comparison.
Answer: According to the context, buyers gain the advantage of being able to "reject a trucker's services if their prices are too high or their delivery times aren't fast enough" due to the presence of many choices between trucking companies.

Result 31
Question: Here is a rewritten version of the question:

"What crop helps farmers manage market risks?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "crop" instead of "type of crop")
* Focusing on the key aspect of the question (managing market risks) rather than the specific benefit (diversifying output and combating revenue volatility)
Answer: Based on the provided context, the answer to the rewritten question is:

Corn

According to the context, growing premium, disease-resistant corn varieties reduces the impact of disease outbreaks and adverse weather, stabilizing yields and lessening volatility. This approach helps mitigate market fluctuations and allows farmers to manage market risks.

Result 32
Question: Here is the rewritten question:

"What could undermine the benefits of the company's expansion?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "the company's" becomes "the company")
* Changing the wording to make it more concise and natural-sounding.
Answer: Based on the provided context, I don't have enough information to determine what could undermine the benefits of the company's expansion. The context only provides information about various industries in Canada, including Wheat Farming, New Car Dealers, Auto Parts Manufacturing, and Long-Distance Specialized Freight Trucking. It does not mention a specific company or its expansion plans.

Result 33
Question: Here is a rewritten version of the question:

"What's the net change in Auto Parts Manufacturing businesses in Canada from 2024 to 2029?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Using a shorter phrase ("net change" instead of "expected annual change")
* Removing unnecessary words and phrases
* Using an abbreviation ("Auto Parts Manufacturing" instead of "the Auto Parts Manufacturing industry")
* Focusing on the main idea of the question ("change in businesses") rather than the specific details.
Answer: According to the provided context, the forecasted annual change in the number of businesses in the Auto Parts Manufacturing industry in Canada from 2024 to 2029 is 0.9%.

Result 34
Question: Here is the rewritten question:

"What share of 2024 industry revenue is domestic?
Answer: I don't know. The provided context does not include information about the share of 2024 industry revenue that is domestic.

Result 35
Question: Here's a rewritten version of the question:

"What owns the rights to a Canadian car dealers report?"

I've used abbreviations like "owns" instead of "retains" and "rights" to make the question shorter and more concise. I've also removed unnecessary words to make it more direct and to the point.
Answer: According to the context, the answer is:

IBISWorld

It is stated in the disclaimer section of the report that "Copyright to this publication is owned by IBISWorld."

Result 36
Question: Here's a rewritten version of the question:

"What drives Canadian auto parts revenue growth, and how do they stay competitive with tech changes?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Using a more general term "drives" instead of "economic conditions"
* Shortening "auto parts manufacturers" to "auto parts"
* Using an abbreviation "tech" for "technological"
* Removing unnecessary words and phrases to make the question more concise.
Answer: Based on the provided context, here's an answer to the rewritten question:

Canadian auto parts revenue growth is driven by several factors, including:

1. Aging vehicle fleets: The average vehicle age in Canada is 11 years, leading to increased demand for replacement parts and repairs, which supports aftermarket sales.
2. New and used car prices: Rising prices for new and used cars encourage consumers to repair rather than replace, driving demand for auto parts.
3. Do-it-yourself (DIY) car repair trend: The popularity of DIY car repair supports demand for auto parts from consumers.
4. Electric and autonomous vehicles: The growth of electric and autonomous vehicles creates new niche markets for auto parts manufacturers.

To stay competitive with technological changes, Canadian auto parts manufacturers focus on:

1. Innovation: They invest in research and development to improve products and secure supply contracts.
2. Product innovation: They develop new products, such as advanced air conditioning and HVAC systems, to meet changing consumer needs.
3. Operational efficiency: They use the most efficient manufacturing technologies and techniques to streamline production and create greater value than competitors.
4. After-sales services: They offer design support and after-sales services to make their products more appealing to automakers and consumers.
5. Differentiation: They focus on higher

Result 37
Question: Here's a rewritten version of the question:

"What triggers industry growth in Canada when a key competitor lowers prices?"

I've used abbreviations like "key" instead of "major" and "triggers" instead of "drives" to make the question shorter and more indirect.
Answer: Based on the provided context, it appears that industry growth in Canada is influenced by various factors, but there is no specific information on what triggers industry growth when a key competitor lowers prices.

However, I can provide some general insights from the context. In the context of New Car Dealers in Canada, it is mentioned that consumers are taking longer to purchase a new car, spending a significant amount of time comparing prices. Dealerships that provide low prices will increase traffic and volume sales. This suggests that price competition can be a factor in driving industry growth.

In the context of Auto Parts Manufacturing in Canada, it is mentioned that companies will need to slash prices to remain competitive as input prices ease through the outlook period. This implies that price competition can be a factor in driving industry growth, but it is not a direct trigger.

In the context of Wheat Farming in Canada, there is no mention of price competition as a factor in driving industry growth.

Therefore, I would say that I don't know the specific answer to the question, but price competition may be a factor in driving industry growth in certain contexts.

Result 38
Question: Here's a rewritten version of the question:

"What kinds of freight do Canadian long-haul carriers move?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "long-haul" instead of "operating both locally and over long distances")
* Focusing on the key aspect of the question (the types of freight transported)
Answer: Unfortunately, I don't see any information in the provided context that directly answers the question "What kinds of freight do Canadian long-haul carriers move?" The context provides information on the industry, market trends, and key success factors, but it doesn't specifically mention the types of freight transported by Canadian long-haul carriers.

Result 39
Question: Here is the rewritten question:

"What year between 2024-2029 will wheat farming revenue in Canada peak before declining?
Answer: I don't know. The text does not provide information on when the revenue will peak before declining. It mentions that revenue growth is expected to be small in the coming years, but it does not specify a particular year when the revenue will peak.

Result 40
Question: Here's a rewritten version of the question:

"What Canadian industries are easiest for specialized trucking companies to operate in?"

I've kept the core meaning of the original question, but made it more concise and indirect by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "operating in" instead of "profit recovery efforts face the least resistance due to favorable market conditions and structural advantages")
* Changing the wording to make it more conversational and less formal.
Answer: Based on the provided context, it seems that the Canadian industries that are easiest for specialized trucking companies to operate in are:

* Local Specialized Freight Trucking
* Long-Distance Specialized Freight Trucking

These industries have relatively low barriers to entry, and the context suggests that they have a more favorable market environment compared to other trucking industries in Canada.

Result 41
Question: Here's a rewritten version of the question:

"What quartile has the strongest link between asset leverage and ROA?"

This version conveys the same meaning as the original question but in a more indirect and concise way, using abbreviations like "ROA" (Return on Assets) and "asset leverage" to refer to the ratio of total assets to equity.
Answer: I don't know.

Result 42
Question: Here's a rewritten version of the question:

"What market conditions favor stable market share concentration for family-owned farms in Canada's corn industry?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "market conditions" instead of "market conditions do")
* Focusing on the key aspect of the question (stable market share concentration)
Answer: Based on the provided context, the market conditions that favor stable market share concentration for family-owned farms in Canada's corn industry are:

* Low concentration of the industry, with no single entity controlling more than 1.0% of revenue
* Decentralized structure of the industry, with thousands of small companies operating locally and focusing on niche market segments
* Geographical diversity, with different regions suited to corn farming and climate variations across provinces creating specific agricultural niches
* Limited scope for any one farm to dominate, due to the need for manual labor and the lack of significant economies of scale
* Low barriers to entry, with moderate increasing barriers to entry, but no significant barriers to prevent new entrants from joining the market.

These market conditions contribute to a stable market share concentration for family-owned farms in Canada's corn industry, as they limit the ability of any single entity to dominate the market and create a fractured market with many small players.

Result 43
Question: Here is the rewritten question:

"What holds back live animal transport growth?
Answer: According to the context, regulatory oversight over the conditions of livestock transport is limiting the growth of the segment. Specifically, regulations prohibit transporting livestock for more than 36 hours without food, water, or rest, and compromised cattle can only be transported for a maximum of 12 hours. This presents many barriers for truckers looking to enter the market and keeps growth within the segment relatively stagnant.

CPU times: user 1.91 s, sys: 73 ms, total: 1.98 s
Wall time: 2min 22s

Add the list of answers into our original dataset. Now we have a complete test set that is ready for evaluation.

In [47]:
dataset = dataset.add_column("answer", answers)

In [39]:
type(dataset)

datasets.arrow_dataset.Dataset

## Evaluate the results

#### Preview the final test set

In [48]:
dataset.to_pandas().head(5)

,question,contexts,ground_truth,evolution_type,metadata,episode_done,answer
0,Here is a question that can be fully answered ...,[ers benefit both parties and will remain popu...,Construction activity drives the demand for dr...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The demand for dry bulk transportation in the ...
1,Here is a question that can be fully answered ...,[ navigate economic downturns and invest in ne...,The government's pro-immigration policies are ...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The expected outcomes of the government's pro-...
2,Here is a question that can be fully answered ...,[ Ireland\nâ¢\nFreight Trucking in China\nLon...,The rebound in economic growth is expected to ...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The expected impact of the rebound in economic...
3,Here is a question that can be fully answered ...,"[.8 pp\nProfit per Business\n$69,567\nCurrent ...",The growth of e-commerce in the long-distance ...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The growth of e-commerce in the long-distance ...
4,Here is a question that can be fully answered ...,[.8 1.9 2.6 1.6 3.2 2.8 2.5\nLabor intensive C...,The answer to given question is not present in...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The average debt ratio of corn farming enterpr...

Run the evaluation query to score the results. In this evaluation, we are looking at the following metrics:
- *[Faithfulness](https://docs.ragas.io/en/v0.1.21/concepts/metrics/faithfulness.html)*: Are all the claims that are made in the answer inferred from the given context(s)?
- *[Context Precision](https://docs.ragas.io/en/v0.1.21/concepts/metrics/context_precision.html)*: Did our retriever return good results that matched the question it was being asked?
- *[Answer Correctness](https://docs.ragas.io/en/v0.1.21/concepts/metrics/answer_correctness.html)*: Was the generated answer correct? Was it complete?

In [49]:
%%time
score = evaluate(
    dataset=dataset,
    metrics=[
        Faithfulness(),
        ContextPrecision(),
        AnswerCorrectness(),
    ],
    llm=llm, # Using OpenAI LLM as the evaluator
    embeddings=embeddings,
)

Evaluating:   0%|          | 0/132 [00:00<?, ?it/s]

Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.
Failed to parse output. Returning None.

CPU times: user 9.2 s, sys: 305 ms, total: 9.5 s
Wall time: 2min 43s

In [53]:
%%time
score = evaluate(
    dataset=dataset,
    metrics=[
        Faithfulness(),
        ContextPrecision(),
        AnswerCorrectness(),
    ],
    llm=generator_llm, # Using OpenAI LLM as the evaluator
    #llm=llm, # Using Llama LLM as the evaluator
    embeddings=embeddings,
)

Evaluating:   0%|          | 0/132 [00:00<?, ?it/s]

Exception raised in Job[35]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-LFzVoOu1ElL68fuxoIi9u7JG on tokens per min (TPM): Limit 30000, Used 29832, Requested 1975. Please try again in 3.614s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Exception raised in Job[63]: TimeoutError()
Exception raised in Job[118]: TimeoutError()
Exception raised in Job[64]: TimeoutError()
Exception raised in Job[1]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-LFzVoOu1ElL68fuxoIi9u7JG on tokens per min (TPM): Limit 30000, Used 28945, Requested 2652. Please try again in 3.194s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Exception raised in Job[84]: TimeoutError()
Exception raised in Job[91]: TimeoutError()
Exception raised in Job[112]: TimeoutError()
Exception raised in Job[24]: TimeoutError()
Exception raised in Job[34]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-LFzVoOu1ElL68fuxoIi9u7JG on tokens per min (TPM): Limit 30000, Used 29197, Requested 2516. Please try again in 3.426s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Exception raised in Job[120]: TimeoutError()
Exception raised in Job[66]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-LFzVoOu1ElL68fuxoIi9u7JG on tokens per min (TPM): Limit 30000, Used 29194, Requested 2306. Please try again in 3s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Exception raised in Job[73]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-LFzVoOu1ElL68fuxoIi9u7JG on tokens per min (TPM): Limit 30000, Used 29207, Requested 2506. Please try again in 3.426s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Exception raised in Job[109]: TimeoutError()
Exception raised in Job[9]: TimeoutError()
Exception raised in Job[3]: TimeoutError()
Exception raised in Job[4]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-LFzVoOu1ElL68fuxoIi9u7JG on tokens per min (TPM): Limit 30000, Used 29822, Requested 2548. Please try again in 4.74s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Exception raised in Job[39]: TimeoutError()
Exception raised in Job[22]: TimeoutError()
Exception raised in Job[130]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o in organization org-LFzVoOu1ElL68fuxoIi9u7JG on tokens per min (TPM): Limit 30000, Used 29440, Requested 2428. Please try again in 3.736s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Exception raised in Job[85]: TimeoutError()
Exception raised in Job[10]: TimeoutError()
Exception raised in Job[25]: TimeoutError()
Exception raised in Job[27]: TimeoutError()
Exception raised in Job[108]: TimeoutError()
Exception raised in Job[121]: TimeoutError()
Exception raised in Job[115]: TimeoutError()
Exception raised in Job[114]: TimeoutError()
Exception raised in Job[127]: TimeoutError()
Exception raised in Job[18]: TimeoutError()
Exception raised in Job[126]: TimeoutError()

CPU times: user 28.2 s, sys: 934 ms, total: 29.2 s
Wall time: 10min 38s

In [54]:
score.to_pandas().head(15)

,question,contexts,ground_truth,evolution_type,metadata,episode_done,answer,faithfulness,context_precision,answer_correctness
0,Here is a question that can be fully answered ...,[ers benefit both parties and will remain popu...,Construction activity drives the demand for dr...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The demand for dry bulk transportation in the ...,0.714286,NaN,0.376862
1,Here is a question that can be fully answered ...,[ navigate economic downturns and invest in ne...,The government's pro-immigration policies are ...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The expected outcomes of the government's pro-...,NaN,NaN,0.561819
2,Here is a question that can be fully answered ...,[ Ireland\nâ¢\nFreight Trucking in China\nLon...,The rebound in economic growth is expected to ...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The expected impact of the rebound in economic...,0.416667,1.0,0.501731
3,Here is a question that can be fully answered ...,"[.8 pp\nProfit per Business\n$69,567\nCurrent ...",The growth of e-commerce in the long-distance ...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The growth of e-commerce in the long-distance ...,NaN,NaN,0.217763
4,Here is a question that can be fully answered ...,[.8 1.9 2.6 1.6 3.2 2.8 2.5\nLabor intensive C...,The answer to given question is not present in...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The average debt ratio of corn farming enterpr...,0.500000,1.0,0.097032
5,Here is a question that can be fully answered ...,"[ Columbia\n43 11.3 886.4 11.2 40.9 4.0 1,885 ...",Ontario has the majority of new car dealership...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,Ontario has the majority of new car dealership...,1.000000,1.0,0.996805
6,Here is a question that can be fully answered ...,[ landscape is much more demanding than for tr...,Successful businesses in the specialized truck...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,Successful businesses in the specialized truck...,NaN,1.0,0.347695
7,Here is a question that can be fully answered ...,[ landscape is much more demanding than for tr...,Successful businesses in the specialized truck...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,Successful businesses in the specialized truck...,0.800000,NaN,0.361452
8,Here is a question that can be fully answered ...,[Transportation and Warehousing In Canada â¢ ...,IBISWorld specializes in industry research wit...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,IBISWorld specializes in industry research wit...,NaN,NaN,0.608252
9,Here is a question that can be fully answered ...,[ who don't enjoy the same pricing power.\nâ¢...,The expected long-term effects of rising truck...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The expected long-term effects of rising truck...,NaN,1.0,0.365598
10,Here is a question that can be fully answered ...,[.8m\nExports High Increasing\nWhat are the in...,"Ireland, the US, and the United Kingdom are ke...",simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The key international markets that drive deman...,1.000000,1.0,0.995565
11,Here is a question that can be fully answered ...,[ navigate economic downturns and invest in ne...,nan,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The Canadian long-distance specialized freight...,0.615385,NaN,NaN
12,Here is a question that can be fully answered ...,[s Low Revenue Growth (2005-2024)\nLow Outlier...,The answer to given question is present in con...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The expected Compound Annual Growth Rate (CAGR...,1.000000,1.0,0.105791
13,Here is a question that can be fully answered ...,[ 2028\n0\n50\n100\n150\nSource: IBISWorld\nCo...,100%,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,According to the Electric Vehicle Availability...,NaN,1.0,0.145791
14,Here is a question that can be fully answered ...,"[154 14.5 1.0 33.7\n2026 275,063 0.5 1.7 1.7 4...",The answer to given question is present in con...,simple,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True,The number of enterprises in the Long-Distance...,0.500000,1.0,0.091734

In [56]:
score["answer_correctness"].mean()

0.38295553132863697

In [57]:
score["faithfulness"].mean()

0.5777748237425657

In [45]:
#score.to_pandas().to_parquet  ("../../Testing_Data/score_llama_answeropenAi.parquet")

In [55]:
score.to_pandas().to_parquet  ("../../Testing_Data/score_llama_answer_openAi_scoreOpenAi.parquet")

In [94]:
#"Meta-Llama-3.1-8B-Instruct"
#chunksize, answer correctness, faithfulness, number of question
#10000, 0.592, 0.698, 50
# 5000, 0.617, 0.700, 50
# 3500, 0.677, 0.734, 50
# 3000, 0.688, 0.800, 50
# 2000, 0.629, 0.742, 50
# 1000, 0.644, 0.703, 50
#  500, 0.619, 0.503, 50
#  250, 0.594, 0.527, 50

In [ ]:
#2500, 0.62, 0.825
#3000, 0.60, 0.78 llama, llamaa, llama, llama
#3000, 062, 0.73, llama, llama, openAi, llama