# RAG Evaluation Test Set Generation

This example shows how to use the [Ragas](https://docs.ragas.io/en/stable/) (```v 0.1.22```) framework to generate a **test set** that can be used to evaluate the quality of a RAG pipeline. We then use the Python [LangChain](https://python.langchain.com/docs/introduction/) library to run some requests through this pipeline and we evaluate the quality of the results.

### <u>Requirements</u>
1. As you will accessing the LLMs and embedding models through Vector AI Engineering's Kaleidoscope Service (Vector Inference + Autoscaling), you will need to request a KScope API Key:

      Run the following command (replace ```<user_id>``` and ```<password>```) from **within the cluster** to obtain the API Key. The ```access_token``` in the output is your KScope API Key.
  ```bash
  curl -X POST -d "grant_type=password" -d "username=<user_id>" -d "password=<password>" https://kscope.vectorinstitute.ai/token
  ```
2. After obtaining the `.env` configurations, make sure to create the ```.kscope.env``` file in your home directory (```/h/<user_id>```) and set the following env variables:
- For local models through Kaleidoscope (KScope):
    ```bash
    export OPENAI_BASE_URL="https://kscope.vectorinstitute.ai/v1"
    export OPENAI_API_KEY=<kscope_api_key>
    ```
- For OpenAI models:
   ```bash
   export OPENAI_BASE_URL="https://api.openai.com/v1"
   export OPENAI_API_KEY=<openai_api_key>
   ```

## Set up the RAG workflow environment

#### Import libraries

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#!pip install pdfplumber

In [3]:
#import pdfplumber

In [4]:
import numpy as np
import os
import sys

from datasets import Dataset
from pathlib import Path

from langchain.chains import RetrievalQA
from langchain.document_loaders.pdf import PyPDFDirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_huggingface.embeddings import HuggingFaceEmbeddings
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

from ragas import evaluate
from ragas.metrics import Faithfulness, ContextPrecision, AnswerCorrectness
from ragas.testset import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context

In [5]:
cd ..

/fs01/home/ws_ikharchuk/rag_bootcamp_ik/rag_evaluation

#### Load config files

In [6]:
# Add root folder of the rag_bootcamp repo to PYTHONPATH
current_dir = Path().resolve()
parent_dir = current_dir.parent
sys.path.insert(0, str(parent_dir))

In [7]:
from utils.load_secrets import load_env_file
load_env_file()

#### Set up some helper functions

In [8]:
def pretty_print_docs(docs):
    print(
        f"\n{'-' * 100}\n".join(
            [f"Document {i+1}:\n\n" + d.page_content for i, d in enumerate(docs)]
        )
    )

#### Make sure other necessary items are in place

## Generate a sythentic test set

#### Start by loading in the documents we'll be using to augment our RAG generations

In [9]:
#load all documents

In [10]:

from langchain.document_loaders import TextLoader
from langchain.document_loaders import PyPDFLoader

In [11]:
%%time
directory_path = "/projects/RAG2/scotia-2/Datasets-Scotia-2/IBIS"
file_list = [
   '48412CA Long-Distance Freight Trucking in Canada Industry Report.pdf',
#'48422CA Local Specialized Freight Trucking in Canada Industry Report.pdf'
]  # Replace with your actual file names

# Load only the specified files
docs = []
for file_name in file_list:
    file_path = os.path.join (directory_path, file_name)
    loader = PyPDFLoader(file_path)
    docs.extend(loader.load())  # Append loaded pages to the list
print(f"Number of source documents: {len(docs)}")
for document in docs:
    document.metadata['file_name'] = document.metadata['source']

Number of source documents: 39
CPU times: user 1.46 s, sys: 111 ms, total: 1.57 s
Wall time: 1.57 s

In [12]:
%%time
# no need 
#Process PDFs
text_splitter = RecursiveCharacterTextSplitter(chunk_size=3000, chunk_overlap=32)
chunks = text_splitter.split_documents(docs)
print(f"Number of text chunks: {len(chunks)}")

Number of text chunks: 47
CPU times: user 8.7 ms, sys: 0 ns, total: 8.7 ms
Wall time: 8.21 ms

#### Now use OpenAI to generate a test set from the data in these documents (This takes about 2-3 minutes)

**IMP Note:** The LLM and embedding model used for test set generation should be more capable than the model being evaluated. Hence, we will use OpenAI GPT-4o and OpenAI embeddings for this purpose.

Store your OpenAI API key in ```~/.ragas_openai.env``` using the following format (this is in addition to ```~/.kscope.env```):

```bash
export RAGAS_OPENAI_BASE_URL="https://api.openai.com/v1"
export RAGAS_OPENAI_API_KEY=<openai_api_key>
```

In [13]:
# Select  LLM (Llama)

In [13]:
from utils.load_secrets import load_env_file_ragas
load_env_file_ragas()

In [15]:
# GENERATOR_BASE_URL = os.environ.get("OPENAI_BASE_URL")

# OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

In [16]:
# GENERATOR_MODEL_NAME = "Meta-Llama-3.1-8B-Instruct"
# #GENERATOR_MODEL_NAME = 'DeepSeek-R1-Distill-Qwen-1.5B'
# EMBEDDING_MODEL_NAME = "BAAI/bge-base-en-v1.5"

In [17]:
# llm = ChatOpenAI(
#     model=GENERATOR_MODEL_NAME,
#     temperature=0,
#     max_tokens=None,
#     base_url=GENERATOR_BASE_URL,
#     api_key=OPENAI_API_KEY
# )

In [14]:
generator_llm = ChatOpenAI(
    model="gpt-4o-mini",
    base_url=os.environ["RAGAS_OPENAI_BASE_URL"],
    api_key=os.environ["RAGAS_OPENAI_API_KEY"],
)
generator_embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small",
    base_url=os.environ["RAGAS_OPENAI_BASE_URL"],
    api_key=os.environ["RAGAS_OPENAI_API_KEY"],
)

In [19]:
# model_kwargs = {'device': 'cuda', 'trust_remote_code': True}
# encode_kwargs = {'normalize_embeddings': True} # set True to compute cosine similarity

# print(f"Setting up the embeddings model...")
# embeddings = HuggingFaceEmbeddings(
#     model_name=   EMBEDDING_MODEL_NAME,
#     model_kwargs=model_kwargs,
#     encode_kwargs=encode_kwargs,
# )

In [15]:
def read_csv_from_directory(directory_path):
    dataframes= []
    for filename in os.listdir(directory_path):
        if filename.endswith('.csv'): 
            file_path = os.path.join(directory_path, filename)
            df = pd.read_csv(file_path)
            df["source"] = filename
            # print(df.head(1))
            dataframes.append(df)
    return pd.concat(dataframes, ignore_index=True)

In [81]:
#Load TRUCKING  data
file_paths = [#'/projects/RAG2/scotia-2/Datasets-Scotia-2/Agriculture_txt/agri_ca_co.csv', 
              '/projects/RAG2/scotia-2/Datasets-Scotia-2/Transport_txt/transport_CA.csv', 
              #'/projects/RAG2/scotia-2/Datasets-Scotia-2/Auto_txt/auto_ca.csv', 
             ]
def load_txt_file(file_path):
    # Create a TextLoader instance

    loader = TextLoader(file_path)

    # Load the document

    document = loader.load()
    chunks2 =text_splitter.split_documents(document)
    print(f"Number of text chunks: {len(chunks2)}")
    return chunks2, document

In [82]:
%%time

for file_path in file_paths:
    chunks_news, document_news = load_txt_file(file_path)

Number of text chunks: 403
CPU times: user 32 ms, sys: 4.01 ms, total: 36 ms
Wall time: 33.4 ms

In [83]:
len(document_news), len (docs)

(1, 39)

40

In [19]:
%%time
#generator_llm = (
#    model="DeepSeek-R1-Distill-Llama-8B",
#    base_url=os.environ["OPENAI_BASE_URL"],
#    api_key=os.environ["OPENAI_API_KEY"],
#)
# Define the RAG embeddings model (different than the OpenAI embedding model defined above for test set generation)
model_kwargs = {'device': 'cuda', 'trust_remote_code': True}
encode_kwargs = {'normalize_embeddings': True} # set True to compute cosine similarity
# print(f"Setting up the RAG LLM...")
# llm = ChatOpenAI(
#     #model="DeepSeek-R1-Distill-Llama-8B",
#     model="Meta-Llama-3.1-8B-Instruct",
#     temperature=0,
#     max_tokens=256,
#     base_url=os.environ["OPENAI_BASE_URL"],
#     api_key=os.environ["OPENAI_API_KEY"],
# )

# embeddings = HuggingFaceEmbeddings(
#     model_name="BAAI/bge-base-en-v1.5",
#     model_kwargs=model_kwargs,
#     encode_kwargs=encode_kwargs,
# )

CPU times: user 8 µs, sys: 2 µs, total: 10 µs
Wall time: 16.5 µs

In [67]:
#generator_llm.generate('what is  the day today?, Answer in no more then 10 words')

In [68]:
# %%time
# # Create generator with OpenAI model
# generator = TestsetGenerator.from_langchain(
#     generator_llm=generator_llm,
#     critic_llm=generator_llm,
#     embeddings=generator_embeddings,
# )

# # Generate the test set
# testset = generator.generate_with_langchain_docs(
#     documents=documents, 
#     test_size=1,
#     distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25},
# )

In [31]:
%%time
# Create generator with LLama model
# generator = TestsetGenerator.from_langchain(
#     #generator_llm=llm,
#     generator_llm=generator_llm,
#     #critic_llm=llm,
#     critic_llm=generator_llm,
#     #embeddings=embeddings,
#     embeddings = generator_embeddings
# )

# # Generate the test set
# testset = generator.generate_with_langchain_docs(
#     documents=combined_docs, 
#     test_size=50,
#     distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25},
# )

embedding nodes:   0%|          | 0/746 [00:00<?, ?it/s]

Filename and doc_id are the same for all nodes.

Generating:   0%|          | 0/50 [00:00<?, ?it/s]

CPU times: user 37.9 s, sys: 1.01 s, total: 39 s
Wall time: 5min 6s

#### Save dataset

In [20]:
#testset2 = testset.to_pandas()

In [21]:
from collections import Counter

In [23]:
#len (testset2.metadata[0])

In [24]:
#testset2.tail(5)

In [25]:
import joblib

In [44]:


# Save (serialize) the object to a file
#joblib.dump(testset, "../../Testing_Data/testset_combined.pkl")

['../../Testing_Data/testset_combined.pkl']

In [45]:
#testset2.to_parquet ('../../Testing_Data/testset_combined.parquet')
#testset2.to_csv ('../../Testing_Data/testset_combined.csv', index =False)

In [26]:
#load 
# Load (deserialize) the object from file
testset = joblib.load("../../Testing_Data/testset_combined.pkl")

## Now, start the RAG pipeline!

#### Choose the RAG LLM and embedding model
Note: This is different than the OpenAI LLM and embedding model defined above for test set generation.

In [27]:
# RAG_LLM_MODEL_NAME = "Meta-Llama-3.1-8B-Instruct"
# RAG_EMBEDDING_MODEL_NAME = "BAAI/bge-base-en-v1.5"

Go through the embedding, storage and retrieval steps.

# Setting up having two vector stores

In [78]:
#PDF 

text_splitter = RecursiveCharacterTextSplitter(chunk_size=3000, chunk_overlap=32)
chunks = text_splitter.split_documents(docs)
print(f"Number of text chunks: {len(chunks)}")

Number of text chunks: 47

In [87]:
%%time
vectorstore_pdf = FAISS.from_documents(chunks, generator_embeddings)
retriever_pdf = vectorstore_pdf.as_retriever(search_kwargs={"k": 3})

CPU times: user 337 ms, sys: 3.97 ms, total: 341 ms
Wall time: 977 ms

In [84]:
len (chunks_news)

403

In [86]:
%%time
# news
vectorstore_news = FAISS.from_documents(chunks_news, generator_embeddings)
retriever_news = vectorstore_news.as_retriever(search_kwargs={"k": 3})

CPU times: user 2.13 s, sys: 40.3 ms, total: 2.17 s
Wall time: 5.84 s

In [88]:
from langchain.schema import BaseRetriever
from pydantic import Field
from typing import List

class CombinedRetriever(BaseRetriever):
    retrievers: List[BaseRetriever] = Field(default_factory=list)

    def get_relevant_documents(self, query: str):
        combined_results = []
        for retriever in self.retrievers:
            combined_results.extend(retriever.get_relevant_documents(query))
        return combined_results

# Instantiate the new combined retriever
combined_retriever = CombinedRetriever(retrievers=[retriever_pdf, retriever_news])

Iterate over the questions in our synthetic testset, and run them each through the RAG pipeline to see what answers get returned. (This also takes 2-3 minutes)

#### Generate answers for all the questions in our test set

In [89]:
# answer Questions

In [90]:
%%time
#USe OpenAi

dataset = testset.to_dataset()
answers = np.empty(len(dataset), dtype=object)

for index, row in enumerate(dataset):
    query = row["question"]
 
    #Run the query through the RAG pipeline
    rag_pipeline = RetrievalQA.from_llm(
        llm=generator_llm,
        retriever=combined_retriever
    )
    answer = rag_pipeline.invoke(input=query)
    answer = answer["result"]
    print(f"Result {index}\nQuestion: {query}\nAnswer: {answer}\n")
    
    # Store the result
    answers[index] = answer

Result 0
Question: What percentage of structural damage is being reported in Jasper due to the wildfires?
Answer: Authorities are reporting potential structural damage of up to 50% in Jasper due to the wildfires.

Result 1
Question: What is the expected growth range for adjusted diluted earnings per share according to CN's latest forecast?
Answer: I don't know.

Result 2
Question: What is the expected revenue growth for long-distance freight trucking services through the end of 2024?
Answer: The expected revenue growth for long-distance freight trucking services through the end of 2024 is a compound annual growth rate (CAGR) of 1.0%, reaching $31.3 billion. Additionally, revenue is anticipated to grow by 1.2% in 2024 alone.

Result 3
Question: What are the potential economic impacts of a labor stoppage at Canada's two largest railroad operators?
Answer: The potential economic impacts of a labor stoppage at Canada's two largest railroad operators, Canadian National Railway and Canadian Pacific Kansas City, are significant. Here are some key points:

1. **Economic Cost**: Moody's estimates that the simultaneous stoppage could cost the Canadian economy approximately C$341 million per day.

2. **Disruption of Goods Transport**: The railways transport about C$380 billion worth of goods and commodities annually. A stoppage would severely disrupt the movement of essential goods, including grain, automobiles, potash, coal, and fertilizers.

3. **Impact on Various Sectors**: Industries heavily reliant on rail transport, such as agriculture, mining, and manufacturing, could face crippling supply-chain delays, increased costs, cash-flow constraints, and potential shutdowns due to the inability to transport their products.

4. **Increased Demand for Trucking**: While trucking companies may absorb some of the increased demand, they cannot fully replace long-haul rail distribution, especially for bulk commodities. This could lead to higher costs and longer lead times for transporting goods.

5. **Cross-Border Trade**: About 85% of U.S.-Canada cross-border freight is handled by Canadian trucking carriers. A rail stoppage will also affect cross-border shipments, creating further complications for trade between the two countries.

Overall, the labor stoppage could lead to widespread economic disruption across North America, affecting both Canadian and U.S. economies due to the interconnected nature of their supply chains.

Result 4
Question: What is the purpose of the conciliation process in labor negotiations?
Answer: I don't know.

Result 5
Question: What strategies do successful businesses use to overcome volatility in the freight trucking industry?
Answer: Successful businesses in the freight trucking industry use the following strategies to overcome volatility:

1. **Establish Long-Term Working Relationships with Suppliers**: Building strong ties with raw material suppliers ensures a reliable flow of materials and components, reducing the impact of market disruptions and price spikes.

2. **Optimize Operating Capacity**: Efficiently managing and utilizing fleet resources allows trucking companies to adapt to fluctuating demand, ensuring cost-effective operations and maintaining competitiveness during periods of volatility.

3. **Offer Competitively Priced Products**: Competitive pricing is essential to attract more clientele while maintaining profitability, especially in a market where cost efficiency is critical.

4. **Adopt a High-Volume, Low-Margin Strategy**: Moving large volumes of goods at competitive rates helps companies capture market share and optimize route efficiency, maximizing overall profitability.

5. **Diversify Client Base**: Serving a wide variety of clients lowers dependency on a single market segment, which helps balance power dynamics and ensures stable revenue streams.

6. **Secure a Highly Skilled Workforce**: Retaining skilled and experienced drivers is vital for ensuring prompt transportation and service quality, which is essential in a competitive environment.

7. **Leverage Technology**: Investing in best-in-class technology can enhance operational efficiency, improve service levels, and facilitate timely and damage-free transportation of customer freight.

By implementing these strategies, businesses can better navigate the challenges posed by volatility in the freight trucking industry.

Result 6
Question: What factors contributed to the increase in FedEx shares on June 26?
Answer: The increase in FedEx shares on June 26 was attributed to several factors:

1. A bullish annual profit forecast, which projected fiscal 2025 earnings of $20 to $22 per share, slightly above analysts' estimates.
2. The company's efforts in restructuring, including combining its air and land-based delivery units, cutting jobs, and optimizing resources, which aimed to improve profitability.
3. The positive performance of its FedEx Freight trucking business, which is the largest in North America and generated significant revenue despite a downturn in the trucking market.
4. Analyst comments valuing the Freight business at $30 billion, suggesting that it could be a significant asset if sold or spun off, which could lead to a higher valuation for the company.
5. Overall market sentiment following these announcements, leading to increased investor confidence in FedEx's prospects.

Result 7
Question: What is the significance of Westshore's potash project in relation to its business diversification and environmental commitments?
Answer: Westshore's potash project is significant for its business diversification as it represents a transformational shift into the agriculture sector, allowing the company to expand its operations beyond coal handling. This diversification enhances Westshore's long-term sustainability and creates new revenue streams, particularly given the critical role of potash in fertilizer production for global agriculture.

In terms of environmental commitments, the potash project aligns with Westshore's goals to limit the impact of its operations on the environment. By investing in potash handling facilities, Westshore is taking steps to diversify its portfolio while also supporting agricultural practices that are essential for food production. Additionally, the project reflects an effort to balance the ongoing need for coal with the recognition of climate impacts associated with coal consumption, emphasizing a move towards more renewable energy resources in the long term.

Result 8
Question: What is the purpose of the National Safety Code in the freight trucking industry?
Answer: The National Safety Code encourages trucking safety, promotes efficiency, and establishes consistent safety standards across the provinces and territories. It covers safety and administrative regulations for single-driver licenses, knowledge and performance tests, driver examiner training, self-certification, and on-road inspections.

Result 9
Question: What impact did the floods have on Halifax and its infrastructure?
Answer: The floods in Halifax caused significant damage to infrastructure, washing away roads, swamping buildings, and damaging bridges. A Canadian National Railway track used to access Halifax, which is Canada's fourth-largest port, was also affected. The damage led to a province-wide state of emergency in Nova Scotia, with Premier Tim Houston stating that the cost of the damage would likely be in the "hundreds of millions" of dollars. Additionally, 19 bridges were damaged, another six were completely destroyed, and many roads remained closed. The extent of the flooding disrupted transportation and posed challenges for search and rescue operations, as well as for the supply chain, with 60% of cargoes at the port being rail-based.

Result 10
Question: What recent actions has Mexico taken regarding fuel and petrochemical imports to combat smuggling?
Answer: Mexico has imposed fresh restrictions on imports of various refined petroleum and petrochemical products to curb fuel theft and adulteration. This includes certain types of gasoline, diesel, jet fuel, and additives like MTBE (methyl tert-butyl ether). Rail cars containing these products from Texas to Mexico have been temporarily held back by Canadian Pacific Kansas City (CPKC) until companies can provide the necessary import permits. The measures aim to stop the adulteration and trade of fuels that could pose risks to human health, the environment, and vehicles.

Result 11
Question: What is TFI International's market capitalization as of FY 2023?
Answer: I don't know.

Result 12
Question: What factors contributed to the decline of the Toronto Stock Exchange?
Answer: Several factors contributed to the decline of the Toronto Stock Exchange, including:

1. **Profit Taking**: Investors engaged in profit taking after stocks that had performed well began to underperform, particularly in the technology sector.

2. **Disappointing Earnings**: Key companies, such as Tesla and Alphabet, reported lackluster earnings, leading investors to question the sustainability of the equity rally driven by technology and AI.

3. **Interest Rate Cuts**: While the Bank of Canada cut interest rates, which could generally support the market, the overall investor sentiment was cautious due to the broader economic context.

4. **Economic Slowdown**: Evidence of a slowdown in the domestic economy, including declining retail sales, contributed to market declines.

5. **Bond Yield Concerns**: Rising long-term borrowing costs, particularly in the bond market, created uncertainty and negatively impacted market sentiment.

6. **Sector-Specific Weakness**: Specific sectors, such as industrials (including railroad stocks), faced losses due to missed revenue estimates from major companies like Canadian National Railway and Canadian Pacific Kansas City.

These factors combined to create a negative environment for the stock market.

Result 13
Question: What accounting principles does CPKC follow for preparing financial information?
Answer: CPKC prepares financial information in accordance with accounting principles generally accepted in the United States of America (U.S. GAAP).

Result 14
Question: What decision is the U.S. Federal Reserve expected to make regarding interest rates?
Answer: The U.S. Federal Reserve is expected to leave interest rates unchanged.

Result 15
Question: What are the environmental benefits associated with the rail network's operations?
Answer: The environmental benefits associated with the rail network's operations include:

1. **Reduced Emissions**: The rail network has significantly reduced locomotive emissions intensity, achieving a reduction of 45% since 1993. This means that trains produce fewer greenhouse gas emissions per unit of cargo transported compared to other modes of transportation.

2. **Lower Fuel Consumption**: The rail network consumes approximately 15% less fuel per gross ton mile than the industry average. This greater fuel efficiency contributes to lower overall carbon emissions.

3. **Encouragement of Fuel-Efficient Technologies**: The Canadian Environmental Protection Act (CEPA) enforces emissions standards for pollutants, which pushes the rail network to adopt fuel-efficient and alternative fuel technologies.

4. **Optimized Operations**: The disciplined approach to scheduled railroading promotes efficiency and fluidity across the network, ensuring that operations are aligned with environmental sustainability goals.

5. **Reduced Carbon Footprint**: The focus on decoupling carbon emissions from growth ensures that as the rail network expands its operations, it does so in a way that minimizes its environmental impact.

Overall, the rail network's operations are designed to minimize emissions and enhance sustainability, contributing positively to environmental goals.

Result 16
Question: What action is the Teamsters Canada Rail Conference planning to take in response to the decision that ended the railway work stoppage?
Answer: The Teamsters Canada Rail Conference is planning to mount a legal challenge to the decision that ended the railway work stoppage and imposed arbitration. They have warned that this decision could lead to the imposition of future contracts, eroding workers' bargaining power.

Result 17
Question: What is the significance of foreign investment in Mexico's regulatory framework?
Answer: I don't know.

Result 18
Question: What is the current status of paid sick leave for U.S. rail workers?
Answer: As of September 2023, the percentage of U.S. rail workers who are guaranteed paid sick leave has increased from 5% to 90% since the end of 2022. However, there are still about 10,000 employees who do not have this benefit. The Biden administration has called on major freight railroads to ensure that all workers have access to paid sick leave.

Result 19
Question: What are acquisition-related costs and how do they impact CPKC's financial results?
Answer: Acquisition-related costs refer to expenses incurred during the process of acquiring another company. These costs can include legal fees, consulting fees, financing fees, integration costs (such as third-party services and system migration), community investments, and costs associated with restructuring and employee retention.

For CPKC, these costs can significantly impact financial results, particularly because they may not be one-time expenses and could continue beyond the year of acquisition. They can affect the diluted earnings per share (EPS) but may be excluded from the company's core adjusted combined diluted EPS, which aims to present a clearer picture of ongoing operational performance. Additionally, unpredictable factors such as foreign exchange rates can also influence reported results but may be removed from certain financial calculations.

Result 20
Question: What processes are involved in the surface water collection at Westshore?
Answer: Westshore collects all rainwater and surface runoff through a series of ditches and sumps, which treat the water using a settlement process to remove coal particles and other solids. Additionally, a water treatment system with sieve bins is in place to treat the water used on site, further removing coal particles from the collected surface water. The terminal discharges treated surface runoff water through an ocean discharge system that employs coagulation and flocculation processes to meet discharge permit criteria for Total Suspended Solids (TSS) levels, oil, and grease. The treated water is continuously monitored with electronic instrumentation, and weekly water samples are analyzed for compliance.

Result 21
Question: What companies acquired by TFI International provide truckload services?
Answer: The context does not specify the names of the companies acquired by TFI International that provide truckload services. Therefore, I don't know the answer.

Result 22
Question: What recent event affected the operations of Canadian National Railway in Nova Scotia?
Answer: Recent flooding in Nova Scotia affected the operations of Canadian National Railway, leading to the shutdown of a line. The floods caused extensive damage, including to the railway tracks used for freight trains heading for the Port of Halifax.

Result 23
Question: What are the potential economic impacts of the looming labor dispute at Canada's main railroads?
Answer: The looming labor dispute at Canada's main railroads could have significant economic impacts, including:

1. **Disruption of Freight Movement**: A simultaneous labor stoppage at Canadian National Railway and Canadian Pacific Kansas City could halt the majority of Canada's freight rail system, disrupting the transport of essential goods such as grain, automobiles, coal, and potash.

2. **Economic Damage**: Estimates suggest that shutting down 75% of Canada's freight rail traffic could cost the economy approximately C$341.5 million ($251 million) per day, which would represent more than 4% of the nation's GDP.

3. **Impact on Industries**: Various industries that rely on rail transport for shipping goods would face challenges, potentially leading to supply chain disruptions and increased costs.

4. **Increased Costs**: Companies may experience increased shipping costs as they seek alternative transportation methods, which could lead to higher prices for consumers.

5. **Market Confidence**: The uncertainty surrounding the labor dispute could negatively affect market confidence, potentially impacting investment and economic growth.

6. **Labor Relations**: The dispute may also set a precedent for future labor negotiations in other sectors, influencing labor relations across the country.

Overall, the labor dispute at Canada's main railroads has the potential to inflict considerable economic harm if not resolved promptly.

Result 24
Question: What role do technology improvements play in enhancing the safety and efficiency of freight trucking?
Answer: Technology improvements play a significant role in enhancing the safety and efficiency of freight trucking in several ways:

1. **Safety Enhancements**: Technology has introduced various safety measures aimed at ensuring drivers' health and reducing operational losses. For example, advancements in vehicle technology help prevent accidents by keeping vehicles on the road, controlling acceleration, and managing speed on steep grades.

2. **Data Collection and Analytics**: Companies are increasingly upgrading their fleets with sensors and other technologies to collect data on driving patterns. This data helps in identifying potential risks and preventing accidents, thus improving overall safety.

3. **Route Optimization**: Technologies such as the Internet of Things (IoT) and artificial intelligence (AI) optimize route planning, enhancing the efficiency of freight delivery. These technologies provide better transport analytics and insights, allowing for more efficient operations.

4. **Vehicle Modernization**: The adoption of hybrid and electric vehicles not only targets environmental sustainability but also mitigates the uncertainties related to fuel prices, thus improving operational efficiency.

5. **Automation**: While technologies like autonomous trucks are still in the developmental phase, they hold the potential to address labor shortages and enhance operational efficiency in the long term.

Overall, these technological advancements contribute to a safer, more efficient, and more competitive freight trucking industry.

Result 25
Question: What led to Canada's stock index peak alongside rising gold prices?
Answer: Canada's stock index peaked due to a combination of factors, including a jump in oil prices which boosted energy shares, and positive corporate earnings reports. Additionally, the market reacted favorably to prospects of lower interest rates, as indicated by comments from Federal Reserve Chair Jerome Powell. Rising gold prices also contributed to the positive sentiment in the market, as gold is one of Canada's top exports. Overall, the rotation towards commodities, including energy and materials, played a significant role in lifting the stock index.

Result 26
Question: What support might help Canada with back-to-work laws during labor disputes?
Answer: I don't know.

Result 27
Question: How did UPS's freight sales affect its valuation?
Answer: UPS's freight sales affected its valuation by contributing to a significant reduction in its overall value. The company sold its freight business to TFI International for $800 million in 2021, prior to a downturn in the trucking market. More recently, UPS announced the sale of its Coyote freight brokerage for just over $1 billion, which was nearly $800,000 less than it paid to acquire the business about a decade ago. These sales indicate a decline in the perceived value of UPS's freight operations and have implications for its overall market position and financial performance.

Result 28
Question: What training do EIC volunteers get for Indigenous attendees?
Answer: EIC volunteers complete Indigenous sensitivity training as recommended by their Indigenous partners.

Result 29
Question: What agri-products might see shipment delays if Canadian railways stop?
Answer: If Canadian railways stop, several agri-products might see shipment delays, including:

1. Grains - As much as 94% of grain is shipped by rail, and a stoppage would significantly impact shipments, particularly for U.S. spring wheat from Minnesota, North Dakota, and South Dakota to the Pacific Northwest for export.

2. Soybeans - The movement of Ontario soybeans to export markets, primarily Japan, could completely stop just before the harvest.

3. Fertilizers - Disruptions in rail service could affect the movement of fertilizers, which are crucial for corn farmers applying them in fall and spring.

4. Meat Products - Canadian meat producers have warned that a rail stoppage could lead to significant losses and waste, with some processing plants expecting to lose up to C$3 million a week.

These delays could result in increased costs and logistical challenges for the agriculture industry.

Result 30
Question: What signals from the Fed might sway investor interest rates?
Answer: Investors are closely watching the Federal Reserve's monetary policy decisions, particularly regarding indications of when the Fed might lower interest rates. Signals that could sway investor interest include comments on economic growth, inflation rates, and any guidance provided on the future path of interest rates during Fed meetings. Additionally, hints about the Fed's approach to managing inflation and employment can also influence investor sentiment and expectations around interest rates.

Result 31
Question: What makes the N.A. rail network connect 3 countries well?
Answer: I don't know.

Result 32
Question: What acquisitions did TFI make for LTL growth?
Answer: TFI International made several acquisitions to enhance its less-than-truckload (LTL) business. Notably, it acquired UPS Freight, which provided access to an established network and customer base, thereby expanding its reach and capabilities in the North American region. Additionally, TFI International acquired Daseke for $1.1 billion in 2024, adding significant assets to its fleet and further strengthening its LTL operations. These acquisitions align with TFI's strategy to enhance its LTL business and improve cash flows.

Result 33
Question: What position will Jim Vena take at Union Pacific post-Lance Fritz?
Answer: Jim Vena will take the position of CEO at Union Pacific, replacing Lance Fritz.

Result 34
Question: What might the FedEx freight sale mean?
Answer: I don't know.

Result 35
Question: What hints at stable oil exports from Canada to the U.S. amid a labor dispute?
Answer: The hints at stable oil exports from Canada to the U.S. amid a labor dispute include:

1. **Excess Capacity on Pipelines**: The Trans Mountain expansion, which nearly tripled the flow of crude from Alberta to the Pacific coast, has created excess capacity that can accommodate oil exports even during a labor dispute at the railroads.

2. **Decreased Reliance on Crude-by-Rail**: U.S. rail imports of Canadian crude have fallen sharply, indicating that crude-by-rail is not as essential to the Canadian market as it once was, particularly after the Trans Mountain expansion.

3. **Maintenance at U.S. Refineries**: Maintenance at U.S. Midwest refineries will free up pipeline space for additional barrels, further supporting stable oil exports.

4. **Current Market Conditions**: The relatively small discount on Canadian crude prices compared to U.S. West Texas Intermediate suggests that there is little market concern about moving Canadian crude, indicating stability in exports.

Result 36
Question: Which sectors benefited from earnings and rate outlook?
Answer: The sectors that benefited from earnings and a robust rate outlook include utilities and telecommunications, as noted in the context. Additionally, strong earnings from major companies could boost the TSX further.

Result 37
Question: What are the Teamsters' main goals in wage talks with CN Rail, considering a possible work stoppage's economic impact?
Answer: The Teamsters' main goals in wage talks with CN Rail include ensuring the preservation of safety-critical fatigue provisions in their collective agreement and addressing concerns over forced relocations for workers. They want to secure competitive wages and working conditions that reflect the needs of their members while preventing any changes that could compromise safety or increase the risk of accidents. The union is negotiating against the backdrop of a potential work stoppage, which they believe could inflict significant economic damage.

Result 38
Question: What impact might CN's move to Hinton have on local jobs and the town's economy post-wildfires?
Answer: CN's move to Hinton is expected to have a significant negative impact on local jobs and the town's economy in Jasper. The relocation will directly affect around 200 union workers currently living in Jasper, which could lead to job losses and economic strain for those families. Additionally, since rail operations are one of the largest industries in Jasper, after tourism, this move could further cripple the community, especially as it is still recovering from the devastation caused by the wildfires. The loss of jobs in the rail industry could exacerbate the economic challenges the town is facing, particularly in the wake of the wildfires that have already harmed the local economy and tourism sector.

Result 39
Question: How do transport modes and economy affect trade efficiency in N.A.?
Answer: I don't know.

Result 40
Question: What impact does the new CPKC-CSX rail corridor have on grain transport efficiency and Canadian rail labor talks?
Answer: I don't know.

Result 41
Question: What's the reasoning behind CPKC's Non-GAAP measures in financial reporting, and how do they improve earnings and liquidity assessment vs. U.S. GAAP?
Answer: CPKC presents Non-GAAP measures to provide an additional basis for evaluating underlying earnings and liquidity trends in their financial results. The reasoning behind using Non-GAAP measures is that they facilitate a multi-period assessment of long-term profitability and help in assessing future profitability.

These measures allow management and stakeholders to analyze financial performance in a way that may highlight trends not captured by traditional U.S. GAAP metrics. Non-GAAP measures can offer insights into the company's operational efficiency and financial health by adjusting for certain items that may distort the evaluation of ongoing business performance.

However, it's important to note that these Non-GAAP measures have no standardized meaning and are not defined by U.S. GAAP, which means they may not be comparable to similar measures presented by other companies. They are not intended to be considered in isolation from or as a substitute for the financial information presented in accordance with U.S. GAAP.

Result 42
Question: What factors shape competition in long-distance trucking?
Answer: Competition in long-distance trucking is shaped by several factors:

1. **Barriers to Entry**: The industry has low barriers to entry, allowing individuals to easily start a trucking business with minimal capital requirements. This increases the number of competitors in the market.

2. **Market Power of Large Companies**: Major freight trucking companies hold significant market power by securing large contracts with manufacturers and retailers. Their ability to offer a diverse range of services provides them a competitive advantage.

3. **Substitutes**: Rail transportation benefits from economies of scale, making it a preferred option for transporting bulky, high-volume shipments, thereby increasing competition for trucking services.

4. **Fuel Prices**: Volatile diesel prices can affect the cost structure of trucking companies. Those that do not establish fuel contracts may face difficulties in passing on price increases to consumers, impacting their competitiveness.

5. **Labor Shortages**: The industry is facing labor shortages as an aging workforce retires and younger workers are less inclined to become truck drivers. This necessitates competitive compensation packages to attract new drivers.

6. **Technological Advancements**: Innovations in logistics and supply chain management can enhance efficiency and reduce costs, influencing competitive dynamics in the industry.

7. **Customer Demand**: Changes in consumer behavior, such as increased online shopping, can drive demand for freight transportation services, thereby shaping competition among trucking firms.

8. **Regulatory Environment**: Regulations and policies can impact operational costs and competitive strategies within the industry.

These factors collectively influence how companies compete in the long-distance trucking sector.

Result 43
Question: What impacts do forward-looking statements in TFI's outlook have, and what external factors affect their reliability?
Answer: Forward-looking statements in TFI International's outlook reflect the company's current expectations regarding future operations and performance. However, these statements are subject to certain risks and uncertainties that could cause actual results to differ materially from what is anticipated.

External factors that affect the reliability of these forward-looking statements include:

1. Competitive market conditions.
2. The company's ability to recruit, train, and retain qualified drivers.
3. Variations in fuel prices and the company's ability to recover these costs from customers.
4. Foreign currency fluctuations.
5. The impact of environmental standards and regulations.
6. Changes in governmental regulations applicable to the company's operations.
7. Adverse weather conditions.
8. Accidents and their impact on operations.
9. Market conditions for used equipment.
10. Changes in interest rates.
11. The cost of liability insurance coverage.
12. Downturns in general economic conditions affecting the company and its customers.
13. Credit market liquidity.
14. The company's ability to identify, negotiate, consummate, and successfully integrate business acquisitions.

These factors can significantly impact TFI's performance and should be considered when evaluating the company's forward-looking statements.

Result 44
Question: What are Westshore's key focuses for environmental and governance efforts?
Answer: Westshore's key focuses for environmental and governance efforts include:

1. **Minimizing Environmental Impact**: Westshore is committed to protecting the natural environment around its operations, aiming to minimize the impact of its activities.

2. **Dust Reduction Activities**: The company engages in ongoing dust reduction activities, such as using spray towers and water trucks, to manage air quality and dust emissions.

3. **Compliance with Air Emissions Permits**: Westshore operates real-time electronic and passive sampling systems to monitor compliance with air emissions permits and ensure that dust fall measurements meet air quality guidelines.

4. **Greenhouse Gas Emissions Reduction**: The company has implemented measures to reduce greenhouse gas emissions, with a focus on utilizing electric power for equipment and minimizing diesel fuel use.

5. **Water Management**: Westshore collects and treats all rainwater and surface runoff to remove pollutants, ensuring that discharges meet quality standards established by relevant permits.

6. **Workplace Safety and Inclusivity**: Westshore prioritizes creating a safe, respectful, and inclusive workplace for its employees.

7. **Transparent Governance**: The company emphasizes accountability to its shareholders through transparent and effective governance structures.

8. **Ongoing ESG Reporting**: Westshore has been publishing annual Environmental, Social, and Governance (ESG) reports to track and communicate its performance and improvements.

Result 45
Question: What acquisitions did TFI make to boost its LTL capacity in North America?
Answer: TFI International made several acquisitions to boost its LTL capacity in North America, including the acquisition of UPS Freight, which provided access to an established network and customer base, enhancing its less-than-truckload capacity and regional reach. Additionally, in 2024, TFI acquired Daseke for $1.1 billion, which added 2,430 tractors and 6,820 trailers to its fleet, further supporting its strategy to enhance its LTL business.

Result 46
Question: What challenges does the Mayan Train project have with budget and the new Inter-Oceanic Train?
Answer: The Mayan Train project has faced significant budget challenges, reportedly running nearly four times over budget and still being far from completion. Additionally, there are concerns regarding its overall progress and management.

The new Inter-Oceanic Train, which is intended to connect the Gulf coast to the Pacific Ocean, has been pitched as a potential rival to the Panama Canal. However, analysts estimate that its capacity to ship goods will be just a fraction of what the canal can handle. Moreover, there were issues earlier this year when Mexican authorities seized parts of a rail line operated by Grupo Mexico for the Inter-Oceanic Train, indicating potential complications in its development and operation.

Result 47
Question: What benefits do businesses see from integrated supply chain solutions, especially with LTL in global distribution?
Answer: Businesses see several benefits from integrated supply chain solutions, particularly with less-than-truckload (LTL) services in global distribution:

1. **Cost Savings**: By contracting long-distance LTL services, businesses can save costs associated with shipping. LTL allows for the consolidation of smaller shipments, which can be more economical compared to full truckload (TL) options.

2. **Increased Efficiency**: Integrated supply chain solutions enable businesses to streamline their operations and improve distribution efficiency. By leveraging existing infrastructure, particularly with intermodal solutions that combine different modes of transport, businesses can optimize their logistics.

3. **Flexibility in Operations**: LTL services support shipment consolidation, allowing businesses to handle partial loads from multiple customers, which provides more flexibility in meeting diverse shipping needs.

4. **Enhanced Service Levels**: Businesses can offer better service levels to their clients through reliable and timely deliveries. The integration of technology in LTL services, such as GPS and order-management systems, enhances tracking and coordination.

5. **Adaptation to E-commerce Growth**: With the rising demand in e-commerce, businesses benefit from the capabilities of LTL services to fulfill smaller, more frequent orders, accommodating the needs of online merchants.

6. **Access to Global Markets**: Integrated supply chain solutions enable businesses to source goods from global markets more effectively, satisfying domestic demand while remaining competitive.

Overall, these benefits contribute to improved operational performance, lower operational costs, and enhanced competitiveness in the global marketplace.

Result 48
Question: What steps did the Bombers take for Indigenous reconciliation in line with EIC's model?
Answer: The Bombers participated in the National Day for Truth and Reconciliation by inviting over 1,000 Indigenous people from across Canada to attend a Canadian Football League game. This event aimed to bring attention to the need for reconciliation with Indigenous peoples and was part of a collaboration involving several CFL teams. Additionally, through the Atik Mason Indigenous Pilot Pathway, EIC invested over $2 million annually back into relationships with Indigenous communities and partners, which is expected to approach $3 million in 2024.

Result 49
Question: What prompted Mayor Salinas's emergency declaration regarding the migrant surge and its impact on border traffic?
Answer: Mayor Salinas issued an emergency declaration due to a "severe undocumented immigrant surge," which led to the temporary closure of train traffic to Mexico via the Eagle Pass gateway in Texas. This situation was exacerbated by reports of migrants from Mexico riding on rail cars to cross into the U.S., which prompted U.S. border authorities to limit the flow of goods into the country.

CPU times: user 2.5 s, sys: 48.1 ms, total: 2.54 s
Wall time: 2min 2s

In [68]:
# %%time
# #Use LLama
# dataset = testset.to_dataset()
# answers = np.empty(len(dataset), dtype=object)

# for index, row in enumerate(dataset):
#     query = row["question"]
    
#     # Run the query through the RAG pipeline
#     rag_pipeline = RetrievalQA.from_llm(
#         llm=llm,
#         retriever=retriever
#     )
#     answer = rag_pipeline.invoke(input=query)
#     answer = answer["result"]
#     print(f"Result {index}\nQuestion: {query}\nAnswer: {answer}\n")
    
#     # Store the result
#     answers[index] = answer

Add the list of answers into our original dataset. Now we have a complete test set that is ready for evaluation.

In [91]:
dataset = dataset.add_column("answer", answers)

In [92]:
type(dataset)

datasets.arrow_dataset.Dataset

## Evaluate the results

#### Preview the final test set

In [93]:
dataset.to_pandas().head(5)

,question,contexts,ground_truth,evolution_type,metadata,episode_done,answer
0,What percentage of structural damage is being ...,"[while choking back tears. \n """"We're seein...",The context reports potentially 30% to 50% str...,simple,"[{'file_name': None, 'page': None, 'source': '...",True,Authorities are reporting potential structural...
1,What is the expected growth range for adjusted...,[ transportation of various commodities and go...,"According to CN's latest forecast, the expecte...",simple,"[{'file_name': None, 'page': None, 'source': '...",True,I don't know.
2,What is the expected revenue growth for long-d...,[ping t o addr ess l abor short ages. A s the ...,Revenue for long-distance freight trucking ser...,simple,[{'file_name': '/projects/RAG2/scotia-2/Datase...,True,The expected revenue growth for long-distance ...
3,What are the potential economic impacts of a l...,[ binding arbitration is imposed.\n Earlier...,The potential economic impacts of a labor stop...,simple,"[{'file_name': None, 'page': None, 'source': '...",True,The potential economic impacts of a labor stop...
4,What is the purpose of the conciliation proces...,[ions to breakthrough on these paid sick leave...,The purpose of the conciliation process in lab...,simple,"[{'file_name': None, 'page': None, 'source': '...",True,I don't know.

Run the evaluation query to score the results. In this evaluation, we are looking at the following metrics:
- *[Faithfulness](https://docs.ragas.io/en/v0.1.21/concepts/metrics/faithfulness.html)*: Are all the claims that are made in the answer inferred from the given context(s)?
- *[Context Precision](https://docs.ragas.io/en/v0.1.21/concepts/metrics/context_precision.html)*: Did our retriever return good results that matched the question it was being asked?
- *[Answer Correctness](https://docs.ragas.io/en/v0.1.21/concepts/metrics/answer_correctness.html)*: Was the generated answer correct? Was it complete?

In [94]:
%%time
score = evaluate(
    dataset=dataset,
    metrics=[
        Faithfulness(),
        ContextPrecision(),
        AnswerCorrectness(),
    ],
    llm=generator_llm, # Using OpenAI LLM as the evaluator
    embeddings=generator_embeddings,
)

Evaluating:   0%|          | 0/150 [00:00<?, ?it/s]

CPU times: user 15.3 s, sys: 199 ms, total: 15.5 s
Wall time: 1min 41s

In [95]:
%%time
#use OpenAi
# score = evaluate(
#     dataset=dataset,
#     metrics=[
#         Faithfulness(),
#         ContextPrecision(),
#         AnswerCorrectness(),
#     ],
#     llm=generator_llm, # Using OpenAI LLM as the evaluator
#     #llm=llm, # Using Llama LLM as the evaluator
#     embeddings=embeddings,
# )

CPU times: user 10 µs, sys: 1e+03 ns, total: 11 µs
Wall time: 18.8 µs

In [96]:
score.to_pandas().isna().sum(axis =0)

question              0
contexts              0
ground_truth          0
evolution_type        0
metadata              0
episode_done          0
answer                0
faithfulness          0
context_precision     0
answer_correctness    0
dtype: int64

In [97]:
score.to_pandas().tail(2)

,question,contexts,ground_truth,evolution_type,metadata,episode_done,answer,faithfulness,context_precision,answer_correctness
48,What steps did the Bombers take for Indigenous...,[ people from across\nCanada to attend the Win...,"The Bombers, in line with EIC's model, partici...",multi_context,"[{'file_name': None, 'page': None, 'source': '...",True,The Bombers participated in the National Day f...,0.833333,1.0,0.817251
49,What prompted Mayor Salinas's emergency declar...,[ late 2021 to help fund its\napproximately $3...,Mayor Salinas issued an emergency declaration ...,multi_context,"[{'file_name': None, 'page': None, 'source': '...",True,Mayor Salinas issued an emergency declaration ...,1.000000,1.0,0.612501

In [98]:
score["answer_correctness"].mean()

0.5750182259677298

In [99]:
score["faithfulness"].mean()

0.5718615107115107

In [45]:
#score.to_pandas().to_parquet  ("../../Testing_Data/score_llama_answeropenAi.parquet")

In [66]:
score.to_pandas().to_parquet  ("../../Testing_Data/score_llama_answer_openAi_scoreOpenAi_2_DB.parquet")

In [94]:
#"Meta-Llama-3.1-8B-Instruct"
#chunksize, answer correctness, faithfulness, number of question
#10000, 0.592, 0.698, 50
# 5000, 0.617, 0.700, 50
# 3500, 0.677, 0.734, 50
# 3000, 0.688, 0.800, 50
# 2000, 0.629, 0.742, 50
# 1000, 0.644, 0.703, 50
#  500, 0.619, 0.503, 50
#  250, 0.594, 0.527, 50

In [ ]:
#2500, 0.62, 0.825
#3000, 0.60, 0.78 llama, llamaa, llama, llama
#3000, 062, 0.73, llama, llama, openAi, llama