# RAG Evaluation Test Set Generation

This example shows how to use the [Ragas](https://docs.ragas.io/en/stable/) (```v 0.1.22```) framework to generate a **test set** that can be used to evaluate the quality of a RAG pipeline. We then use the Python [LangChain](https://python.langchain.com/docs/introduction/) library to run some requests through this pipeline and we evaluate the quality of the results.

### <u>Requirements</u>
1. As you will accessing the LLMs and embedding models through Vector AI Engineering's Kaleidoscope Service (Vector Inference + Autoscaling), you will need to request a KScope API Key:

      Run the following command (replace ```<user_id>``` and ```<password>```) from **within the cluster** to obtain the API Key. The ```access_token``` in the output is your KScope API Key.
  ```bash
  curl -X POST -d "grant_type=password" -d "username=<user_id>" -d "password=<password>" https://kscope.vectorinstitute.ai/token
  ```
2. After obtaining the `.env` configurations, make sure to create the ```.kscope.env``` file in your home directory (```/h/<user_id>```) and set the following env variables:
- For local models through Kaleidoscope (KScope):
    ```bash
    export OPENAI_BASE_URL="https://kscope.vectorinstitute.ai/v1"
    export OPENAI_API_KEY=<kscope_api_key>
    ```
- For OpenAI models:
   ```bash
   export OPENAI_BASE_URL="https://api.openai.com/v1"
   export OPENAI_API_KEY=<openai_api_key>
   ```

## Set up the RAG workflow environment

#### Import libraries

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#!pip install pdfplumber

In [3]:
#import pdfplumber

In [4]:
import numpy as np
import os
import sys

from datasets import Dataset
from pathlib import Path

from langchain.chains import RetrievalQA
from langchain.document_loaders.pdf import PyPDFDirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_huggingface.embeddings import HuggingFaceEmbeddings
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

from ragas import evaluate
from ragas.metrics import Faithfulness, ContextPrecision, AnswerCorrectness
from ragas.testset import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context

In [5]:
cd ..

/fs01/home/ws_ikharchuk/rag_bootcamp_ik/rag_evaluation

#### Load config files

In [6]:
# Add root folder of the rag_bootcamp repo to PYTHONPATH
current_dir = Path().resolve()
parent_dir = current_dir.parent
sys.path.insert(0, str(parent_dir))

In [7]:
from utils.load_secrets import load_env_file
load_env_file()

#### Set up some helper functions

In [8]:
def pretty_print_docs(docs):
    print(
        f"\n{'-' * 100}\n".join(
            [f"Document {i+1}:\n\n" + d.page_content for i, d in enumerate(docs)]
        )
    )

#### Make sure other necessary items are in place

## Generate a sythentic test set

#### Start by loading in the documents we'll be using to augment our RAG generations

In [9]:
#load all documents

In [10]:

from langchain.document_loaders import TextLoader
from langchain.document_loaders import PyPDFLoader

In [11]:
%%time
directory_path = "/projects/RAG2/scotia-2/Datasets-Scotia-2/IBIS"
file_list = [
   '48412CA Long-Distance Freight Trucking in Canada Industry Report.pdf',
#'48422CA Local Specialized Freight Trucking in Canada Industry Report.pdf'
]  # Replace with your actual file names

# Load only the specified files
docs = []
for file_name in file_list:
    file_path = os.path.join (directory_path, file_name)
    loader = PyPDFLoader(file_path)
    docs.extend(loader.load())  # Append loaded pages to the list
print(f"Number of source documents: {len(docs)}")
for document in docs:
    document.metadata['file_name'] = document.metadata['source']

Number of source documents: 39
CPU times: user 1.45 s, sys: 58.3 ms, total: 1.5 s
Wall time: 1.53 s

In [12]:
%%time
# no need 
#Process PDFs
text_splitter = RecursiveCharacterTextSplitter(chunk_size=3000, chunk_overlap=32)
chunks = text_splitter.split_documents(docs)
print(f"Number of text chunks: {len(chunks)}")

Number of text chunks: 47
CPU times: user 7.81 ms, sys: 0 ns, total: 7.81 ms
Wall time: 7.67 ms

#### Now use OpenAI to generate a test set from the data in these documents (This takes about 2-3 minutes)

**IMP Note:** The LLM and embedding model used for test set generation should be more capable than the model being evaluated. Hence, we will use OpenAI GPT-4o and OpenAI embeddings for this purpose.

Store your OpenAI API key in ```~/.ragas_openai.env``` using the following format (this is in addition to ```~/.kscope.env```):

```bash
export RAGAS_OPENAI_BASE_URL="https://api.openai.com/v1"
export RAGAS_OPENAI_API_KEY=<openai_api_key>
```

In [13]:
# Select  LLM (Llama)

In [14]:
from utils.load_secrets import load_env_file_ragas
load_env_file_ragas()

In [15]:
GENERATOR_BASE_URL = os.environ.get("OPENAI_BASE_URL")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

In [16]:
GENERATOR_MODEL_NAME = "Meta-Llama-3.1-8B-Instruct"
#GENERATOR_MODEL_NAME = 'DeepSeek-R1-Distill-Qwen-1.5B'
EMBEDDING_MODEL_NAME = "BAAI/bge-base-en-v1.5"

In [17]:
# llm = ChatOpenAI(
#     model=GENERATOR_MODEL_NAME,
#     temperature=0,
#     max_tokens=None,
#     base_url=GENERATOR_BASE_URL,
#     api_key=OPENAI_API_KEY
# )

In [18]:
generator_llm = ChatOpenAI(
    model="gpt-4o-mini",
    base_url=os.environ["RAGAS_OPENAI_BASE_URL"],
    api_key=os.environ["RAGAS_OPENAI_API_KEY"],
)
generator_embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small",
    base_url=os.environ["RAGAS_OPENAI_BASE_URL"],
    api_key=os.environ["RAGAS_OPENAI_API_KEY"],
)

In [19]:
# model_kwargs = {'device': 'cuda', 'trust_remote_code': True}
# encode_kwargs = {'normalize_embeddings': True} # set True to compute cosine similarity

# print(f"Setting up the embeddings model...")
# embeddings = HuggingFaceEmbeddings(
#     model_name=   EMBEDDING_MODEL_NAME,
#     model_kwargs=model_kwargs,
#     encode_kwargs=encode_kwargs,
# )

In [20]:
def read_csv_from_directory(directory_path):
    dataframes= []
    for filename in os.listdir(directory_path):
        if filename.endswith('.csv'): 
            file_path = os.path.join(directory_path, filename)
            df = pd.read_csv(file_path)
            df["source"] = filename
            # print(df.head(1))
            dataframes.append(df)
    return pd.concat(dataframes, ignore_index=True)

In [21]:
#Load TRUCKING  data
file_paths = [#'/projects/RAG2/scotia-2/Datasets-Scotia-2/Agriculture_txt/agri_ca_co.csv', 
              '/projects/RAG2/scotia-2/Datasets-Scotia-2/Transport_txt/transport_CA.csv', 
              #'/projects/RAG2/scotia-2/Datasets-Scotia-2/Auto_txt/auto_ca.csv', 
             ]
def load_txt_file(file_path):
    # Create a TextLoader instance

    loader = TextLoader(file_path)

    # Load the document

    document = loader.load()
    chunks2 =text_splitter.split_documents(document)
    print(f"Number of text chunks: {len(chunks2)}")
    return chunks2, document

In [22]:
%%time
chunks =[]
for file_path in file_paths:
    chunks2, document_news = load_txt_file(file_path)
    chunks= chunks +chunks2

Number of text chunks: 403
CPU times: user 32 ms, sys: 4.55 ms, total: 36.6 ms
Wall time: 33.2 ms

In [23]:
len(document_news), len (docs)

(1, 39)

In [24]:
combined_docs = docs +document_news

In [41]:
len (combined_docs)

40

In [25]:
%%time
#generator_llm = (
#    model="DeepSeek-R1-Distill-Llama-8B",
#    base_url=os.environ["OPENAI_BASE_URL"],
#    api_key=os.environ["OPENAI_API_KEY"],
#)
# Define the RAG embeddings model (different than the OpenAI embedding model defined above for test set generation)
model_kwargs = {'device': 'cuda', 'trust_remote_code': True}
encode_kwargs = {'normalize_embeddings': True} # set True to compute cosine similarity
# print(f"Setting up the RAG LLM...")
llm = ChatOpenAI(
    #model="DeepSeek-R1-Distill-Llama-8B",
    model="Meta-Llama-3.1-8B-Instruct",
    temperature=0,
    max_tokens=256,
    base_url=os.environ["OPENAI_BASE_URL"],
    api_key=os.environ["OPENAI_API_KEY"],
)

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-base-en-v1.5",
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
)

CPU times: user 4.61 s, sys: 1.46 s, total: 6.07 s
Wall time: 6.89 s

In [67]:
#generator_llm.generate('what is  the day today?, Answer in no more then 10 words')

In [68]:
# %%time
# # Create generator with OpenAI model
# generator = TestsetGenerator.from_langchain(
#     generator_llm=generator_llm,
#     critic_llm=generator_llm,
#     embeddings=generator_embeddings,
# )

# # Generate the test set
# testset = generator.generate_with_langchain_docs(
#     documents=documents, 
#     test_size=1,
#     distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25},
# )

In [31]:
%%time
# Create generator with LLama model
generator = TestsetGenerator.from_langchain(
    #generator_llm=llm,
    generator_llm=generator_llm,
    #critic_llm=llm,
    critic_llm=generator_llm,
    #embeddings=embeddings,
    embeddings = generator_embeddings
)

# Generate the test set
testset = generator.generate_with_langchain_docs(
    documents=combined_docs, 
    test_size=50,
    distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25},
)

embedding nodes:   0%|          | 0/746 [00:00<?, ?it/s]

Filename and doc_id are the same for all nodes.

Generating:   0%|          | 0/50 [00:00<?, ?it/s]

CPU times: user 37.9 s, sys: 1.01 s, total: 39 s
Wall time: 5min 6s

#### Save dataset

In [32]:
testset2 = testset.to_pandas()

In [37]:
from collections import Counter

In [40]:
len (testset2.metadata[0])

1

In [33]:
testset2.tail(5)

,question,contexts,ground_truth,evolution_type,metadata,episode_done
45,What acquisitions did TFI make to boost its LT...,"[3.7%\n96.3%\n3.7 1,149.4 167.8 14.6 Compa...",TFI International made two significant acquisi...,multi_context,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True
46,What challenges does the Mayan Train project h...,[ by the next five years\nas trade finance oft...,Experts have warned that the Mayan Train has r...,multi_context,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True
47,What benefits do businesses see from integrate...,[Previous suppl y chain chal lenges ar e pr om...,Businesses see benefits from integrated supply...,multi_context,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True
48,What steps did the Bombers take for Indigenous...,[ people from across\nCanada to attend the Win...,"The Bombers, in line with EIC's model, partici...",multi_context,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True
49,What prompted Mayor Salinas's emergency declar...,[ late 2021 to help fund its\napproximately $3...,Mayor Salinas issued an emergency declaration ...,multi_context,[{'source': '/projects/RAG2/scotia-2/Datasets-...,True

In [42]:
import joblib

In [44]:


# Save (serialize) the object to a file
joblib.dump(testset, "../../Testing_Data/testset_combined.pkl")

['../../Testing_Data/testset_combined.pkl']

In [45]:
testset2.to_parquet ('../../Testing_Data/testset_combined.parquet')
testset2.to_csv ('../../Testing_Data/testset_combined.csv', index =False)

In [28]:
#load 
# Load (deserialize) the object from file
testset = joblib.load("../../Testing_Data/testset_combined.pkl")

## Now, start the RAG pipeline!

#### Choose the RAG LLM and embedding model
Note: This is different than the OpenAI LLM and embedding model defined above for test set generation.

In [46]:
RAG_LLM_MODEL_NAME = "Meta-Llama-3.1-8B-Instruct"
RAG_EMBEDDING_MODEL_NAME = "BAAI/bge-base-en-v1.5"

#### Generate answers for all the questions in our test set

Go through the embedding, storage and retrieval steps.

In [47]:
# Split the documents into smaller chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=3000, chunk_overlap=32)  ### Change Chunks here 
chunks = text_splitter.split_documents(combined_docs)
print(f"Number of text chunks: {len(chunks)}")

Number of text chunks: 450

In [48]:
# Define the RAG embeddings model (different than the OpenAI embedding model defined above for test set generation)
model_kwargs = {'device': 'cuda', 'trust_remote_code': True}
encode_kwargs = {'normalize_embeddings': True} # set True to compute cosine similarity

print(f"Setting up the RAG embeddings model...")
embeddings = HuggingFaceEmbeddings(
    model_name=RAG_EMBEDDING_MODEL_NAME,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs,
)
print (f"setting up {RAG_EMBEDDING_MODEL_NAME}")

Setting up the RAG embeddings model...
setting up BAAI/bge-base-en-v1.5

In [49]:
%%time
# Create the vector store and the retriever
vectorstore = FAISS.from_documents(chunks, #embeddings
                                  generator_embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

In [52]:
RAG_LLM_MODEL_NAME

'Meta-Llama-3.1-8B-Instruct'

In [38]:
%%time
# Define the RAG LLM (different than the OpenAI LLM defined above for test set generation)
print(f"Setting up the RAG LLM...")
llm = ChatOpenAI(
    model=RAG_LLM_MODEL_NAME,
    temperature=0,
    max_tokens=256,
    base_url=os.environ["OPENAI_BASE_URL"],
    api_key=os.environ["OPENAI_API_KEY"],
)
print (f"setting up {RAG_LLM_MODEL_NAME}")

Setting up the RAG LLM...
setting up Meta-Llama-3.1-8B-Instruct
CPU times: user 21 ms, sys: 4.14 ms, total: 25.1 ms
Wall time: 23.8 ms

Iterate over the questions in our synthetic testset, and run them each through the RAG pipeline to see what answers get returned. (This also takes 2-3 minutes)

In [53]:
# answer Questions

In [54]:
%%time
#USe OpenAi

dataset = testset.to_dataset()
answers = np.empty(len(dataset), dtype=object)

for index, row in enumerate(dataset):
    query = row["question"]
    
    # Run the query through the RAG pipeline
    rag_pipeline = RetrievalQA.from_llm(
        llm=generator_llm,
        retriever=retriever
    )
    answer = rag_pipeline.invoke(input=query)
    answer = answer["result"]
    print(f"Result {index}\nQuestion: {query}\nAnswer: {answer}\n")
    
    # Store the result
    answers[index] = answer

Result 0
Question: What percentage of structural damage is being reported in Jasper due to the wildfires?
Answer: Authorities have estimated that there is potentially 30% to 50% structural damage in Jasper due to the wildfires.

Result 1
Question: What is the expected growth range for adjusted diluted earnings per share according to CN's latest forecast?
Answer: I don't know.

Result 2
Question: What is the expected revenue growth for long-distance freight trucking services through the end of 2024?
Answer: The expected revenue growth for long-distance freight trucking services through the end of 2024 is a compound annual growth rate (CAGR) of 1.0%, reaching $31.3 billion.

Result 3
Question: What are the potential economic impacts of a labor stoppage at Canada's two largest railroad operators?
Answer: A labor stoppage at Canada's two largest railroad operators, Canadian National Railway and Canadian Pacific Kansas City, could have significant economic impacts. According to estimates, the simultaneous stoppage could cost the Canadian economy approximately C$341 million (about $251.14 million) per day.

Key sectors that would be affected include:

1. **Fertilizers**: Fertilizers account for a major portion of the commodities shipped by Canadian railways, with about 75% of all fertilizer produced and used in Canada moved by rail. The fertilizer industry could see lost sales revenue estimated between C$55 million and C$63 million per day due to disruptions.

2. **Agriculture**: The stoppage would hinder the transport of agricultural products, including grains and potash, which are critical for farming operations.

3. **Trucking**: While trucking can absorb some increased demand, it cannot completely replace the long-haul rail distribution for bulk commodities. This could result in higher costs and longer lead times for truckload shippers.

4. **Broader Supply Chain Disruptions**: Many industries, including mining and manufacturing, rely on rail transport for their supply chains. A stoppage would lead to crippling supply-chain delays, increased costs, cash-flow constraints, and potential shutdowns in affected sectors.

Overall, the labor stoppage could inflict billions of dollars' worth of economic damage across Canada and have a ripple effect throughout North America, given the interconnected nature of the rail networks.

Result 4
Question: What is the purpose of the conciliation process in labor negotiations?
Answer: I don't know.

Result 5
Question: What strategies do successful businesses use to overcome volatility in the freight trucking industry?
Answer: Successful businesses in the freight trucking industry use the following strategies to overcome volatility:

1. **Establish long-term working relationships with raw material suppliers**: Building strong ties with suppliers ensures a reliable flow of materials and components, reducing the impact of market disruptions and price spikes.

2. **Optimize operating capacity**: Efficiently managing and utilizing fleet resources allows trucking companies to adapt to fluctuating demand, ensuring cost-effective operations and maintaining competitiveness during periods of volatility.

3. **Offer competitively priced products**: Competitive pricing is essential to attract more clientele while maintaining profitability, especially in a market where cost efficiency is a critical factor for customers choosing service providers.

4. **Adopt a high-volume, low-margin strategy**: Moving large volumes of goods at competitive rates can drive success by capturing market share and optimizing route efficiency, thereby maximizing overall profitability.

5. **Diversify the customer base**: Serving a wide variety of clients lowers dependency on a single market segment, reducing the influence of any single buyer and ensuring stable revenue streams.

6. **Develop a strong market profile**: Establishing a strong market presence enhances brand recognition and customer loyalty, reducing buyer power and making the service a preferred choice amid competitive offers.

These strategies help mitigate the risks associated with volatility in the industry.

Result 6
Question: What factors contributed to the increase in FedEx shares on June 26?
Answer: The increase in FedEx shares on June 26 was primarily attributed to the company reassuring investors with a bullish annual profit forecast, projecting fiscal 2025 earnings of $20 to $22 per share, which was slightly above analysts' estimates. Additionally, FedEx indicated that it was considering selling or spinning off its freight trucking business, which one analyst valued at $30 billion. This positive outlook and strategic review of the Freight business contributed to the surge in share prices, with shares jumping as much as 15% during the day.

Result 7
Question: What is the significance of Westshore's potash project in relation to its business diversification and environmental commitments?
Answer: Westshore's potash project is significant for its business diversification as it represents a transformational shift into the agriculture sector, expanding beyond its traditional focus on coal handling. This diversification is part of a multi-billion investment and is expected to enhance Westshore's long-term business sustainability by tapping into the growing demand for potash, a critical ingredient in fertilizer required for global agriculture.

In terms of environmental commitments, the potash project aligns with Westshore's efforts to reduce its impact on the environment. By expanding its operations to include potash, Westshore aims to enhance its environmental stewardship and support agricultural practices that are essential for feeding a growing population, while also recognizing the need for greater use of renewable energy resources. Overall, the potash project not only diversifies Westshore's business portfolio but also reinforces its commitment to environmental responsibility.

Result 8
Question: What is the purpose of the National Safety Code in the freight trucking industry?
Answer: The National Safety Code encourages trucking safety, promotes efficiency, and establishes consistent safety standards across the provinces and territories. It covers safety and administrative regulations for single-driver licenses, knowledge and performance tests, driver examiner training, self-certification, and on-road inspections.

Result 9
Question: What impact did the floods have on Halifax and its infrastructure?
Answer: The floods in Halifax, Nova Scotia had a significant impact on the infrastructure and the region. They washed away roads, swamped buildings, and damaged bridges. Specifically, a section of the Canadian National Railway track used to access Halifax, which is Canada's fourth-largest port, was extensively damaged. Although Canadian National Railway has restored much of the damaged infrastructure, some repairs will be delayed until the floodwaters recede. The floods also disrupted transportation, with many roads remaining closed and 19 bridges damaged, six of which were completely destroyed. The overall damage was described as unimaginable, with the cost likely to be in the "hundreds of millions" of dollars.

Result 10
Question: What recent actions has Mexico taken regarding fuel and petrochemical imports to combat smuggling?
Answer: Mexico has recently imposed fresh restrictions on imports of dozens of refined petroleum and petrochemical products to curb fuel theft and adulteration. This includes certain types of gasoline, diesel, jet fuel, and additives like MTBE (methyl tert-butyl ether). As a result, the rail company Canadian Pacific Kansas City (CPKC) has temporarily held back rail cars containing fuel and petrochemicals bound from Texas to Mexico until companies can present the necessary import permits. The measures aim to prevent the adulteration and trade of fuels that could pose health and environmental risks.

Result 11
Question: What is TFI International's market capitalization as of FY 2023?
Answer: TFI International's market capitalization as of FY 2023 is less than $12 billion.

Result 12
Question: What factors contributed to the decline of the Toronto Stock Exchange?
Answer: The decline of the Toronto Stock Exchange was attributed to several factors, including:

1. **Profit Taking**: Investors engaged in profit-taking after high-flying technology shares had performed well in the past weeks, leading to declines in those stocks.

2. **Disappointing Earnings**: Major companies, such as Tesla and Alphabet, reported lackluster earnings, raising concerns about the sustainability of the recent equity rally driven by Big Tech and AI.

3. **Interest Rate Cuts**: While the Bank of Canada cut its key interest rate, providing some support, the overall market sentiment was still affected by the performance of technology and financial sectors.

4. **Sector Performance**: The technology sector experienced a notable decline, along with heavily weighted financials and industrials, which also contributed to the overall decrease in the index.

5. **Economic Indicators**: Broader economic indicators, such as rising long-term borrowing costs and disappointing retail sales data, indicated a slowdown in the domestic economy, further impacting investor confidence.

6. **Market Conditions**: The overall market conditions, including investor caution ahead of upcoming economic data and central bank meetings, contributed to the downward trend in the index.

Result 13
Question: What accounting principles does CPKC follow for preparing financial information?
Answer: CPKC prepares financial information in accordance with accounting principles generally accepted in the United States of America (U.S. GAAP), unless otherwise noted.

Result 14
Question: What decision is the U.S. Federal Reserve expected to make regarding interest rates?
Answer: The U.S. Federal Reserve is expected to leave interest rates unchanged during its upcoming monetary policy decision.

Result 15
Question: What are the environmental benefits associated with the rail network's operations?
Answer: The environmental benefits associated with the rail network's operations include:

1. **Reduced Emissions**: CN has reduced locomotive emissions intensity by 45% since 1993, which contributes to lower greenhouse gas emissions.

2. **Fuel Efficiency**: The rail network consumes approximately 15% less fuel per gross ton mile than the industry average, indicating a more efficient use of energy resources.

3. **Sustainable Growth**: The ongoing investments in network upgrades and modernization programs are designed to enhance productivity and capacity improvements while supporting long-term sustainability.

4. **Decoupling Carbon Emissions from Growth**: The strategy aims to continue growth while reducing carbon emissions, thereby minimizing the environmental impact as operations expand.

These efforts collectively contribute to a more environmentally friendly transportation option compared to other modes of freight transport.

Result 16
Question: What action is the Teamsters Canada Rail Conference planning to take in response to the decision that ended the railway work stoppage?
Answer: The Teamsters Canada Rail Conference is planning to mount a legal challenge to the decision that ended the railway work stoppage and imposed arbitration. They have stated that they will appeal the decision in federal court.

Result 17
Question: What is the significance of foreign investment in Mexico's regulatory framework?
Answer: The significance of foreign investment in Mexico's regulatory framework lies in its potential to stimulate economic growth, enhance trade, and create jobs. A stable regulatory framework is crucial for attracting foreign investment, as it provides investors with the confidence that their investments will be protected and that there will be consistent rules governing business operations.

In the context of recent developments, Scotiabank's strategy to focus on the Mexican market aims to leverage the growing North American trade and the opportunities presented by nearshoring. However, there are concerns about the political and economic risks associated with foreign investment in Mexico, especially given the challenges that foreign banks have faced in the country.

A stable regulatory environment can help mitigate these risks and promote a more favorable atmosphere for foreign investors, which is essential for maximizing the benefits of foreign capital inflows and fostering sustainable economic development in Mexico.

Result 18
Question: What is the current status of paid sick leave for U.S. rail workers?
Answer: As of September 2023, the percentage of U.S. rail workers who are guaranteed paid sick leave has risen from 5% to 90% since the end of 2022. However, there are still about 10,000 employees who do not have the benefit. The Biden administration has called on major freight railroads to guarantee paid sick leave for all workers.

Result 19
Question: What are acquisition-related costs and how do they impact CPKC's financial results?
Answer: Acquisition-related costs refer to the expenses incurred by CPKC during the process of acquiring another company, in this case, KCS. These costs can include a variety of expenditures such as legal fees, consulting fees, financing fees, integration costs (including third-party services and system migration), community investments, and costs associated with debt exchange transactions. Additionally, they may encompass fair value gains or losses on foreign exchange forward contracts, restructuring costs, employee retention costs, and transaction and integration costs recognized within equity earnings of KCS.

These acquisition-related costs can significantly impact CPKC's financial results by affecting the company's diluted earnings per share (EPS). While these costs are recognized as expenses, they may be excluded from CPKC's Core adjusted combined diluted EPS, which is a non-GAAP measure. This exclusion is due to the unpredictable nature and potential non-recurring nature of such costs, especially given the complexity and magnitude of the acquisition. Consequently, these costs can create fluctuations in reported financial performance, making it challenging to reconcile forward-looking non-GAAP measures to the most comparable U.S. GAAP measures.

Result 20
Question: What processes are involved in the surface water collection at Westshore?
Answer: The surface water collection at Westshore involves the following processes:

1. Collection of all rainwater and surface runoff through a series of ditches and sumps.
2. Treatment of the collected water through a settlement process to remove coal particles and other solids.
3. Use of a water treatment system with sieve bins to further treat the water and remove coal particles.
4. Discharge of treated surface runoff water through an ocean discharge system, which employs coagulation and flocculation to remove particulates and meet discharge permit criteria for Total Suspended Solids (TSS) and oil and grease levels.
5. Continuous monitoring of the treated water with electronic instrumentation, along with weekly water sampling for analysis and record keeping.

Result 21
Question: What companies acquired by TFI International provide truckload services?
Answer: The companies acquired by TFI International that provide truckload services include Daseke, Inc. and Dahlsten Truck Line.

Result 22
Question: What recent event affected the operations of Canadian National Railway in Nova Scotia?
Answer: Recent torrential rainfall in Nova Scotia caused devastating floods, which affected the operations of Canadian National Railway. The floods washed away roads, damaged bridges, and caused extensive damage to a section of CN Rail track used for freight trains heading to the Port of Halifax. As a result, CN Rail had to shut down the line temporarily.

Result 23
Question: What are the potential economic impacts of the looming labor dispute at Canada's main railroads?
Answer: The potential economic impacts of the looming labor dispute at Canada's main railroads include:

1. **Significant Financial Losses**: The simultaneous labor stoppage could cost the Canadian economy approximately C$341 million per day, which is more than 4% of the nation's GDP.

2. **Disruptions Across Industries**: Various industries, including fertilizers, coal, and automotive, rely heavily on rail transport. Disruptions could lead to estimated losses of C$55 million to C$63 million per day for the fertilizer industry alone, along with significant impacts on other sectors that depend on timely shipments.

3. **Increased Costs and Delays**: As companies may shift their transport needs to trucking due to rail disruptions, they could face higher costs and longer lead times. This shift could also strain the trucking industry, which may not be able to fully absorb the increased demand, especially for bulk commodities.

4. **Impact on Agriculture**: The agricultural sector could be severely affected, as grain handling facilities may fill to capacity within 7-10 days, halting farmers' cash flow until rail services resume.

5. **Wider North American Effects**: Since both Canadian National Railway and Canadian Pacific Kansas City have networks extending into the U.S. and Mexico, disruptions could affect supply chains across North America, impacting facilities that rely on Canadian goods.

Overall, the labor dispute could have widespread and severe implications for the economy, affecting a range of sectors and potentially leading to layoffs and operational challenges for businesses dependent on rail transport.

Result 24
Question: What role do technology improvements play in enhancing the safety and efficiency of freight trucking?
Answer: Technology improvements play a significant role in enhancing the safety and efficiency of freight trucking in several ways:

1. **Safety Measures**: Technology has introduced various safety features aimed at ensuring that vehicles maintain safe operation. For example, advancements help prevent vehicles from veering off the road, accelerating too quickly, or traveling down steep grades at excessive speeds.

2. **Data Collection and Analytics**: Companies are increasingly using technology to collect data on driving patterns, which can help identify risky behaviors and prevent potential accidents. This data-driven approach allows for better monitoring of drivers' day-to-day activities, leading to safer operations.

3. **Vehicle Upgrades**: The adoption of newer technologies, including sensors and advanced driving assistance systems, enhances vehicle performance and safety. These upgrades can lead to reduced accident rates and improved cargo delivery reliability.

4. **Route Optimization**: Technologies such as the Internet of Things (IoT) and artificial intelligence (AI) help optimize route planning, making transport more efficient. This optimizes fuel usage and reduces delivery times, further enhancing operational efficiency.

5. **Autonomous and Semi-Autonomous Vehicles**: While still in developmental stages, these technologies have the potential to mitigate labor shortages and enhance safety by reducing human error in driving.

Overall, technology improvements are integral to increasing the safety and efficiency of freight trucking, enabling companies to operate more effectively and reduce risks on the road.

Result 25
Question: What led to Canada's stock index peak alongside rising gold prices?
Answer: Canada's stock index peaked alongside rising gold prices due to gains in the materials sector, specifically from gold miners and uranium producers. The increase in gold prices, which reached record highs, contributed to the positive sentiment in the market. Additionally, the overall investor sentiment was boosted by recent advances in the market and positive domestic economic data, such as an increase in retail sales. This combination of factors helped lift the Toronto Stock Exchange's S&P/TSX composite index to its highest levels.

Result 26
Question: What support might help Canada with back-to-work laws during labor disputes?
Answer: The federal government could seek to pass back-to-work legislation to end labor disputes, but it would need the support of at least one other party in the parliament since it does not control a majority of seats. In the past, such legislation has been used to force workers to return to their jobs during strikes, as seen with the previous Conservative government in 2012. Additionally, the Labour Minister has the power to request binding arbitration to resolve disputes, as was done in recent cases involving rail workers. Support from other political parties, especially those with strong ties to labor, could also be crucial in navigating these disputes effectively.

Result 27
Question: How did UPS's freight sales affect its valuation?
Answer: UPS's freight sales negatively impacted its valuation. The company sold its freight business to TFI International for $800 million in 2021 before the trucking market downturn. This week, UPS also announced the sale of its Coyote freight brokerage for just over $1 billion, which was nearly $800,000 less than it paid to acquire the business about a decade ago. Such sales, especially at lower valuations, can lead to a decrease in overall company valuation and suggest a challenging market environment for freight services.

Result 28
Question: What training do EIC volunteers get for Indigenous attendees?
Answer: EIC volunteers complete Indigenous sensitivity training as recommended by their Indigenous partners.

Result 29
Question: What agri-products might see shipment delays if Canadian railways stop?
Answer: Shipment delays could affect several agricultural products, including:

1. **Grains**: As much as 94% of grain is shipped by rail in Canada, and a stoppage would impact the movement of U.S. spring wheat from Minnesota, North Dakota, and South Dakota to the Pacific Northwest for export.

2. **Fertilizers**: The railways move an average of 69,000 tons of fertilizer products per day, and disruptions would significantly impact the supply chain for fertilizers used by U.S. corn farmers.

3. **Meat**: Canadian meat producers warned of millions of dollars in losses and waste, with some processing plants expecting to lose up to C$3 million a week.

4. **Soybeans**: There are concerns that the movement of Ontario soybeans to export markets, primarily Japan, could stop just before the harvest.

Overall, a rail stoppage would have severe implications for bulk commodity exporters in both Canada and the United States, affecting their ability to transport these essential agricultural products.

Result 30
Question: What signals from the Fed might sway investor interest rates?
Answer: Signals from the Fed that might sway investor interest rates include announcements regarding changes to the benchmark interest rate, guidance on future monetary policy, insights into economic conditions influencing their decisions, and any indications of concerns regarding inflation or economic growth. Specifically, if the Fed suggests that rates will remain high for an extended period or signals a potential rate cut, it can significantly impact investor sentiment and interest rates in the market. Additionally, upcoming economic data releases, such as inflation reports or GDP growth, can also influence the Fed's decisions and, consequently, investor expectations regarding interest rates.

Result 31
Question: What makes the N.A. rail network connect 3 countries well?
Answer: The North American rail network connects the three countries—Canada, the United States, and Mexico—effectively due to several key factors:

1. **Dominant Rail Operators**: Canadian National Railway (CN) and Canadian Pacific Kansas City (CPKC) are the two main freight rail operators in Canada, together holding a duopoly. They operate extensive coast-to-coast rail networks that facilitate transit across the continent.

2. **Interline Partnerships**: Both CN and CPKC have established interline partnerships with other Class I railroads in the U.S. and Mexico, which allows for seamless transfers of cargo between different rail networks.

3. **Strategic Locations**: The rail networks are strategically located to serve major trade corridors and ports across North America. This includes connections to key intermodal ports like those in Vancouver and Montreal, which are essential for international trade.

4. **Comprehensive Coverage**: The rail network covers significant regions, from the Western and Eastern Canadian fiber-rich producing areas to the Midwest and Southern U.S. corridors. This broad coverage enables efficient transport of goods across long distances.

5. **Integration with Other Transport Modes**: The railroads are integrated with other transportation modes, such as trucking and shipping, enhancing the overall logistics capabilities and allowing for efficient movement of goods.

These elements work together to create a robust rail network that supports trade and commerce across Canada, the U.S., and Mexico.

Result 32
Question: What acquisitions did TFI make for LTL growth?
Answer: TFI International made several acquisitions for LTL growth, including:

1. Siemens Transportation Group (STG) on July 13, 2023, which provides LTL, truckload, and flatbed services throughout North America.
2. JHT Holdings, Inc. on August 16, 2023, which is an asset-light logistics and transportation provider for Class 6-8 truck manufacturers.

These acquisitions were aimed at enhancing TFI's presence and capabilities in the LTL segment.

Result 33
Question: What position will Jim Vena take at Union Pacific post-Lance Fritz?
Answer: Jim Vena will take the position of CEO at Union Pacific, replacing Lance Fritz. He will assume the role on August 14.

Result 34
Question: What might the FedEx freight sale mean?
Answer: The potential sale or spin-off of FedEx's freight trucking business could have several implications:

1. **Increased Valuation**: Analysts have valued the FedEx Freight business at around $30 billion. If it is sold or operates as a standalone company, it may lead to a significant re-rating of its valuation, potentially increasing the overall market value for FedEx.

2. **Focus on Core Operations**: By divesting the freight business, FedEx could concentrate on its more profitable segments and streamline operations, which may enhance profitability.

3. **Market Dynamics**: The sale could impact competition within the logistics and freight industry, especially in light of Yellow Corp's recent operational shutdown, which has led to expectations of higher rates in the trucking sector.

4. **Investor Confidence**: FedEx's bullish annual profit forecast and the review of its Freight business may reassure investors about the company’s strategic direction and profitability, potentially leading to a further increase in share prices.

5. **Operational Efficiency**: The restructuring efforts that include a review of the freight business may lead to improved operational efficiency and cost management, benefiting the company in the longer term.

Overall, the decision regarding the FedEx Freight business could shape the company's future strategy, financial health, and its competitive position in the logistics market.

Result 35
Question: What hints at stable oil exports from Canada to the U.S. amid a labor dispute?
Answer: The context suggests several reasons that hint at stable oil exports from Canada to the U.S. amid a labor dispute:

1. **Excess Pipeline Capacity**: The expansion of the Trans Mountain pipeline and excess capacity on other pipelines are expected to limit the impact of any labor dispute on oil exports. Trans Mountain's expansion nearly tripled the flow of crude from Alberta to the Pacific coast, increasing capacity significantly.

2. **Declining Rail Imports**: U.S. rail imports of Canadian crude have fallen sharply in recent years, averaging around 55,000 barrels per day in May, which is the lowest since the pandemic price crash in 2020. The majority of crude oil is transported by pipeline, with Canada exporting about 4.2 million barrels per day to the U.S.

3. **Market Conditions**: Prices of Western Canadian Select crude typically fall during export logjams, but experts believe that the available capacity on pipelines should limit deep discounting, indicating a stable market for Canadian crude.

4. **Alternative Arrangements**: Companies receiving crude by rail are reportedly looking for alternatives, such as substituting with pipeline grades or different buyers, which suggests a proactive approach to maintaining supply despite potential disruptions.

5. **Limited Impact on Major Producers**: Companies like Cenovus Energy and ConocoPhillips have stated they are closely monitoring the situation and have plans in place to mitigate impacts, indicating they do not expect significant disruptions to their operations.

Overall, these factors point towards a resilient oil export market despite the looming labor dispute.

Result 36
Question: Which sectors benefited from earnings and rate outlook?
Answer: The sectors that benefited from earnings and the outlook for lower interest rates included technology and railroad shares. Specifically, gains in technology stocks were noted, and railroad stocks also performed well as investors anticipated a positive impact from expected rate cuts.

Result 37
Question: What are the Teamsters' main goals in wage talks with CN Rail, considering a possible work stoppage's economic impact?
Answer: I don't know.

Result 38
Question: What impact might CN's move to Hinton have on local jobs and the town's economy post-wildfires?
Answer: CN's move to Hinton is expected to have a significant negative impact on local jobs and the town's economy in Jasper. The relocation will directly affect around 200 union workers currently living in Jasper, which could lead to job losses in the area. Rail is one of the largest industries in Jasper, second only to tourism, and the shift of operations to Hinton will further cripple the already struggling community, which has been devastated by recent wildfires. The loss of these jobs and the decline in rail operations could exacerbate the economic challenges faced by Jasper, especially as it attempts to recover from the destruction caused by the wildfires.

Result 39
Question: How do transport modes and economy affect trade efficiency in N.A.?
Answer: I don't know.

Result 40
Question: What impact does the new CPKC-CSX rail corridor have on grain transport efficiency and Canadian rail labor talks?
Answer: I don't know.

Result 41
Question: What's the reasoning behind CPKC's Non-GAAP measures in financial reporting, and how do they improve earnings and liquidity assessment vs. U.S. GAAP?
Answer: CPKC presents Non-GAAP measures to provide an additional basis for evaluating underlying earnings and liquidity trends in its current financial results, which can be compared with prior periods' results. Management believes that these measures facilitate a multi-period assessment of long-term profitability and help in assessing future profitability.

The reasoning behind using Non-GAAP measures is that they allow for a more nuanced understanding of the company's financial performance beyond what is reported under U.S. GAAP. While U.S. GAAP provides standardized financial statements, Non-GAAP measures may highlight specific aspects of performance that management considers important for assessing the company's operational health, such as core adjusted operating income or free cash flow.

However, it's important to note that these Non-GAAP measures have no standardized meaning and are not defined by U.S. GAAP, which means they may not be comparable to similar measures presented by other companies. Additionally, the presentation of Non-GAAP measures is not intended to be seen in isolation or as superior to the financial information provided under U.S. GAAP.

Result 42
Question: What factors shape competition in long-distance trucking?
Answer: Several factors shape competition in long-distance trucking:

1. **Barriers to Entry**: The long-distance freight trucking industry has low barriers to entry, allowing individuals to easily start a business with minimal capital requirements. This fosters competition as more players can enter the market.

2. **Market Power of Large Companies**: Large freight trucking companies have significant market power by securing major contracts and offering a diverse range of services. Their ability to outsource contracts during high-demand periods helps maintain their dominance.

3. **In-House Transportation Services**: Companies are increasingly developing in-house transportation services to reduce outsourcing costs, which pressures third-party distribution providers.

4. **Economies of Scale**: Rail transportation benefits from economies of scale, allowing it to transport large cargo volumes at lower costs compared to trucking over long distances. This makes rail a preferred option for bulky shipments, impacting truckers' competitiveness.

5. **Fuel Prices**: Volatile diesel prices affect pricing strategies and the competitiveness of trucking against rail distribution. Rising fuel prices pressure truckers, while a decline in diesel prices can enhance profitability and competitive pricing.

6. **Labor Shortages**: The industry faces labor shortages as an aging workforce retires and younger workers seek alternative careers. Companies must offer competitive compensation to attract and retain drivers.

7. **Technological Advancements**: Investment in technology, including vehicle upgrades and digitalization, is critical for improving efficiency and safety, impacting competitive dynamics.

8. **Consumer Preferences**: An increasing preference among customers to outsource logistics operations encourages competition and can lead to further consolidation among large carriers.

These factors collectively contribute to a highly competitive environment within the long-distance trucking sector.

Result 43
Question: What impacts do forward-looking statements in TFI's outlook have, and what external factors affect their reliability?
Answer: Forward-looking statements in TFI's outlook reflect management's current expectations regarding future results, performance, and achievements. However, these statements are inherently subject to significant business, economic, and competitive uncertainties and contingencies.

External factors that affect the reliability of these forward-looking statements include:

1. Economic and geopolitical conditions.
2. Competition in the market.
3. Access to capital and market trends.
4. Changes in government regulations and funding, especially for sectors like health care.
5. Operational performance and growth metrics.
6. Environmental, social, and governance factors.
7. Risks associated with acquisitions and reliance on key customers.
8. Fluctuations in sales prices and purchase prices of assets.
9. Interest rates and foreign exchange rates.
10. General economic conditions affecting TFI and its customers.

These factors could cause actual results to differ materially from those expressed in forward-looking statements. Therefore, readers are cautioned not to place undue reliance on such statements, as they only reflect the expectations at the time they were made.

Result 44
Question: What are Westshore's key focuses for environmental and governance efforts?
Answer: Westshore's key focuses for environmental and governance efforts include:

1. **Minimizing Environmental Impact**: Westshore aims to minimize the impact of its operations on the natural environment, ensuring that it operates responsibly and protects the environment for future generations.

2. **Dust Reduction Activities**: The company engages in ongoing dust reduction activities, such as using spray towers, water trucks, and anti-dust agents, and carefully monitoring weather conditions.

3. **Air Quality Compliance**: Westshore monitors compliance with air emissions permits and consistently meets British Columbia air quality guidelines.

4. **Greenhouse Gas Emissions Reduction**: Westshore has made efforts to reduce GHG emissions, notably by replacing old equipment with more efficient models.

5. **Water Management**: Westshore collects and treats rainwater, surface runoff, and wastewater to meet regulatory standards and minimize environmental impact.

6. **Noise Reduction**: The company implements measures to reduce noise from terminal activities, including upgrading equipment and using quieter materials.

7. **Transparency and Accountability**: Westshore is committed to transparent governance structures and being accountable to shareholders.

8. **Continuous Improvement**: The company seeks opportunities to progress and improve its environmental performance, as demonstrated by its annual ESG reporting.

These focuses reflect Westshore's commitment to responsible operations and environmental stewardship.

Result 45
Question: What acquisitions did TFI make to boost its LTL capacity in North America?
Answer: TFI International expanded its LTL capacity in North America by acquiring UPS Freight, which provided access to an established network and customer base. Additionally, in 2024, TFI strengthened its trucking business by acquiring Daseke for $1.1 billion, which added 2,430 tractors and 6,820 trailers to its fleet, further supporting its LTL business.

Result 46
Question: What challenges does the Mayan Train project have with budget and the new Inter-Oceanic Train?
Answer: The Mayan Train project has faced significant challenges, particularly regarding its budget. Experts have warned that the project has run nearly four times over budget and is still far from being completed.

As for the Inter-Oceanic Train, it is part of a broader government initiative aimed at boosting investment in Mexico's poorer southern regions. While it has been pitched as a potential rival to the Panama Canal, analysts estimate that it will only be able to ship a fraction of what the canal can move. Additionally, earlier this year, there were complications when Mexican authorities seized parts of a rail line operated by Grupo Mexico for the Inter-Oceanic Train, although a deal was later reached between the two parties.

Result 47
Question: What benefits do businesses see from integrated supply chain solutions, especially with LTL in global distribution?
Answer: Businesses see several benefits from integrated supply chain solutions, particularly with less-than-truckload (LTL) services in global distribution, including:

1. **Cost Savings**: By contracting long-distance LTL services, businesses can save on transportation costs as they can consolidate shipments from multiple customers, reducing operational expenses.

2. **Increased Efficiency**: Integrated solutions allow for better coordination and planning of shipments, utilizing existing infrastructure like rail systems to enhance distribution efficiency.

3. **Flexibility in Operations**: LTL services support shipment consolidation, enabling businesses to manage smaller loads more effectively and cater to varying demand without the need for dedicated full truckloads.

4. **Competitive Advantage**: Utilizing LTL services enables businesses to remain competitive in the e-commerce marketplace by meeting domestic demand for goods sourced from global markets.

5. **Technology Integration**: Investments in technology, such as GPS and order-management systems, enhance the tracking and management of shipments, leading to improved service levels and customer satisfaction.

6. **Adaptability to Market Changes**: Integrated supply chain solutions allow businesses to quickly adapt to changes in demand, especially as e-commerce continues to grow, facilitating timely delivery and order fulfillment.

Overall, these benefits contribute to a more streamlined and responsive supply chain, essential for businesses competing in today’s fast-paced market environment.

Result 48
Question: What steps did the Bombers take for Indigenous reconciliation in line with EIC's model?
Answer: The Winnipeg Blue Bombers, in collaboration with EIC, took several steps for Indigenous reconciliation, particularly through the event held on September 29, 2023. They invited over 1,000 Indigenous people from across Canada to attend a Canadian Football League game, bringing attention to the need for reconciliation with Indigenous peoples. This initiative included collaboration with more than 100 Indigenous communities and four Indigenous governing bodies.

The event provided an opportunity for Indigenous attendees, many from remote communities who had never experienced such a large gathering, to engage in a communal celebration. EIC covered the costs of transportation, lodging, and incidentals for the participants, and provided them with orange gear to wear to the game.

Additionally, EIC's commitment to Truth and Reconciliation included its employees completing Indigenous sensitivity training as recommended by Indigenous partners, reinforcing the importance of understanding and respecting Indigenous cultures. This annual event has been expanded in subsequent years, illustrating a sustained effort towards reconciliation and community engagement.

Result 49
Question: What prompted Mayor Salinas's emergency declaration regarding the migrant surge and its impact on border traffic?
Answer: Mayor Rolando Salinas issued an emergency declaration due to a "severe undocumented immigrant surge," which was prompted by an influx of migrants from Mexico riding on rail cars to cross into Eagle Pass, Texas. This situation led to the temporary closure of the Eagle Pass border crossing, affecting train traffic and limiting the flow of goods into the country.

CPU times: user 2.01 s, sys: 77 ms, total: 2.08 s
Wall time: 1min 36s

In [36]:
%%time
#Use LLama
dataset = testset.to_dataset()
answers = np.empty(len(dataset), dtype=object)

for index, row in enumerate(dataset):
    query = row["question"]
    
    # Run the query through the RAG pipeline
    rag_pipeline = RetrievalQA.from_llm(
        llm=llm,
        retriever=retriever
    )
    answer = rag_pipeline.invoke(input=query)
    answer = answer["result"]
    print(f"Result {index}\nQuestion: {query}\nAnswer: {answer}\n")
    
    # Store the result
    answers[index] = answer

Result 0
Question: Here is a question that can be fully answered from the given context:

"What drives the demand for dry bulk transportation in the local specialized freight trucking industry in Canada?"

This question can be answered by referencing the context, which states that "Dry bulk transportation swells alongside construction activity" and that "Strong construction activity has supported this segment but is expected to trend downward through the end of 2024 as tightened monetary policy pressures businesses' financing ability.
Answer: According to the context, the demand for dry bulk transportation in the local specialized freight trucking industry in Canada is driven by construction activity. Specifically, it is stated that "Dry bulk transport is the largest market for specialized trucks" and that "A strong expansion in mining and high demand from the construction sector fueled market growth."

Result 1
Question: Here is a question that can be fully answered from the given context:

"What are the expected outcomes of the government's pro-immigration policies on the driver shortage and turnover in the long-distance specialized freight trucking industry in Canada?
Answer: The expected outcomes of the government's pro-immigration policies on the driver shortage and turnover in the long-distance specialized freight trucking industry in Canada are to alleviate pressure from high driver turnover. The policies, such as the Express Entry initiative, aim to quickly bring in new truckers to replace retiring employees and those not keen on the trucker lifestyle, thereby addressing the ongoing issues with worker retention and incentivizing more skilled drivers to stay in the industry.

Result 2
Question: Here is a question that can be fully answered from the given context:

"What is the expected impact of the rebound in economic growth on the demand for freight transportation services in Canada?
Answer: The expected impact of the rebound in economic growth on the demand for freight transportation services in Canada is that it will boost demand for freight transportation services, driven by increased consumer spending and construction investments.

Result 3
Question: Here is a question that can be fully answered from the given context using the topic "E-commerce growth":

question: "What is driving the growth of e-commerce in the long-distance freight trucking industry in Canada?
Answer: The growth of e-commerce is driving the expansion of the Less-than-truckload (LTL) segment in the long-distance freight trucking industry in Canada. This is because smaller establishments are benefiting from cheaper shipments, and trucking companies are expanding their value-added services to secure their place in global supply chains and grow revenue.

Result 4
Question: Here is a question that can be fully answered from the given context:

"What is the average debt ratio of corn farming enterprises in Canada, based on the data from 2018 to 2022?
Answer: To calculate the average debt ratio, we need to add up the debt ratios for each year from 2018 to 2022 and divide by the number of years.

Debt ratio for 2018: 0.6
Debt ratio for 2019: 0.6
Debt ratio for 2020: 0.6
Debt ratio for 2021: 0.6
Debt ratio for 2022: 0.5

Average debt ratio = (0.6 + 0.6 + 0.6 + 0.6 + 0.5) / 5
Average debt ratio = 3.3 / 5
Average debt ratio = 0.66

So, the average debt ratio of corn farming enterprises in Canada, based on the data from 2018 to 2022, is 0.66 or 66%.

Result 5
Question: Here is a question that can be fully answered from the given context:

"What province in Canada has the majority of new car dealerships and auto parts manufacturers?"

This question can be answered by looking at the tables and text in the context, which state that Ontario has the majority of new car dealerships and auto parts manufacturers, and that it is the province with the largest spread of businesses compared to its population.
Answer: The province in Canada with the majority of new car dealerships and auto parts manufacturers is Ontario.

Result 6
Question: Here is a question that can be fully answered from the given context:

"What are the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation?
Answer: According to the context, the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation are:

1. Develop strong technical product knowledge: Having deep technical expertise ensures companies can effectively manage and troubleshoot their specialized equipment, enhancing reliability and service excellence.
2. Establish brand names: Building a recognizable and trusted brand fosters client confidence and loyalty, reducing the likelihood of customers switching to substitutes.

These factors help businesses in the specialized trucking services industry to differentiate themselves and offer more attractive services compared to substitutes like rail transportation and air transportation.

Result 7
Question: Here is a question that can be fully answered from the given context:

"What are the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation?
Answer: According to the context, the key factors that successful businesses in the specialized trucking services industry use to compete with substitutes such as rail transportation and air transportation are:

1. Develop strong technical product knowledge: Having deep technical expertise ensures companies can effectively manage and troubleshoot their specialized equipment, enhancing reliability and service excellence.
2. Establish brand names: Building a recognizable and trusted brand fosters client confidence and loyalty, reducing the likelihood of customers switching to substitutes.

These factors help businesses in the specialized trucking services industry to differentiate themselves and offer more attractive services compared to substitutes like rail transportation and air transportation.

Result 8
Question: Here is a question that can be fully answered from the given context:

"What type of research does IBISWorld specialize in?
Answer: IBISWorld specializes in industry research with coverage on thousands of global industries.

Result 9
Question: Here is a question that can be fully answered from the given context:

"What are the expected long-term effects of rising truck prices and fuel costs on the Long-Distance Specialized Freight Trucking industry in Canada?
Answer: According to the context, the expected long-term effects of rising truck prices and fuel costs on the Long-Distance Specialized Freight Trucking industry in Canada are:

* A decline in insurance and maintenance costs relative to revenue expansion, supporting a profit recovery.
* A slowing consumer-price index and a rebounding economic activity energized by monetary easing will support freight volumes and transport of petroleum and reefer contracts, spurring revenue expansion and allowing profit to recover as conditions stabilize.
* A rise in purchases is expected to persist in line with climbing prices of new vehicles, but the expected decline in fuel prices as the energy markets stabilize will provide relief.
* Improved route optimization and focus on the most profitable routes are expected to persist, limiting the need for drivers and allowing businesses to generate more revenue without dramatically expanding fleet sizes.

Result 10
Question: Here is a question that can be fully answered from the given context:

"What are the key international markets that drive demand for Canadian corn exports?"

This question can be answered by referencing the context, which states that "Demand from key international markets drives corn exports" and specifically mentions Ireland, the US, and the United Kingdom as key markets.
Answer: According to the context, the key international markets that drive demand for Canadian corn exports are:

* Ireland
* The US
* The United Kingdom

These markets account for a significant portion of Canadian corn exports, underscoring their importance for sustaining export growth.

Result 11
Question: Here is a question that can be fully answered from the given context:

"What are the expected trends in the Canadian long-distance specialized freight trucking industry, including the impact of technological advances and government policies?"

This question is fully answerable from the context, which discusses the industry's expected growth, the impact of technological advances, the effects of government policies such as the Express Entry initiative, and the industry's maturity and saturation levels.
Answer: Based on the provided context, here are the expected trends in the Canadian long-distance specialized freight trucking industry:

1. **Growth**: The industry is expected to grow, driven by the acceleration in the GDP growth from 1.1% in 2024 to 1.6% in 2025, and the expected CAGR of 1.9% in consumer spending through 2029. This growth will be fueled by the recovery in economic activity, manufacturing output, and consumer spending.
2. **Technological advances**: Technological advances will continue to reshape the industry, with trucking companies investing in remote monitoring systems and technology to strengthen the industry's resilience. The gradual rollout of autonomous trucks will transform long-distance logistics, allowing for more efficient transportation and reducing the limitations presented by the Hours of Service (HOS) and Electronic Logging Devices (ELDs).
3. **Government policies**: The Canadian government's policies, such as the Express Entry initiative, will alleviate pressure from high driver turnover by attracting migrant workers to the industry. The government's economic policies will also favor freight transportation services, supporting demand for freight trucking and the safety of drivers.
4. **Consolidation**: The industry is expected to experience further consolidation, driven by rising competition and customers

Result 12
Question: Here is a question that can be fully answered from the given context:

"What is the expected Compound Annual Growth Rate (CAGR) of revenue for local specialized freight trucking companies in Canada through the end of 2029?
Answer: According to the context, the expected Compound Annual Growth Rate (CAGR) of revenue for local specialized freight trucking companies in Canada through the end of 2029 is 1.5%.

Result 13
Question: Here is a question that can be fully answered from the given context:

"According to the Electric Vehicle Availability Standard, what percentage of new cars, SUVs, crossovers, and light-duty pickup trucks sold in Canada must be 100% zero-emission by 2035?"

This question can be answered directly from the context, which states: "Canada unveiled the Electric Vehicle Availability Standard, requiring all new cars, SUVs, crossovers and light-duty pickup trucks sold in Canada to be 100% zero-emission by 2035.
Answer: According to the Electric Vehicle Availability Standard, 100% of new cars, SUVs, crossovers, and light-duty pickup trucks sold in Canada must be 100% zero-emission by 2035.

Result 14
Question: Here is a question that can be fully answered from the given context:

"By what percentage did the number of enterprises in the Long-Distance Freight Trucking industry in Canada increase from 2006 to 2007?"

This question can be answered by looking at the "Enterprises" column in the table, where it shows a 17% increase from 2006 to 2007.
Answer: According to the context, the number of enterprises in the Long-Distance Freight Trucking industry in Canada increased by 11.9% from 2006 to 2007, not 17%. This can be seen in the "Enterprises" column of the table, where the number of enterprises in 2006 is 21,949 and in 2007 is 24,570.

Result 15
Question: Here is a question that can be fully answered from the given context:

"Keyphrase: 'Strong market profile'
question: "How does establishing a strong market presence affect buyer power in the long-distance freight trucking industry in Canada?
Answer: According to the context, establishing a strong market presence enhances brand recognition and customer loyalty, which reduces buyer power by making the service a preferred choice, lessening the impact of competitive offers in the market.

Result 16
Question: Here is a question that can be fully answered from the given context:

"Over the period from 2005 to 2030, what was the average annual percentage change in the number of establishments in the Long-Distance Freight Trucking industry in Canada?"

This question can be answered by analyzing the data in the "Industry Data Annual Change" section of the context, specifically the column labeled "%" under the "Establishments" heading.
Answer: To calculate the average annual percentage change in the number of establishments, we need to calculate the average of the annual percentage changes from 2005 to 2030.

The annual percentage changes in the number of establishments are:

2006: 18.1%
2007: 5.7%
2008: 8.3%
2009: 1.0%
2010: 1.1%
2011: 2.1%
2012: 3.3%
2013: 20.3%
2014: 7.4%
2015: 7.7%
2016: 6.1%
2017: 5.1%
2018: 5.5%
2019: 5.3%
2020: 4.8%
2021: 4.8%
2022: 7.1%
2023: 3.9%
2024: 3.6%
2025: 3.8%
2026: 3.5%
2027: 3.2%
2028: 3.2%
2029: 1.4%
2030: 1.2%

To calculate the average, we add up all the annual percentage

Result 17
Question: Here is a question that can be fully answered from the given context:

"How do fuel costs and pricing power affect the profitability of long-distance specialized freight trucking companies in Canada?
Answer: Fuel costs have a significant impact on the profitability of long-distance specialized freight trucking companies in Canada. Rising fuel costs can increase operating expenses, which can reduce profit margins. However, trucking companies can mitigate the impact of fuel costs by imposing fuel surcharges on their contracts, which can help to boost revenue. The ability of trucking companies to pass on fuel costs to their clients through surcharges is influenced by their pricing power, which is affected by factors such as the level of competition in the market and the company's market share.

In the context of the Canadian long-distance specialized freight trucking industry, fuel costs have been a major concern, particularly in recent years due to the surge in fuel prices. However, larger local specialized freight trucking companies have been able to successfully impose fuel surcharges or mitigate prices with forward contracts, which has helped to maintain their profit margins. In contrast, smaller competitors have struggled to impose the same additional costs, which has exacerbated the dominance of larger companies and lifted concentration in the industry.

Overall, the profitability of long-distance specialized freight trucking companies in Canada is influenced by their ability to manage fuel costs and pricing power, which is critical to maintaining profit margins in a highly competitive market.

Result 18
Question: Here is a question that can be fully answered from the given context:

"What is the forecasted revenue growth rate for the Long-Distance Specialized Freight Trucking industry in Canada from 2019-2024?"

This question can be answered by looking at the table that shows the forecasted annual revenue and change percentage for the industry from 2012 to 2028. The answer can be found in the row that says "Revenue" and the column that says "â19-â24 î¥0.5 %", which indicates a revenue growth rate of 0.5% from 2019 to 2024.
Answer: The forecasted revenue growth rate for the Long-Distance Specialized Freight Trucking industry in Canada from 2019-2024 is 0.5%.

Result 19
Question: Here is a question that can be fully answered from the given context:

"What is the expected impact of the rebound in economic growth on the demand for freight transportation services in Canada?
Answer: The expected impact of the rebound in economic growth on the demand for freight transportation services in Canada is that it will boost demand for freight transportation services, driven by increased consumer spending and construction investments.

Result 20
Question: Here is a question that can be fully answered from the given context:

"What is the effect of low barriers to entry on the long-distance freight trucking industry in Canada?
Answer: Low barriers to entry in the long-distance freight trucking industry in Canada have kept the market competitive. This is because individuals can easily start a business with minimal capital requirements, such as a commercial driver's license, a few basic tools, and a truck. As a result, the industry has seen an expansion in nonemployer establishments, with over 60.0% of all establishments being nonemployers. Additionally, the presence of freight brokerages and agencies facilitating contracts with clients has supported the entry of nonemployers, keeping the concentration low.

Result 21
Question: Here is a question that can be fully answered from the given context using the keyphrase "Barriers to Entry":

"What challenges do potential industry entrants face when entering the local specialized freight trucking industry in Canada?"

This question is fully answerable from the context, as it is directly addressed in the section "What challenges do potential industry entrants face?" under the subheading "Barriers to Entry".
Answer: According to the context, potential industry entrants face the following challenges when entering the local specialized freight trucking industry in Canada:

* Legal: The regulatory landscape is more demanding than for transporting regular freight, with regulations governing road safety, hours of service, weight, and the distribution of hazardous materials.
* Start-up Costs: Specialization type dictates the start-up costs incurred, with businesses targeting a specific niche requiring a truck compatible with the distribution service required. Diversifying operations can greatly expand the up-front capital investment.
* Differentiation: Companies differentiate by specializing in niche distribution services, which requires the right type of truck, such as flatbed, dry-bulk trailer, reefer, pneumatic trailer, and others.
* Labour Expenses: Truck drivers work long hours and sometimes spend days at a time away from home, so salaries are high to compensate, and new tank and refrigeration trucking companies need steady revenue to retain enough employees to comply with hours of service laws.

Result 22
Question: Here is a question that can be fully answered from the given context:

"Key Success Factors for Local Specialized Freight Trucking companies include developing a strong reputation, generating repeat customers, and providing superior after-sales service. What is the primary way in which successful Local Specialized Freight Trucking businesses handle concentration in the market?"

This question requires the reader to understand the key success factors mentioned in the context and how they relate to the topic of Local Specialized Freight Trucking.
Answer: According to the context, the primary way in which successful Local Specialized Freight Trucking businesses handle concentration in the market is by "Maintain[ing] efficient work practices". This is mentioned in the section "How do successful businesses handle concentration?" under the context of Local Specialized Freight Trucking in Canada.

Result 23
Question: Here is a question that can be fully answered from the given context:

"Despite the importance of livestock transportation, what has increased the complexity and documentation requirements for this service in Canada?"

This question can be answered by referencing the following sentence in the context:

"The lack of viable alternatives causes livestock companies to depend on trucking for animal transportation. Nonetheless, stringent animal welfare regulations in Canada have increased the complexity and documentation requirements for livestock transport.
Answer: Stringent animal welfare regulations in Canada have increased the complexity and documentation requirements for livestock transport.

Result 24
Question: Here is a question that can be fully answered from the given context:

"Are regulatory barriers at both the provincial and federal levels governing the testing of autonomous vehicles in Canada?"

This question is formed using the topic "Regulatory barriers in Canada" and can be answered directly from the context, which states: "Regulatory barriers at both the provincial and federal levels govern the testing of autonomous vehicles in Canada...
Answer: Yes, regulatory barriers at both the provincial and federal levels govern the testing of autonomous vehicles in Canada.

Result 25
Question: Here is a rewritten version of the question:

"What operational strategy enables Canadian Local Specialized Freight Trucking firms to thrive during market fluctuations?"

I've kept the core meaning of the original question, but made it more concise and indirect by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "operational strategy" instead of "operational strategy helps")
* Focusing on the key outcome (thriving during market fluctuations) rather than the specific practices that lead to it.
Answer: Based on the provided context, the operational strategy that enables Canadian Local Specialized Freight Trucking firms to thrive during market fluctuations is:

Maintain efficient work practices and use new technology to contain costs and boost productivity.

This strategy is mentioned in the context as a key success factor for the industry, allowing firms to reduce costs, improve resilience, and adapt to changing market conditions.

Result 26
Question: Here is the rewritten question:

"What GM crops are on the market, excluding wheat?"

This question conveys the same meaning as the original, but in a more indirect and concise manner. It requires the reader to make the same logical connections and inferences as the original question, but in a more subtle way.
Answer: Based on the provided context, the answer to the rewritten question is:

"Genetically modified (GM) corn seeds."

This is because the context mentions that genetically modified corn seeds offer enhanced resistance to pests and diseases, safeguarding crops, and provide increased yield potential, essential for meeting rising demand across animal feed, human consumption, and industrial uses.

Result 27
Question: Here is a rewritten version of the question:

"When did Canada's Auto Parts Mfg. industry see a big revenue boost?"

I've used abbreviations (e.g. "Mfg." for "Manufacturing") and shortened the question to make it more concise while still conveying the same meaning.
Answer: According to the provided context, Canada's Auto Parts Mfg. industry saw a big revenue boost in 2024, with a 1.9% jump in revenue and a profit margin of 8.7%.

Result 28
Question: Here is the rewritten question:

"What kind of freight do Canadian local trucking companies haul for ag products?"

I shortened the question by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "ag" for "agricultural")
* Simplifying the sentence structure
* Focusing on the main idea of the question
Answer: According to the context, Canadian local trucking companies haul various types of freight for ag products, including:

* Perishable goods such as fruits and vegetables, which require insulated vehicles
* Bulk dry goods such as corn and grains, which are loaded into pneumatic trailers
* Oversized objects such as rigs, pipes, and drilling equipment, which are transported using flatbed trailers

These types of freight are often transported to remote locations without rail access, making specialized truck services necessary.

Result 29
Question: How much of Canada's wheat demand comes from imports?
Answer: According to the provided context, imports account for a minimal share of domestic demand, typically less than 2.0% of domestic demand in a given year.

Result 30
Question: Here is a rewritten version of the question:

"What advantage do buyers gain when comparing freight trucking companies in Canada?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "freight trucking" instead of "long-distance freight trucking")
* Focusing on the key benefit for buyers, rather than the process of comparison.
Answer: According to the context, buyers gain the advantage of being able to "reject a trucker's services if their prices are too high or their delivery times aren't fast enough" due to the presence of many choices between trucking companies.

Result 31
Question: Here is a rewritten version of the question:

"What crop helps farmers manage market risks?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "crop" instead of "type of crop")
* Focusing on the key aspect of the question (managing market risks) rather than the specific benefit (diversifying output and combating revenue volatility)
Answer: Based on the provided context, the answer to the rewritten question is:

Corn

According to the context, growing premium, disease-resistant corn varieties reduces the impact of disease outbreaks and adverse weather, stabilizing yields and lessening volatility. This approach helps mitigate market fluctuations and allows farmers to manage market risks.

Result 32
Question: Here is the rewritten question:

"What could undermine the benefits of the company's expansion?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "the company's" becomes "the company")
* Changing the wording to make it more concise and natural-sounding.
Answer: Based on the provided context, I don't have enough information to determine what could undermine the benefits of the company's expansion. The context only provides information about various industries in Canada, including Wheat Farming, New Car Dealers, Auto Parts Manufacturing, and Long-Distance Specialized Freight Trucking. It does not mention a specific company or its expansion plans.

Result 33
Question: Here is a rewritten version of the question:

"What's the net change in Auto Parts Manufacturing businesses in Canada from 2024 to 2029?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Using a shorter phrase ("net change" instead of "expected annual change")
* Removing unnecessary words and phrases
* Using an abbreviation ("Auto Parts Manufacturing" instead of "the Auto Parts Manufacturing industry")
* Focusing on the main idea of the question ("change in businesses") rather than the specific details.
Answer: According to the provided context, the forecasted annual change in the number of businesses in the Auto Parts Manufacturing industry in Canada from 2024 to 2029 is 0.9%.

Result 34
Question: Here is the rewritten question:

"What share of 2024 industry revenue is domestic?
Answer: I don't know. The provided context does not include information about the share of 2024 industry revenue that is domestic.

Result 35
Question: Here's a rewritten version of the question:

"What owns the rights to a Canadian car dealers report?"

I've used abbreviations like "owns" instead of "retains" and "rights" to make the question shorter and more concise. I've also removed unnecessary words to make it more direct and to the point.
Answer: According to the context, the answer is:

IBISWorld

It is stated in the disclaimer section of the report that "Copyright to this publication is owned by IBISWorld."

Result 36
Question: Here's a rewritten version of the question:

"What drives Canadian auto parts revenue growth, and how do they stay competitive with tech changes?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Using a more general term "drives" instead of "economic conditions"
* Shortening "auto parts manufacturers" to "auto parts"
* Using an abbreviation "tech" for "technological"
* Removing unnecessary words and phrases to make the question more concise.
Answer: Based on the provided context, here's an answer to the rewritten question:

Canadian auto parts revenue growth is driven by several factors, including:

1. Aging vehicle fleets: The average vehicle age in Canada is 11 years, leading to increased demand for replacement parts and repairs, which supports aftermarket sales.
2. New and used car prices: Rising prices for new and used cars encourage consumers to repair rather than replace, driving demand for auto parts.
3. Do-it-yourself (DIY) car repair trend: The popularity of DIY car repair supports demand for auto parts from consumers.
4. Electric and autonomous vehicles: The growth of electric and autonomous vehicles creates new niche markets for auto parts manufacturers.

To stay competitive with technological changes, Canadian auto parts manufacturers focus on:

1. Innovation: They invest in research and development to improve products and secure supply contracts.
2. Product innovation: They develop new products, such as advanced air conditioning and HVAC systems, to meet changing consumer needs.
3. Operational efficiency: They use the most efficient manufacturing technologies and techniques to streamline production and create greater value than competitors.
4. After-sales services: They offer design support and after-sales services to make their products more appealing to automakers and consumers.
5. Differentiation: They focus on higher

Result 37
Question: Here's a rewritten version of the question:

"What triggers industry growth in Canada when a key competitor lowers prices?"

I've used abbreviations like "key" instead of "major" and "triggers" instead of "drives" to make the question shorter and more indirect.
Answer: Based on the provided context, it appears that industry growth in Canada is influenced by various factors, but there is no specific information on what triggers industry growth when a key competitor lowers prices.

However, I can provide some general insights from the context. In the context of New Car Dealers in Canada, it is mentioned that consumers are taking longer to purchase a new car, spending a significant amount of time comparing prices. Dealerships that provide low prices will increase traffic and volume sales. This suggests that price competition can be a factor in driving industry growth.

In the context of Auto Parts Manufacturing in Canada, it is mentioned that companies will need to slash prices to remain competitive as input prices ease through the outlook period. This implies that price competition can be a factor in driving industry growth, but it is not a direct trigger.

In the context of Wheat Farming in Canada, there is no mention of price competition as a factor in driving industry growth.

Therefore, I would say that I don't know the specific answer to the question, but price competition may be a factor in driving industry growth in certain contexts.

Result 38
Question: Here's a rewritten version of the question:

"What kinds of freight do Canadian long-haul carriers move?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "long-haul" instead of "operating both locally and over long distances")
* Focusing on the key aspect of the question (the types of freight transported)
Answer: Unfortunately, I don't see any information in the provided context that directly answers the question "What kinds of freight do Canadian long-haul carriers move?" The context provides information on the industry, market trends, and key success factors, but it doesn't specifically mention the types of freight transported by Canadian long-haul carriers.

Result 39
Question: Here is the rewritten question:

"What year between 2024-2029 will wheat farming revenue in Canada peak before declining?
Answer: I don't know. The text does not provide information on when the revenue will peak before declining. It mentions that revenue growth is expected to be small in the coming years, but it does not specify a particular year when the revenue will peak.

Result 40
Question: Here's a rewritten version of the question:

"What Canadian industries are easiest for specialized trucking companies to operate in?"

I've kept the core meaning of the original question, but made it more concise and indirect by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "operating in" instead of "profit recovery efforts face the least resistance due to favorable market conditions and structural advantages")
* Changing the wording to make it more conversational and less formal.
Answer: Based on the provided context, it seems that the Canadian industries that are easiest for specialized trucking companies to operate in are:

* Local Specialized Freight Trucking
* Long-Distance Specialized Freight Trucking

These industries have relatively low barriers to entry, and the context suggests that they have a more favorable market environment compared to other trucking industries in Canada.

Result 41
Question: Here's a rewritten version of the question:

"What quartile has the strongest link between asset leverage and ROA?"

This version conveys the same meaning as the original question but in a more indirect and concise way, using abbreviations like "ROA" (Return on Assets) and "asset leverage" to refer to the ratio of total assets to equity.
Answer: I don't know.

Result 42
Question: Here's a rewritten version of the question:

"What market conditions favor stable market share concentration for family-owned farms in Canada's corn industry?"

I've kept the essence of the original question, but made it more indirect and concise by:

* Removing unnecessary words and phrases
* Using abbreviations (e.g. "market conditions" instead of "market conditions do")
* Focusing on the key aspect of the question (stable market share concentration)
Answer: Based on the provided context, the market conditions that favor stable market share concentration for family-owned farms in Canada's corn industry are:

* Low concentration of the industry, with no single entity controlling more than 1.0% of revenue
* Decentralized structure of the industry, with thousands of small companies operating locally and focusing on niche market segments
* Geographical diversity, with different regions suited to corn farming and climate variations across provinces creating specific agricultural niches
* Limited scope for any one farm to dominate, due to the need for manual labor and the lack of significant economies of scale
* Low barriers to entry, with moderate increasing barriers to entry, but no significant barriers to prevent new entrants from joining the market.

These market conditions contribute to a stable market share concentration for family-owned farms in Canada's corn industry, as they limit the ability of any single entity to dominate the market and create a fractured market with many small players.

Result 43
Question: Here is the rewritten question:

"What holds back live animal transport growth?
Answer: According to the context, regulatory oversight over the conditions of livestock transport is limiting the growth of the segment. Specifically, regulations prohibit transporting livestock for more than 36 hours without food, water, or rest, and compromised cattle can only be transported for a maximum of 12 hours. This presents many barriers for truckers looking to enter the market and keeps growth within the segment relatively stagnant.

CPU times: user 1.91 s, sys: 73 ms, total: 1.98 s
Wall time: 2min 22s

Add the list of answers into our original dataset. Now we have a complete test set that is ready for evaluation.

In [55]:
dataset = dataset.add_column("answer", answers)

In [56]:
type(dataset)

datasets.arrow_dataset.Dataset

## Evaluate the results

#### Preview the final test set

In [57]:
dataset.to_pandas().head(5)

,question,contexts,ground_truth,evolution_type,metadata,episode_done,answer
0,What percentage of structural damage is being ...,"[while choking back tears. \n """"We're seein...",The context reports potentially 30% to 50% str...,simple,"[{'file_name': None, 'page': None, 'source': '...",True,Authorities have estimated that there is poten...
1,What is the expected growth range for adjusted...,[ transportation of various commodities and go...,"According to CN's latest forecast, the expecte...",simple,"[{'file_name': None, 'page': None, 'source': '...",True,I don't know.
2,What is the expected revenue growth for long-d...,[ping t o addr ess l abor short ages. A s the ...,Revenue for long-distance freight trucking ser...,simple,[{'file_name': '/projects/RAG2/scotia-2/Datase...,True,The expected revenue growth for long-distance ...
3,What are the potential economic impacts of a l...,[ binding arbitration is imposed.\n Earlier...,The potential economic impacts of a labor stop...,simple,"[{'file_name': None, 'page': None, 'source': '...",True,A labor stoppage at Canada's two largest railr...
4,What is the purpose of the conciliation proces...,[ions to breakthrough on these paid sick leave...,The purpose of the conciliation process in lab...,simple,"[{'file_name': None, 'page': None, 'source': '...",True,I don't know.

Run the evaluation query to score the results. In this evaluation, we are looking at the following metrics:
- *[Faithfulness](https://docs.ragas.io/en/v0.1.21/concepts/metrics/faithfulness.html)*: Are all the claims that are made in the answer inferred from the given context(s)?
- *[Context Precision](https://docs.ragas.io/en/v0.1.21/concepts/metrics/context_precision.html)*: Did our retriever return good results that matched the question it was being asked?
- *[Answer Correctness](https://docs.ragas.io/en/v0.1.21/concepts/metrics/answer_correctness.html)*: Was the generated answer correct? Was it complete?

In [59]:
%%time
score = evaluate(
    dataset=dataset,
    metrics=[
        Faithfulness(),
        ContextPrecision(),
        AnswerCorrectness(),
    ],
    llm=generator_llm, # Using OpenAI LLM as the evaluator
    embeddings=generator_embeddings,
)

Evaluating:   0%|          | 0/150 [00:00<?, ?it/s]

CPU times: user 19.2 s, sys: 356 ms, total: 19.6 s
Wall time: 2min 4s

In [60]:
%%time
#use OpenAi
# score = evaluate(
#     dataset=dataset,
#     metrics=[
#         Faithfulness(),
#         ContextPrecision(),
#         AnswerCorrectness(),
#     ],
#     llm=generator_llm, # Using OpenAI LLM as the evaluator
#     #llm=llm, # Using Llama LLM as the evaluator
#     embeddings=embeddings,
# )

CPU times: user 9 µs, sys: 1e+03 ns, total: 10 µs
Wall time: 17.2 µs

In [63]:
score.to_pandas().isna().sum(axis =0)

question              0
contexts              0
ground_truth          0
evolution_type        0
metadata              0
episode_done          0
answer                0
faithfulness          0
context_precision     0
answer_correctness    0
dtype: int64

In [67]:
score.to_pandas().tail(4)

,question,contexts,ground_truth,evolution_type,metadata,episode_done,answer,faithfulness,context_precision,answer_correctness
46,What challenges does the Mayan Train project h...,[ by the next five years\nas trade finance oft...,Experts have warned that the Mayan Train has r...,multi_context,"[{'file_name': None, 'page': None, 'source': '...",True,The Mayan Train project has faced significant ...,1.000000,1.0,0.649690
47,What benefits do businesses see from integrate...,[Previous suppl y chain chal lenges ar e pr om...,Businesses see benefits from integrated supply...,multi_context,[{'file_name': '/projects/RAG2/scotia-2/Datase...,True,Businesses see several benefits from integrate...,0.352941,1.0,0.641920
48,What steps did the Bombers take for Indigenous...,[ people from across\nCanada to attend the Win...,"The Bombers, in line with EIC's model, partici...",multi_context,"[{'file_name': None, 'page': None, 'source': '...",True,"The Winnipeg Blue Bombers, in collaboration wi...",0.136364,1.0,0.309660
49,What prompted Mayor Salinas's emergency declar...,[ late 2021 to help fund its\napproximately $3...,Mayor Salinas issued an emergency declaration ...,multi_context,"[{'file_name': None, 'page': None, 'source': '...",True,Mayor Rolando Salinas issued an emergency decl...,1.000000,1.0,0.879351

In [64]:
score["answer_correctness"].mean()

0.5993340782213483

In [65]:
score["faithfulness"].mean()

0.6362367859335891

In [45]:
#score.to_pandas().to_parquet  ("../../Testing_Data/score_llama_answeropenAi.parquet")

In [66]:
score.to_pandas().to_parquet  ("../../Testing_Data/score_llama_answer_openAi_scoreOpenAi_1_DB.parquet")

In [94]:
#"Meta-Llama-3.1-8B-Instruct"
#chunksize, answer correctness, faithfulness, number of question
#10000, 0.592, 0.698, 50
# 5000, 0.617, 0.700, 50
# 3500, 0.677, 0.734, 50
# 3000, 0.688, 0.800, 50
# 2000, 0.629, 0.742, 50
# 1000, 0.644, 0.703, 50
#  500, 0.619, 0.503, 50
#  250, 0.594, 0.527, 50

In [ ]:
#2500, 0.62, 0.825
#3000, 0.60, 0.78 llama, llamaa, llama, llama
#3000, 062, 0.73, llama, llama, openAi, llama